### ISSUE TITLE
Max min average in mobile apps

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1001]
Description:

Max/min/average mobile apps implementation

Add menu item:

Show min/max/avg (when minmaxavg hidden)
Hide min/max/avg (when minmaxavg shown)

Confirm from Elias the formula used for calculation

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/7b99b579-5a06-4880-a3d2-bd29a932aa41)

default in chart is that min/max/avg is shown

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1461

**Comment by markoaamunkajo** [comment]
Some ideas

![Image](https://user-images.githubusercontent.com/50437378/235580281-cce46733-863d-4456-aa5e-a19505e00ab7.png)
![Image](https://user-images.githubusercontent.com/50437378/235580282-4ddaf5ea-305d-4349-ac45-b9c8bdd944e2.png)

**Comment by DG12** [comment]
Personally I like 'AVG' in between min and Mac

**Comment by andreevdenis** [comment]
Correct order: Min max avg

**Comment by markoaamunkajo** [comment]
Moved to 2.6 sprint

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like the menu item is missing

Add menu item:

Show min/max/avg (when minmaxavg hidden)
Hide min/max/avg (when minmaxavg shown)

**Comment by markoaamunkajo** [comment]
QA passed
