### ISSUE TITLE
Implement settings in app for testing internal cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1031]
Description:

Implement settings in app for testing internal cloud features.
On iOS this is done in dev build by setting available under defaults menu item.

**Comment by markoaamunkajo** [comment]
Ask @ojousima about the URL to be used for dev

**Comment by ojousima** [comment]
Should be in testnet.ruuvi.com, but I'm not sure if that routes properly. Let me know on Monday when the DNS has propagated

**Comment by markoaamunkajo** [comment]
QA passed
