### ISSUE TITLE
Alarm at 66F but range LT30 GT95 - BUG 2.3.4

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#1033]
See attached screen shots.
![450A_66Falarm](https://github.com/ruuvi/com.ruuvi.station/assets/2365961/13a019a7-aac7-4100-8d43-76b1ebbbe55c)

![450A_setting_LT30_GT95](https://github.com/ruuvi/com.ruuvi.station/assets/2365961/c45b91d9-3deb-4f42-97db-e879243997c7)

**Comment by laurijamsa** [comment]
We actually got also another similar report yesterday but couldn't reproduce yet. @andreevdenis

**Comment by andreevdenis** [comment]
@DG12 thanks for report! Preparing hotfix now.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
Fixed in 2.3.5
