### ISSUE TITLE
Cloud Connection alert

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1036]
Description:

Add Cloud connection alert to Sensor Settings page

This alert is shown only to PRO subscription level or higher

Default alert interval is 15 minutes
Minimum is 2 minutes

User can adjust in 1 minute intervals

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/eef92df1-7a9e-4e36-9a2d-f4640a31e08f)

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1514

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like this line is not filled all the way to the right side. Do we have other locations where line is not full? Maybe this should be full.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/899a31ac-9b9d-411f-a9ea-8b8c6e6e598c)

**Comment by andreevdenis** [comment]
@markoaamunkajo we have the same for other alerts edit
![image](https://github.com/ruuvi/com.ruuvi.station/assets/24788772/b5f1bdf8-64f7-4d91-8dcf-9ad4091295e4)

**Comment by markoaamunkajo** [comment]
QA passed
