### ISSUE TITLE
Calibration popup texts are capitalized

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1042]
Description:

Calibration popup CANCEL OK texts are capitalized in popup
I didn't spot these in language file

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/57c48632-c901-4d16-9e0a-058fd9f0d316)

**Comment by andreevdenis** [comment]
OK capitalized in localization project. Fixed Cancel

**Comment by markoaamunkajo** [comment]
QA passed
