### ISSUE TITLE
3.30 updated to 3.31.1

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1043]
Current version number was shown differently after fw update than when it's read from Bluetooth

Test and see what is shown

**Comment by markoaamunkajo** [comment]
Ok leaving it for now

**Comment by laurijamsa** [comment]
I think we had a similar issue on iOS earlier and we fixed it. If right now the current version info is shown before actually verifying it from the sensor, it is a totally wrong thing to do and may make user think that all is ok even if something actually went wrong during the update. I understand that this is minor and not fixing it is usually easier solution than fixing it, but still, let's keep this open in backlog, test more and estimate wotkload before deciding of not to do it.
