### ISSUE TITLE
New UTM tag for Buy Ruuvi Sensors Menu link

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1044]
Description:

We want to add new UTM tag for Buy Ruuvi Sensors Menu link
Create new ident for Buy Ruuvi Sensors Menu link as follows:

"ident_ios": "",
      "ident_android": "buy_sensors_menu_link",
      "ident_webui": "",
      "en": "https://ruuvi.com/products?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android",
      "fi": "https://ruuvi.com/fi/tuotteet?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android",
      "ru": "https://ruuvi.com/products?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android",
      "sv": "https://ruuvi.com/products?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android",
      "fr": "https://ruuvi.com/products?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android",
      "de": "https://ruuvi.com/products?utm_campaign=app_ua_nav&utm_medium=referral&utm_source=android"

**Comment by andreevdenis** [comment]
We already have this. The only difference in campain name app_ua vs app_ua_nav

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/24788772/5cf34744-932e-43e6-ae7b-70d277e77256)

**Comment by markoaamunkajo** [comment]
QA passed
