### ISSUE TITLE
Move "Change background image", remove "General", remove "Export icon"

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#1049]
Changes to Sensor Settings page
1. Move Change background image title above Name and name it Background image
2. Remove General title
3. Remove Export icon on top

![Screenshot 2023-06-30 at 12 14 58](https://github.com/ruuvi/com.ruuvi.station/assets/19531763/a83c1629-6616-4ce6-85ed-5f240c620ff4)

**Comment by markoaamunkajo** [comment]
QA passed
