### ISSUE TITLE
Add more history length options to History page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#1052]
Description:

Let's add new options to view history length in history page.

Same as on the web ui:

<img width="307" alt="image" src="https://github.com/ruuvi/com.ruuvi.station/assets/1311912/9906dbd7-3849-49dd-85b0-b7dc1e051437">

Please use same strings as in webui.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1537

**Comment by markoaamunkajo** [comment]
I see it in 2.5.4, QA passed

**Comment by markoaamunkajo** [comment]
Reopened, wrong card

**Comment by markoaamunkajo** [comment]
QA passed
