### ISSUE TITLE
Sensor view font fixes

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#1069]
1. Make the sensor title larger in size and change it to Mulish ExtraBold (this should take about the same width than the old title with old font, see the example)
2. Change small measurements' font to Mulish Bold and use the same logic with numbers and attributes as on dashboard
-> smaller "%, hpa, movements" and with less opacity

![Screenshot 2023-07-24 at 10 00 10](https://github.com/ruuvi/com.ruuvi.station/assets/19531763/dbc7216b-084e-4cbb-ad07-3d78f1eaf2e8)

**Comment by markoaamunkajo** [comment]
On S22 I feel that the humidity, pressure and movement icons are slightly oversized.
On other test phones this is not so noticeable.

What do you think @sini-maaria ?

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/9f09fef8-96ea-4d90-b3ae-e901fddca251)

**Comment by markoaamunkajo** [comment]
"no cropping, longer side max 3000px, jpg 60%" 🤔  webp doesnt give big benefits compared to well compressed jpg I think

**Comment by markoaamunkajo** [comment]
Qa passed
