### ISSUE TITLE
Support for different "gateway backends"?

### ISSUE THREAD

**Issue by micopiira** [ruuvi/com.ruuvi.station#107]
Could this app add support for directly posting data to other kind of backends like InfluxDB (Possibly a plugin architecture of some kind)?

Then you would not need https://github.com/ruuvi/ruuvi-station-influx-gateway or such running on a separate server.

**Comment by ojousima** [comment]
It would be technically doable, but currently our priority is in adding the features which already are on iOS app to Android app too. For example fetching local data from Weather API and reading logged data over GATT.

**Comment by laurijamsa** [comment]
Thanks for the idea. However, I agree with Otso that this is not currently a priority. Also, we're going to have a dedicated Ruuvi Gateway for data routing in the future. Closing this issue.
