### ISSUE TITLE
Units and formatting from push

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1074]
Description:

There are some differences in push alert formattings between Android and iOS.
Please check how these are handled in iOS app.

Please also add support for new boolean coming from API.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1544

**Comment by markoaamunkajo** [comment]
Waiting for @ojousima to create boolean. Chase him if no news.

**Comment by andreevdenis** [comment]
Will be fixed with #1079
