### ISSUE TITLE
Support plain text push alerts

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1079]
Description:

API will send push alert content for example now for Cloud Connection (offline) alert.
Android should support these sorts of push messages.

Discuss with @ojousima about implementation.
This should be done with high priority.

Remember that the old method for existing push messages should also work for time being.

**Comment by andreevdenis** [comment]
Waiting for cloud implementation

**Comment by markoaamunkajo** [comment]
Cannot still verify these since staging is broken

**Comment by markoaamunkajo** [comment]
Android confirmed, moving to done.
