### ISSUE TITLE
Change app welcome images

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#1080]
1. Beaver with mailbox. (Old image had transparency on sensors.)
2. Last beaver 

I will send you the new files.

![Screenshot 2023-08-03 at 10 36 05](https://github.com/ruuvi/com.ruuvi.station/assets/19531763/219a0b23-2608-4eb0-87e3-10f7a8a7e387)

**Comment by markoaamunkajo** [comment]
QA passed
