### ISSUE TITLE
While syncing history, tap X popup should offer continue 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#1084]
When syncing history, tapping X to abort immediately stops and displays 
![AndroidXsync_disconnected](https://github.com/ruuvi/com.ruuvi.station/assets/2365961/3ae5ec91-ba24-4c68-a3ae-3fc26245305f)

`Disconnected.
`
IOS offers a better abort download or continue waiting

**Comment by markoaamunkajo** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/6ed43f0a-2ed5-477b-9b43-ed44ca8c22da)
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/8d24ed9c-ca8a-483a-b198-d82e52650e6a)

**Comment by markoaamunkajo** [comment]
Let's implement it same way as on iOS:

1. If download fails, instead of Disconnected popup show Download failed popup, same as screenshot above
2. If user presses X, show Are you sure popup, same as screenshot above

**Comment by markoaamunkajo** [comment]
QA passed
