### ISSUE TITLE
Sync didn't timeout when no new data downloaded from sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1086]
Description:

S21 Ultra

Sensor with 3.31.1 fw
df 5

Syncing 10 days sensor data through GATT stalled at one point, Lauri waited for over 1 minute and there was no timeout.

Check that timeout occurs in 30 seconds if no new data can be downloaded from sensor.

**Comment by markoaamunkajo** [comment]
Lauri will test again after Android OS update.

**Comment by markoaamunkajo** [comment]
https://drive.google.com/file/d/1ADYk3UWqHd4EFgoQGStUQRmPgkvQPXPE/view?usp=sharing

This was tested by driving away from my house where the sensor was located.
There is no timeout, OS12.

**Comment by DG12** [comment]
This seems to be similar to IOS issue
https://github.com/ruuvi/com.ruuvi.station.ios/issues/1599

Easier way to duplicate :
This problem can be duplicated with a ruuvi with RSSI less then about -80dB
with a lot of history to sync. Get sync started then
place it on a MacBookPro keyboard then nearly closing the screen, as the aluminum case absorbs (or reflects?) the radio signal.

**Comment by markoaamunkajo** [comment]
No timeout also confirmed on OS13, when returning back to vicinity of the sensor, app starts to read advertisements.



![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/af2f4497-dd3e-4cd7-aeb3-d428fdb852de)

**Comment by markoaamunkajo** [comment]
2.6.4 the issue is same. This was just recently fixed in iOS, I think Muzibur found a working solution.

Here are 2 videos of what happens:

1. Bluetooth sync started and moved away from sensor, waiting for timeout, which never happens
https://drive.google.com/file/d/10GZJlxdK54syp0mLs6IL9F9APuefUKWU/view?usp=sharing

2. Moved back to sensor range, sync didn't continue but Bluetooth started updating measurements
https://drive.google.com/file/d/109WjCcv9y44d2P6zto9EbtjjUIXoZzSA/view?usp=sharing

**Comment by markoaamunkajo** [comment]
QA passed
