### ISSUE TITLE
Sync status icon to sensor settings page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1087]
Description:

Show sync status as toast message on sensor settings page when user is signed in:

activity_saving_to_cloud
activity_saving_success
activity_saving_fail

Use same toast as other errors.

Let's do it for sensor settings page first.

Automatic retry or next app open case: how we tell to user that it got stored, do we need to modify logic somehow?

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1600

**Comment by markoaamunkajo** [comment]
Requires loading icon from Sini-Maaria

**Comment by markoaamunkajo** [comment]
@andreevdenis this is the idea we are looking for as animation

https://codemyui.com/progress-and-tick-icon-animation/

Can this be done with default Android icon set or do you need custom animation?

**Comment by markoaamunkajo** [comment]
@andreevdenis The saving delay is too long.

https://github.com/ruuvi/com.ruuvi.station/assets/50437378/77eaad9a-20da-4170-9e94-c11301617e75


Other notes:

On iOS you are not able to leave the page until saving is done. I believe this is to prevent saving to fail.

**Comment by andreevdenis** [comment]
@markoaamunkajo 
Saving delay is standard for Android short message. There are 3 options: 4s, 10s and indefinite. We can do it shorter but with hacky way so I don't think it worth it. 

As for blocking UI until saving is done I believe this a bad practice, especially if leaving screen won't prevent saving which is our case.

**Comment by markoaamunkajo** [comment]
@andreevdenis is our short message now using 4s?

**Comment by andreevdenis** [comment]
Yes

**Comment by markoaamunkajo** [comment]
Discussed with Lauri, this is good for now.
