### ISSUE TITLE
Deep linking in email URL

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1092]
Description:

Discuss with @ojousima about format for deep linking to open sensor card from email in iOS app.

https://github.com/ruuvi/ruuvi.cloud.js/issues/389

Also support card for web:
https://github.com/ruuvi/com.ruuvi.station.webui/issues/359

**Comment by markoaamunkajo** [comment]
@andreevdenis currently opening webUI in browser. I'm not completely sure if link should be formatted to something else than what I used.

https://github.com/ruuvi/com.ruuvi.station/assets/50437378/18ffa4fb-ecd0-4d01-8f76-991aefb3d274

**Comment by andreevdenis** [comment]
It should open app from https://station.ruuvi.com/dashboard


But actually I can see it's not working out of the box for fresh Android versions, only for Android 9. I'll take a look

**Comment by markoaamunkajo** [comment]
QA passed
