### ISSUE TITLE
Temperature offset Fahrenheit  YAFPP calibrate to 60, says 60.01 - minor 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#1102]
User calibrates to 60F, app acknowledges with 60.01

**Comment by markoaamunkajo** [comment]
Likely caused by rounding from Celsius, which has not enough resolution for value.
@rinat-enikeev please check and comment can we add more accuracy on Celsius value for rounding case to improve this situation?

**Comment by andreevdenis** [comment]
Changing calibration precision to 0.0001 did the job

**Comment by markoaamunkajo** [comment]
QA passed
