### ISSUE TITLE
Android 14 compatibility check

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#1116]

**Comment by andreevdenis** [comment]
@markoaamunkajo check if you have access to Android 14

**Comment by markoaamunkajo** [comment]
I will have access at the end of this month.

**Comment by markoaamunkajo** [comment]
Onboarding
Sign in
Portrait, landscape
Dashboard views
Themes
BT alerts, notifications
Alert notification sounds
Card types
Contact support
About/ help
What to measure
Shop links
Charts
Sleep / background scan

**Comment by markoaamunkajo** [comment]
There might be something related to widgets, my small widgets are not updatable using refresh button since last checking yesterday. New widgets are updating as of now. Will check tomorrow.



![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/10f14584-0f30-4fed-a41f-ed437993d5a8)

**Comment by markoaamunkajo** [comment]
Card added about widgets, moving this to done.
