### ISSUE TITLE
App crash when you try to change app language in Xiaomi phone with Android 13

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#1119]

**Comment by markoaamunkajo** [comment]
Related to forum post: https://f.ruuvi.com/t/android-apin-kielivalinta-puuttuu/6381/7

**Comment by andreevdenis** [comment]
Possible solution is to disable this feature for Xiaomi

**Comment by markoaamunkajo** [comment]
Moving to done, no Xiaomi to test

**Comment by markoaamunkajo** [comment]
Moving to done, does not occur on my devices.
