### ISSUE TITLE
If picture is taken in horizontal orientation, background photo is not updated

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1134]
Description:

Otso encountered this issue with Android Ruuvi Station.
Seems he has permission ungranted in settings.

App did not crash, only background did not update when taking photo with S21 camera.

**Comment by andreevdenis** [comment]
Not related to permissions. You can reproduce this by taking photo in horizontal orientation.

**Comment by markoaamunkajo** [comment]
QA passed
