### ISSUE TITLE
Updated time doesn't reset to 0 from Cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1141]
Description:

User has active pro subscription. Installed new build 2.6.3 and signed in to the app.

It seems Web and iOS were able to reset updated time to 0 on this example sensor, but on Android same sensor never resets counter to 0. 

Muzibur added a fix for this just recently, maybe same fix is needed on Android?

https://drive.google.com/file/d/1-UPsW9w35oIZmo7J6fNpT8LOUcQbKOyo/view?usp=sharing

Web:

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/dd1732a4-e03c-4040-9d24-6a06b975a48a)

iOS:
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/a6198df5-2d25-4a48-8d4e-5ef305bceefb)

Android:
https://drive.google.com/file/d/1-T6eLFzdrOD-FQmHNF8qu0CH6Hx_a_Q1/view?usp=sharing

**Comment by andreevdenis** [comment]
Should work as always. Please re-check @markoaamunkajo

**Comment by markoaamunkajo** [comment]
Discussed in DM, sent couple of new videos about updated times.

**Comment by markoaamunkajo** [comment]
@andreevdenis this is caused by system time being set manually and mine was 5 minutes ahead.
Tried also 1 hour behind and I can get the counter to update with negative values.

Also happens on iOS.
Is this something worth fixing? I guess most will use automatic time on their devices.

**Comment by andreevdenis** [comment]
We are comparing timestamp from the cloud with local time so this explains everything. Not worth fixing in my opinion and I'm not sure how we can fix this.

**Comment by markoaamunkajo** [comment]
Ok moving to done
