### ISSUE TITLE
Investigate if /subscription endpoint is used anywhere

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1143]
Description:

Check what /subscription endpoint is used in Android
And can this call be disabled for now, since we don't show user subs level under My Account

**Comment by andreevdenis** [comment]
Currently I use this call to get maximum shares per sensor from subscription info. Maybe later we'll need to get some additional info. Initially I wanted to update this once per 24h, but due to mistake it was updating on every sync. I've fixed this and now we won't be poking subscription too often.

**Comment by laurijamsa** [comment]
Hmm, how max number of shares per sensor is known on iOS @priyonto ? If something different, like discussed today, let's unify the apps to use the same calls in the same pages.

**Comment by priyonto** [comment]
@laurijamsa iOS uses hardcoded share limit now. We actually need to implement this endpoint in that case. I created a card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1740

**Comment by markoaamunkajo** [comment]
Moving to done
