### ISSUE TITLE
Support Bluetooth widgets

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1159]
Description:

Allow adding local Bluetooth sensors to widgets.

Remove restrictions for:
Sign in
Gateway as data source

Also allow widget to update from Bluetooth when Cloud mode is disabled.
Widget has to update automatically if sensor has been paired, background scan is enabled.
Update manually when background scan disabled and sensor not paired.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1849

**Comment by laurijamsa** [comment]
Let's prototype this and then make a decision if we want to include it in the release.

**Comment by markoaamunkajo** [comment]
The degree sign (dew) didn't update with Celsius after user signed in to account that had this same Bluetooth sensor in it.
It would also probably be a good idea to refresh sensor names when user signs in if Bluetooth sensor is claimed to account.

https://github.com/user-attachments/assets/fcf7fc30-c0da-469e-95d7-5ea840d34788
![Image](https://github.com/user-attachments/assets/c4c2e594-10cb-47ec-88ba-51b1f96d3d45)

**Comment by markoaamunkajo** [comment]
QA passed
