### ISSUE TITLE
Sensor offset in different timezone

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1178]
Description:

When you monitor sensors in a different time zone the time reference that is used at the bottom of the chart seem to be the sensors time zone. However the graph is positioned like it uses the phone/device's time zone. It makes it look like the chart is giving values from future.

Example in the screenshot below.
I am currently in GMT+8 and live in GMT+1. The 7h time difference causes an offset.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/a98fc432-5c61-4123-8dda-8cd74500742b)

**Comment by markoaamunkajo** [comment]
We will always use local timezone to show data.

If for example user shares sensor at his local timezone is 8 am and receiver local time is 4 am we will show that measurement at local time.

This would require new feature and we can consider it's not necessary because of not many real life use cases.

**Comment by laurijamsa** [comment]
As far as I can see, this whole issue was just a confusion because of the graph plot bug that is described in here:

 https://github.com/ruuvi/com.ruuvi.station/issues/1181
