### ISSUE TITLE
Adding new dataformat support

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#1191]
https://docs.ruuvi.com/communication/bluetooth-advertisements/data-format-c5-rawv2#case-valid-data

**Comment by markoaamunkajo** [comment]
Will move to alpha, testing can be done there

**Comment by laurijamsa** [comment]
Reopening as I think that this hasn't been tested yet. Otso has binaries that can be flashed to RuuviTag to test this.

**Comment by andreevdenis** [comment]
You can get FW here:
https://github.com/ruuvi/ruuvi.firmware.c/releases/tag/v3.32.0

You need UUID fw. I used this one: [ruuvitag_b_armgcc_ruuvifw_uuid_v3.32.0_dfu_app.zip](https://github.com/ruuvi/ruuvi.firmware.c/releases/download/v3.32.0/ruuvitag_b_armgcc_ruuvifw_uuid_v3.32.0_dfu_app.zip)

**Comment by markoaamunkajo** [comment]
@andreevdenis on More info page the data format is shown as "197", it should be reporting "c5" instead, like it's reporting in WebUI.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/976f5202-c4c4-4248-8d5a-06764441c41b)

**Comment by markoaamunkajo** [comment]
@andreevdenis

Firmware shows current version on sensor settings page as Very old and user can run firmware update on it even the version will be reported as higher on Firmware update page.

Let's not allow user to downgrade firmware in the app.

**Comment by markoaamunkajo** [comment]
QA passed
