### ISSUE TITLE
2.7 Chart history graph legend doesn't use commas for Pa

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1203]
Description:

1. There is no comma separator for Pa unit in charts (legend, last measurement)
2. Layout is broken with slightly larger than standard font size, values should not overlap with legend.

**Comment by laurijamsa** [comment]
The provided screenshot is wrong, there should not be commas in there if your system setting is not american like in this screenshot:

![IMG_20240215_114147_317.jpg](https://github.com/ruuvi/com.ruuvi.station/assets/1311912/98567f8f-7b83-49a1-a266-abe89f421848)

**Comment by markoaamunkajo** [comment]
QA passed
