### ISSUE TITLE
2.7 Sensor is showing 0C although last measurement 6 days ago shows -19.88C

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1204]
Description:

This sensor has some issue and it's being investigated on Cloud side.
https://github.com/ruuvi/ruuvi.cloud.js/issues/430

Last measurement is from 6 days ago.

Sensor card showing 0C when last measurement was -19.88. User should see all last measured sensor values.
History view shows correct last measurement for temp.

[Mökki Kitchen_20240215T111403+0700.csv](https://github.com/ruuvi/com.ruuvi.station/files/14291476/Mokki.Kitchen_20240215T111403%2B0700.csv)

**Comment by markoaamunkajo** [comment]
More details to this

The owner sees
- 3 sensor values on Android dashboard: Temperature, humidity, pressure

Sharee sees
- 1 sensor value on Android dashboard: Temperature (with incorrect reading)
- Sharee sees 3 charts with correct values on history view

**Comment by andreevdenis** [comment]
Currently the app is not supporting nullable temperature for the sensor. Supporting it is tricky and time consuming because in almost all of the screens and classes where we display and operate temperature we expect it to be not null. So we need to code behaviour for null temperature cases in many many places.

**Comment by andreevdenis** [comment]
For now we can skip measurements that come with null temperature to avoid showing wrong value (0 C). Or postpone the changes. 
@markoaamunkajo

**Comment by laurijamsa** [comment]
Let's postpone for now I would say. But we may need to fix this properly later.

I think not showing measurements that may not be correct somehow can just make it harder to spot issues or bugs in the future.

**Comment by laurijamsa** [comment]
I assume the issue https://github.com/ruuvi/com.ruuvi.station/issues/1289 requires this discussed null support and if so, it will allow to fix also this issue.

**Comment by markoaamunkajo** [comment]
@andreevdenis Was this fixed already with https://github.com/ruuvi/com.ruuvi.station/issues/1289 ?

**Comment by andreevdenis** [comment]
Emulated no temperature for one of the sensors. You can check how app behave in this situation. Alerts for temperature will be hidden also as offset correction. Humidity can be displayed only if unit set to relative, for other types temperature is needed.

https://github.com/user-attachments/assets/b76c61d0-e237-4a75-b8cf-f3a40d977458

**Comment by markoaamunkajo** [comment]
Should we hide it completely? (In latest version it is shown as - °C with unit)

Hmm yes I think we should hide it. Same way as we are hiding humi/pressure in case of pro 3in1 or 2in1

**Comment by markoaamunkajo** [comment]
QA passed
