### ISSUE TITLE
2.8.0 Mini Gateway icon occurred

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1215]
Description:

Spotted this mini Gateway icon. I believe this happened after switching between Bluetooth and Gateway icons.
This sensor is using the new firmware, but not sure if that could be the reason for it.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/16706a05-8fa9-49f9-a3d8-103db7260994)

**Comment by andreevdenis** [comment]
It's possible to reproduce by playing with CloudMode on/off. But it appears randomly. I got 7 sensors for testing and all of them are changing from Bluetooth icon to gateway, but only 1 or 2 have issues with size, every time different sensors. Not connected to FW version for sure. Anyway fix is on the way

**Comment by markoaamunkajo** [comment]
QA passed
