### ISSUE TITLE
2.8 NFC scanned sensor but Bluetooth permission asked

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1219]
Description:

User had signed in to his account in Ruuvi Station, then signed out.
Immediately after that he goes to Add a new sensor page and NFC scans a RuuviTag.

Actual: app shows message that Bluetooth needs to be turned on.
Expected: Bluetooth is on, NFC scan should add sensor card since none exists.

https://github.com/ruuvi/com.ruuvi.station/assets/50437378/f9961ca8-e41d-4868-91b7-25793194026f

**Comment by andreevdenis** [comment]
Right after sign out all data was deleted and when you first scan it with NFC there were no info about this sensor. One second later Bluetooth advertisement was received and sensor was successfully added. This probably can be improved but it's a very rare case and I don't think it worth it.

**Comment by markoaamunkajo** [comment]
Ok, let's ignore this.
