### ISSUE TITLE
Show alert triggered range with alert colour

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1220]
Description:

Show alert triggered range with alert colour in alert settings.

When setting an alert, specifying a range when the value is OUTSIDE of desired values the graphic is confusing.

Currently 
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/97667f7f-2ed4-4613-bfdf-4731715161cc)

This does show that the acceptable (non-alert) range is in the green area and states that the alert triggers when less than 37 or greater than 101.
This minor modification, highlighting the alert ranges, would be clearer

Design:
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/cf92ebeb-7dc2-45ee-9529-7dfd8df072ad)

Thank you for your consideration.
Although this issue is submitted against station IOS it applies to all station applications.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1818

**Comment by markoaamunkajo** [comment]
Updated design to the main description

**Comment by sini-maaria** [comment]
Color code for the line between the dots: #d0e2e1 in the light theme and 50% (#d0e2e1) in the dark theme.

**Comment by markoaamunkajo** [comment]
@andreevdenis lets modify the colour scheme according to Sini-Maaria's instructions.

**Comment by markoaamunkajo** [comment]
@andreevdenis sorry we decided in spec meeting to go with current implementation, no need for changes. Moving to done.
