### ISSUE TITLE
Update Crashlytics SDKs to support release monitoring

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1224]
Description:

Let's update Firebase SDK's to support release monitoring feature

https://firebase.google.com/docs/release/release-monitoring#required-sdk-versions

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1989

**Comment by andreevdenis** [comment]
Release monitoring will be available after version goes to beta

**Comment by markoaamunkajo** [comment]
Moving to done, will see in beta
