### ISSUE TITLE
Redesign text layouts for history view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1225]
UPDATE: need to hide this change under feature flag for now

Description:

We want to change the layout of the existing 3 charts in history view to this style to improve readability of chart.

Let's prototype this and see how it works with alert limits.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/b556e6c9-75da-438f-90fa-8152bf1092f2)

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1994

**Comment by markoaamunkajo** [comment]
Asking @sini-maaria about layout how it looks in her eyes.

**Comment by laurijamsa** [comment]
From iOS https://github.com/ruuvi/com.ruuvi.station.ios/issues/1994 issue:

"I think the latest could be the last one like you suggested. The second suggestion about changing the order from min-max-average to min-average-max feels not like an enhancement so I wouldn't change it for now."

**Comment by markoaamunkajo** [comment]
I don't have anything new to add to this, I will call this QA passed
