### ISSUE TITLE
Support temperature range for external temp sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1226]
Description:

Improve alert range for temperature when using ext temp sensor

1. Allow adding any value to beyond current min-max limitation
2. When edited, this value is used, with condition that min is smaller than max because app cannot know that external temperature sensor is used
3. We will not adjust slider

**Comment by andreevdenis** [comment]
New limits: -55 to 155

**Comment by markoaamunkajo** [comment]
QA passed
