### ISSUE TITLE
Follow selected resolution in all chart settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1230]
Description:

Let's improve this so that calculation is always done with precise values for Min/Max/Avg
Make sure that Last datapoint and Selected datapoint conversion uses high resolution values as well

Show in UI resolution that user has selected in settings everywhere in the app including Min/Max/Avg

(in the example image user had selected 1 degree resolution, but chart shows differently)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/c1801511-4926-43e8-a618-02cdd284317d)

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1996

**Comment by andreevdenis** [comment]
Discussed during meeting to apply user selected resolution to min/max/avg/latest. Selected point should still show full resolution anyway.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Looks like this is broken in latest build (where old text layouts are used on charts screen)

**Comment by markoaamunkajo** [comment]
QA passed
