### ISSUE TITLE
Graph datapoint optimisations (make it faster, etc)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#1236]
Swiping to next sensor is a bit laggy for example. Let's discuss how to make graphs more smooth in general first and if cannot, maybe we will disable the animation between moving different sensors by pressing the arrow icons.

**Comment by markoaamunkajo** [comment]
Handled on card https://github.com/ruuvi/com.ruuvi.station/issues/1245
