### ISSUE TITLE
Scrollbar colour on history view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1239]
Description:

History view page shows white colour scrollbar on extreme right when scrolling up and down charts.
White colour on dark themed history view page is very prominent, should a different colour be used?

**Comment by markoaamunkajo** [comment]
@sini-maaria should this be fixed?


Install latest build, rotate screen then scroll.

**Comment by laurijamsa** [comment]
I think it's fine for now. Closing.
