### ISSUE TITLE
2.9.5 lot of space in chart left side

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1242]
Description:

There seems to be a lot of empty space on left side of chart on history page.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/8501e6a9-d691-4155-a653-48c6b5cdcf60)

**Comment by andreevdenis** [comment]
To be able to sync zoom and panning between temperature, humidity and pressure charts they should have exactly the same width of timelime. Pressure has longest values on the left side so I apply same offset to temperature and humidity.

**Comment by markoaamunkajo** [comment]
Closing issue as there is no solution to fix this in short run
