### ISSUE TITLE
Add banner to logged out users

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1247]
Description:

If logged out user has locally added sensors he will see them on dashboard but he is not informed that he is currently logged out.

Banner will be shown in every case when he is logged out (was previously signed in)
User can close banner from X and it will be not appear unless next app update if he never decides to sign in

![Image](https://github.com/user-attachments/assets/cede4eaf-f80f-4fd8-8b46-e6b0b31d1682)

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/2006

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
If cloud token expires or if due to some other cloud issue app thinks user has signed out this should be shown sutomatically. Did you do these tests?

**Comment by markoaamunkajo** [comment]
These tests are impossible to do without Otso, but we will need to check cloud error behaviour so will put this back to wait for those tests.

**Comment by markoaamunkajo** [comment]
Confirmed in testing.
