### ISSUE TITLE
Google Analytics consents

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1249]
Description:

Both apps have some issues with Google Analytics with proper consents.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/20cd65dd-d9d7-4f3a-9e0d-03541d8759e2)

**Comment by andreevdenis** [comment]
https://developers.google.com/tag-platform/security/guides/app-consent?platform=android&consentmode=advanced#kotlin

**Comment by markoaamunkajo** [comment]
@andreevdenis this task seems like completed, since no more nagging in Google Console, moving to done.
