### ISSUE TITLE
Issues with old history view layout

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1250]
Description:

In the latest build you can see that the values are auto aligned, but ends up in separate rows unlike all other charts.

Also values show 00.00 for quite some time, maybe this could also be improved.

https://github.com/ruuvi/com.ruuvi.station/assets/50437378/d81e4d62-210e-4d6d-876e-95ac35d1fc84

**Comment by andreevdenis** [comment]
Looks like wrong values are displayed for pressure min/max/avg.

**Comment by andreevdenis** [comment]
Didn't do anything about showing initial 0.00 - will check it when will be working with charts performance.

**Comment by markoaamunkajo** [comment]
QA passed
