### ISSUE TITLE
Saving status toast should be shown slower

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1259]
Description:

On sensor settings page when user changes setting it will be synced to cloud with status toast popping up at bottom of the screen.

The first "saving to cloud..." status shows too fast for user to be able to read it
Let's make it a little bit slower

**Comment by andreevdenis** [comment]
@markoaamunkajo  
Actually toast for "Saving to cloud... Please wait." is showing for indefinite time. Once it's saved or failed toast is replaced by "success" or "fail" message. I can add additional delay, what should it be?

**Comment by andreevdenis** [comment]
500ms - should be delay

**Comment by markoaamunkajo** [comment]
QA passed
