### ISSUE TITLE
App can freeze when user has bg scan set to off and returns to RuuviTag signal area

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1265]
Description:

Device: samsung SM-S911B
Android version: 14
App: Ruuvi Station 2.8.2

User has background scanning set to off and leaves home where his RuuviTags are.
When he returns back to RuuviTag signal area and checks Ruuvi Station app, the app is frozen.

**Comment by markoaamunkajo** [comment]
I tested taking my old Huawei and newer S24 Android phones outside of the house with bg scan disabled and returning back woke the app and sensors update normally. I would guess that maybe some peripherals are causing issues?

**Comment by markoaamunkajo** [comment]
Tested again, did not freeze. Will give old phone one go still.

**Comment by markoaamunkajo** [comment]
I have not seen this, moving to done

**Comment by laurijamsa** [comment]
Let us try to reproduce one more time and if unsuccessful, close.

**Comment by markoaamunkajo** [comment]
Tested again few more times and it's not reproducable on my device. Closing issue.
