### ISSUE TITLE
Show all sensors in history view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1266]
Description:

We want to see how performance is affected when all sensor types are drawn into their own chart in history view page

Including:

Acceleration
Battery
Etc

Let's make a demo build with this to test it out with the new charts layout. This is only for internal test.

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like for me zooming and scrolling gets stuck in chart. I have no performance issues like Lauri posted, but feels like something crashes in the chart view.

https://github.com/ruuvi/com.ruuvi.station/assets/50437378/5ade1e04-13e5-4152-9483-74c703077682

**Comment by laurijamsa** [comment]
I don't quite understand what's not ok in the video. If this is related to the new graph view UI we are about to release in 2.11, this needs to be investigated asap

**Comment by markoaamunkajo** [comment]
Somehow the freezing zooming issue is gone in the latest build. Closing this issue as completed.
