### ISSUE TITLE
Update com.google.android.play

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#1270]
com.google.android.play:core has added this note for core:1.10.2:

Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration

You may not be able to release future versions of your app with this SDK version to production or open testing.

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like this is approved in Google Play no more nagging. Can this card be closed?
