### ISSUE TITLE
Imporove sign in logic

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#1274]
Let's change the logic for sign in and show dashboard to user right after getting main info about sensors from sensors-dense endpoint. Continue with downloading sensor history in background process. Also maybe no need to wait for downloading background images.

**Comment by markoaamunkajo** [comment]
2.11.2

To me it seems not intuitive that user needs to wait on empty chart view for all measurements to be downloaded to all charts. On iOS this is done per chart and it seems to work better. Can we implement it the iOS way instead?

https://github.com/user-attachments/assets/b967f109-a9e4-4438-a4f7-c918edc94c4d

**Comment by andreevdenis** [comment]
Decided to change order of downloading. Prioritize history over background image. Add sync indicators to history page and dashboard.

**Comment by markoaamunkajo** [comment]
Works well on my S22, needs more testing

**Comment by markoaamunkajo** [comment]
Tested also on S10+ and Android Tab.
QA passed
