### ISSUE TITLE
Remove Polish strings from language file

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1276]
Description:

Polish will not be added to app, so we may move the strings out from language file

Example

      "ident_ios": "LocalNotificationsManager.HighSignal.title",
      "ident_android": "alert_notification_rssi_high",
      "ident_webui": "",
      "en": "Signal strength too high!",
      "fi": "Signaalin voimakkuus liian korkea!",
      "ru": "Высокий уровень сигнала!",
      "sv": "För hög signalstyrka!",
      "fr": "Puissance du signal trop importante !",
      "de": "Signalstärke ist zu hoch!",
	  **"pl": "Zbyt wysoki poziom sygnału!"**

**Comment by andreevdenis** [comment]
Decided to not remove
