### ISSUE TITLE
Force claim error string not in language file, probably hard coded

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1282]
Description:

Force claim string is not in language file, probably hard coded
This should be in the language file

You are scanning a different RuuviTag

Related iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/2083

**Comment by andreevdenis** [comment]
Search for "claim_wrong_sensor_scanned" in localization

**Comment by markoaamunkajo** [comment]
Moving to done, Android is good
