### ISSUE TITLE
Minimised app on history page, on return it forces me to dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1283]
Description:

User was on history page when he minimised app.
Now when app is reopened using app icon, he lands correctly on that same history page but is quickly moved to dashboard.

Expected: keep user on the page that he was on when he minimised app to background.

**Comment by markoaamunkajo** [comment]
https://github.com/user-attachments/assets/853e4c90-a128-4a1f-8be8-a8eb40e76456

**Comment by andreevdenis** [comment]
![Image](https://github.com/user-attachments/assets/57b94048-4fb6-4881-8786-8cc3b1006dc9)

**Comment by markoaamunkajo** [comment]
Now works after disabling developer options in OS and restarting phone. Moving to done.
