### ISSUE TITLE
Point terms and  privacy policy URL to section with mobile apps details

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1284]
Description:

Point terms and  privacy policy URL to section with mobile apps details

**Comment by laurijamsa** [comment]
Links to use:

All languages except Finnish: https://ruuvi.com/privacy/#apps
Finnish: https://ruuvi.com/fi/tietosuoja/#apps

**Comment by markoaamunkajo** [comment]
Will do in localisation file

**Comment by andreevdenis** [comment]
![Image](https://github.com/user-attachments/assets/3b494a04-ae53-4f8e-ad05-eb8414b92d43)

**Comment by markoaamunkajo** [comment]
Added to localisation file, made pull request to merge to master
