### ISSUE TITLE
Use dot as separator for XLXS export

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1287]
Description:

Let's use dot as separator for XLXS export instead of comma to unify with CSV export option.
Please fix this in the 2.10 version, since XLXS is not yet out.

**Comment by markoaamunkajo** [comment]
Looks like actually it's common for English speaking countries to use comma as separator in Excel files, so closing this.

**Comment by markoaamunkajo** [comment]
This needs discussion first.

**Comment by laurijamsa** [comment]
What kind of decision is this waiting for? Let's close if all is ok.

**Comment by markoaamunkajo** [comment]
I believe we discussed and this is redundant. Closing card.
