### ISSUE TITLE
Clean install app sensor viewport shows 10 days as default should be All

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1288]
Description:

2.10.10 user made clean install of Ruuvi Station app, didn't sign in and added 1 sensor to the app.

Actual: when viewing history view page the selected viewport is 10 days.
Expected: viewport should be All by default.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
Have you seen my comments on IOS [ISSUE 2042](https://github.com/ruuvi/com.ruuvi.station.ios/issues/2042)

Just saying.
