### ISSUE TITLE
Let user go to force claim page when no internet

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1293]
Description:

On iOS user is able to go to force claim page when there is no internet (wifi off, airplane mode).
On Android, user cannot get to force claim page, he gets bounced back to sensor settings page

Expected: Allow user access to force claim page

https://github.com/user-attachments/assets/7ac58d81-7ba7-4e31-9a6e-5b32f4f7b3fc

**Comment by laurijamsa** [comment]
I think correct would be to allow to go there but if no internet, give a "no internet" toast when trying to perform a force claim. Unify with iOS.

**Comment by markoaamunkajo** [comment]
No internet toast shown when accessing page
Goes to page normally when internet

I think this is good to go.
