### ISSUE TITLE
Check image size and format limitations in app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1302]
Description:

Description:

Check image size and format limitations in app

**Comment by markoaamunkajo** [comment]
640heif
1280 heif
1920 heif

heic 1920x1280
iOS proraw_max - NO
iOS max - NO
iOS proraw_12mp - NO
jpg 1920x1280
jpg 6720x4480
jpg 8974x6434
jpg 2400x1720
jpg 1920x455
jpg 8192x2932
jpg 8268x1960
gif animation - NO
png 2400x1720
tiff 2400x1720 - NO
webp 1920x1280 - NO

**Comment by markoaamunkajo** [comment]
@andreevdenis 

Should we block picking those images that are not supported? 
Little bit surprised about webp. I tested these from Google Drive. Tested on 2 devices.

**Comment by markoaamunkajo** [comment]
Send example imagesto Denis that are not working

**Comment by andreevdenis** [comment]
Webp is supported now. For other formats users will see error message

**Comment by markoaamunkajo** [comment]
Webp now works and error messages for unsupported checked

**Comment by markoaamunkajo** [comment]
Moved to completed
