### ISSUE TITLE
Make more sparse retry errors coming from Cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1307]
Description:

In staging tests we noticed that from sensors dense we are receiving 15 seconds retry when sending error, seems that Android app is doing this.

Throttle
400 error

Expected:
Let's fix it so that retry is 1 min and if possible +1 min after that and + 1 min after that.
But even 1 min interval will be much better.

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like it doesn't work 2.11.6

400 errors: 

![Image](https://github.com/user-attachments/assets/052d1aa1-3d5b-4c37-9a0a-134745a673ad)

Throttle:

![Image](https://github.com/user-attachments/assets/d2c384aa-980b-4bfa-b976-10aa68c0177b)

**Comment by andreevdenis** [comment]
How exactly did you check it?
Please try again with latest build

**Comment by markoaamunkajo** [comment]
We checked with Otso, it requires some changes pushed to Staging
OK, will check again when we have time

**Comment by markoaamunkajo** [comment]
Will set up tests with Otso

**Comment by markoaamunkajo** [comment]
2.11.16 build

We tested with 500 error together with Otso, and retry interval seems to be closer to 20 seconds, which means this is not fixed.
This was also observed with spinning indicator at the top of the dashboard screen.

![Image](https://github.com/user-attachments/assets/3237e825-3ff3-4907-a420-3910179d8c9a)

**Comment by markoaamunkajo** [comment]
500 - Now 1 minute retry interval for 500 error
429 - Now 1 min
403 - Now 1 min
401 - user signed out

This is now fixed, moving to done.
