### ISSUE TITLE
Largest possible font size crashes app on sign in

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1312]
Description:

Actual:
User has Samsung A-series phone and Ruuvi Station app is crashing when tap on Skip button in onboarding or continue to sign in path. This crash is caused by using the biggest possible font available on the device.

Choosing second biggest font will not crash app and user is able to complete onboarding and use app normally.

Expected: make app not crash when using biggest available font

**Comment by andreevdenis** [comment]
This should be fixed now:

![Image](https://github.com/user-attachments/assets/fb42731f-a58e-42c0-a475-6bef86ec532c)

**Comment by markoaamunkajo** [comment]
QA passed
