### ISSUE TITLE
App doesn't keep last screen when brought back from minimised state

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1317]
Description:

Android app used to open the last screen when user brought it back from minimised state.
In the latest version the last screen opens but user is immediately teleported to dashboard.

https://github.com/user-attachments/assets/c7c0a0ae-6eda-4e4d-91f1-cd52eaf29637

Expected: keep user on last visited screen instead of moving him to dashboard when app is brought to foreground.

**Comment by laurijamsa** [comment]
Works for me correctly. I think this is because of enabled system developer settings in your phone settings?

**Comment by andreevdenis** [comment]
Same case as #1283 
@markoaamunkajo

**Comment by markoaamunkajo** [comment]
Looks like somehow developer options were hidden from me, brought them back and checked setting is inactivated and now it works. moving to done.
