### ISSUE TITLE
CSV export will crash app with Bluetooth sensors that have not been seen long time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1332]
Description:

User reported that when he tries to get CSV/XLXS-export from Bluetooth sensors that were not seen in a long time the app will first move user to dashboard, then if trying again app will crash.

Samsung S21, One UI 6.1, Android 14
2.11.16

**Comment by markoaamunkajo** [comment]
Reproduced,

This is caused by sensor name that contains "/".
When this is added to sensor name the app will experience this behavior.

**Comment by andreevdenis** [comment]
Chars that are not ok to have in filename will be replaced with _ when found in sensor name. 
These chars: '"', '*', '/', ':', '<', '>', '?', '\', '|'

**Comment by markoaamunkajo** [comment]
QA passed
