### ISSUE TITLE
Keyboard minus key is not working on sensor settings page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1341]
Description:

When setting the alert range manually on sensor settings page I cannot set the negative minus character from keyboard for some reason. I'm using UK keyboard on the phone and language is set to English.

https://github.com/user-attachments/assets/2ea80671-42da-43ba-9a85-d46e5ce3408a

**Comment by andreevdenis** [comment]
Why high priority? Works ok with Google keyboard. It can be reproduced with samsung keyboard. Unfortunatly I can't make samsung keyboard to show minus for decimal input. Probably it's a bug of Compose, maybe will be fixed in next versions.

**Comment by andreevdenis** [comment]
Decided to show normal keyboard for now

**Comment by markoaamunkajo** [comment]
QA passed
