### ISSUE TITLE
Scale data source icon according to font size

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1343]
Description:

Looking at Bluetooth icon shown at the dashboard, full card and history view it doesn't scale when big font is used. Let's scale data source icons accordingly.

![Image](https://github.com/user-attachments/assets/87cebc0f-9e0c-4619-a84d-d3917d8067df)

**Comment by andreevdenis** [comment]
I did the same for dasboard icons

**Comment by markoaamunkajo** [comment]
QA passed
