### ISSUE TITLE
Setting cloud sensor alert glitches in Android app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1344]
Description:

User tried to set alert to off for shared cloud sensor and it glitched and didn't set to off status.

**Comment by markoaamunkajo** [comment]
2.12.3, S22 Ultra,  I managed to reproduce the switch glitch and finally reproduced it. It happened only once when setting enabled alert to disabled wouldn't switch off but discussed this with Lauri and considered that this might happen to a lot of people so needs to be included in the next release.

Lauri got the saving to cloud text also glitching and repeating in this case.

https://github.com/user-attachments/assets/462edd4b-e5aa-4ef6-ad33-d90afc3ab6bf

**Comment by markoaamunkajo** [comment]
@andreevdenis sorry this needs to be included in this release since many people will likely see it

**Comment by DG12** [comment]
Consider user is unable to connect to cloud. Don't say "**error**".
Rather something like 
"Unable to update settings to cloud(?) at this time. Will update settings when internet connection is restored."

Even better idea, have app check if internet connection is good first!

**Comment by markoaamunkajo** [comment]
QA passed
