### ISSUE TITLE
1.2.11 Delete all tag cards - bg from first tag will remain on empty placeholder screen

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#145]
Description:Samsung S8, OS9

User has multiple tags in Ruuvi Station, few of them with background pictureHe deletes tag cards until he sees the empty placeholder screen with text"No Tags Added, press here to add tags."

Actual:Background from the first tag is placed in the background of placeholder screen

Expected:Show default placeholder screen background

**Comment by andreevdenis** [comment]
Also removing tag not always working

**Comment by markoaamunkajo** [comment]
QA passed
