### ISSUE TITLE
Show all datapoints makes phone slow down drastically

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#149]
Description

Reported by Henri, S9, app 1.1.4

Dashboard  view slow when scrollingThe whole app sluggish and getting worse when show all points enabled in graph settings

**Comment by markoaamunkajo** [comment]
I'll investigate this, have another user case

1.4.22, Android 11

User updated app to 1.4.22, app is not crashing but working very slowly and it's not starting sync


Issues appears after graph screen is opened
Changing "display all data in chart" doesn't help
User rebooted phone and when opening app again charts view is showing same dialog for sync "remove historical data"

About page is showing 2 tags
42775 / 2 = 21387,50 measurements per tag

https://user-images.githubusercontent.com/50437378/109015712-0434ee00-76e8-11eb-8be0-20774fc22002.mp4
![photo_2021-02-24 21 29 34](https://user-images.githubusercontent.com/50437378/109015764-0f881980-76e8-11eb-9edb-404401f5552c.jpeg)
![photo_2021-02-24 21 30 12](https://user-images.githubusercontent.com/50437378/109015775-10b94680-76e8-11eb-8b0a-78c4746f6c91.jpeg)


After removing RuuviTags and adding them again it's working.
But he had to click sync many times before it started syncing.

That was first time he saw this error and never appeared in previous version.

And has been using now 3.29.3 ~1 month

**Comment by markoaamunkajo** [comment]
Moving this to done lots of improvements were made.
