### ISSUE TITLE
Show in settings if alert is currently muted

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#159]
Description:

We are able to set alerts to timeout in notifications drawer, but we don't actually indicate that anywhere. Maybe a good idea would be to show which alerts are snoozed in tag settings?

For future consideration - in new UI

**Comment by markoaamunkajo** [comment]
Let's fix the styling a little now muted text looks like a title, suggested better idea in dm

**Comment by markoaamunkajo** [comment]
QA passed
