### ISSUE TITLE
Emoji as tag name shows weird "avatar" for tag in Dashboard view

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#162]

**Comment by andreevdenis** [comment]
Looks good to me now
![photo_2021-05-19_22-48-48](https://user-images.githubusercontent.com/24788772/118875243-7a667c80-b8f4-11eb-9ee7-fd1d3a9b1dac.jpg)

**Comment by andreevdenis** [comment]
Test in 1.5.19

**Comment by DG12** [comment]
Are there ramifications for upload filename?

**Comment by andreevdenis** [comment]
Filenames are fine with emojis

**Comment by markoaamunkajo** [comment]
Looks like emoji as a name doesn't get synchronized correctly with network. If user syncs network it will show Mac as sensor name and emoji is gone.

**Comment by markoaamunkajo** [comment]
Agh will make another card. Moving this one to done.

**Comment by laurijamsa** [comment]
Seems that this one is still open for some reason. Closing.
