### ISSUE TITLE
Obfuscate code

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#167]

**Comment by DG12** [comment]
What's this mean?

**Comment by andreevdenis** [comment]
As wikipedia says it's an act of creating source or machine code that is difficult for humans to understand. Mostly used to protect source code but it's no our case since we're open source. It can also give benifits as minimizing apk size.

It's definatly not a high priority and issue was created mostly to get rid of warning from Google when we upload new version to Play Store.
