### ISSUE TITLE
Ruuvi Network - Share/Unshare implementation

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#169]

**Comment by DG12** [comment]
Can you please describe what this is?
I see the claim/share buttons. What do they do?

**Comment by andreevdenis** [comment]
By pushing 'claim' you're saying to Ruuvi Network that this sensor is yours and now it's linked with your account. If you sign in on another device you'll automatically get this sensor to app without adding it by hand. You can share your sensors to friends or family and if you have gateway - they will get measurements from shrared sensors via network.

**Comment by DG12** [comment]
I have ruuuvi gateway up and running(usually), several ruuvi's in range.
How do I see gateway forwarded data?
I just restarted it, I 
(7440) tcpip_adapter: sta ip: 192.168.1.63, mask: 255.255.255.0, gw: 192.168.1.1
I (12020) TIME: [tiT] Time has been synchronized: 2021-02-03 01:28:32.302
I (12960) ADV_POST_TASK: Advertisements in table:

**Comment by DG12** [comment]
Free heap varies 155416,,155480...

**Comment by andreevdenis** [comment]
I don't have gateway yet and don't know how to configure it. But from app perspective you should:  
1) sign in
2) claim sensor
3) sync data from network (refresh button in left bottom corner of navigation drawer)

If you close to your sensor it will be hard to understand if you get data directly or from network.

**Comment by markoaamunkajo** [comment]
QA passed
