### ISSUE TITLE
Language unification Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#184]
Description:

Change terminology and language in Android app to match iOS Ruuvi Station

Terminology related notes are in Confluence:
https://ruuvi.atlassian.net/l/c/C2f4Psu9

**Comment by andreevdenis** [comment]
Alerts: Connection and Signal strength work differently in iOS/Android

**Comment by markoaamunkajo** [comment]
In Chart Settings explainer text under Display all data in chart setting
"Enabling it may cause slow chart work"

Should be
"Enabling it may cause charts to update slowly"

**Comment by markoaamunkajo** [comment]
QA passed
