### ISSUE TITLE
Android Tag Settings - More info

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#186]
Description:

Unify Tag Settings / more info with iOS

iOS More Info includes:

More info popup (depending on fw version)
UUID
MAC Address
Data Format
Data Received Via
Battery Voltage
Acceleration X
Acceleration Y
Acceleration Z
Tx Power
Movement Counter
Measurement Seq Number

**Comment by DG12** [comment]
I'd like to suggest listing MAC, data format and Tx Power last since they are (more or less) static and data format is only useful for development.
I'd also suggest omitting UUID since it is rather meaningless to the users and is not even consistant.

**Comment by andreevdenis** [comment]
Didn't add UUID since it iOS specific

**Comment by markoaamunkajo** [comment]
Looks like values are not updating live on sensor settings screen but they are updated every time user accesses this screen. I think this is fine.

QA passed

**Comment by laurijamsa** [comment]
Actually, they should update. Reopening this.

**Comment by markoaamunkajo** [comment]
Now counters updating. Moving to done
