### ISSUE TITLE
Implement tag default naming in Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#188]
Description:

Unify tag default naming with iOS version

Add a New Sensor
Scanned sensors should be shown with name _Ruuvi xxxx_ instead of MAC address

**Comment by andreevdenis** [comment]
Implemented in 1.5.19

**Comment by andreevdenis** [comment]
If sensor had empty name it will be renamed accordingly with new rules. This may not work for Network sensors, but since we have very few of Network users - I don't want to spend time on this.

**Comment by markoaamunkajo** [comment]
QA passed
