### ISSUE TITLE
Video tutorials link lead to app crash (in calibrate tag)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#190]
True for OnePlus, Huawei and redmi
![image](https://user-images.githubusercontent.com/24788772/100901163-9a37ee80-34d4-11eb-94c5-7dd45f84046c.png)

**Comment by andreevdenis** [comment]
@markoaamunkajo wait for 1.4.4 to check it

**Comment by markoaamunkajo** [comment]
QA passed
