### ISSUE TITLE
Gatt download on old devices (like samsung galaxy s5) lead to fail and history is lost

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#204]

**Comment by ojousima** [comment]
As of Ruuvi FW 3.29.3 the RuuviTag kicks connection after 5 minutes, this protects against losing history. However, the app doesn't try to sync starting from latest received datapoints, but rather from last sync attempt. 

If tag has data from Monday to Sunday and user tries to sync on Sunday, tag might give out only Monday and Tuesday. On second sync attempt app tries to get data starting from Sunday, leaving data from Wednesday to Saturday not fetched.

**Comment by andreevdenis** [comment]
Looks like we can't do much on Android side. It depends on connection event length extension property of FW. Sync is fast if we use 3.28.13 even on samsung galaxy s5 it take seconds

![image](https://user-images.githubusercontent.com/24788772/106382908-b15f6380-63d3-11eb-9557-2796004d3f12.png)

**Comment by markoaamunkajo** [comment]
QA passed, not losing history for me on S5 when disconnected message shown.
