### ISSUE TITLE
Remove mentions of "tags" in app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#213]
Description:

We want to start using word "sensor" in all of these locations, since "tag" is technically a product name.
---

Splash screen app intro: "Access data for each linked RuuviTag in real time and explore history graphs" -> "Access data for each linked sensor in real time and explore history charts"

Splash screen app intro: "Press SCAN to find and add nearby RuuviTags to your Ruuvi Station" -> "Press SCAN to find and add nearby sensors to your Ruuvi Station"

No sensors placeholder screen: "No tags added, press here to add tags" -> "No sensors added, press here to add sensors"

Tag Settings -> Sensor Settings
Tag Name -> Sensor Name

Bluetooth activation request popup: "The app uses Bluetooth LE to read data from RuuviTag sensors" -> "The app uses Bluetooth LE to read data from Ruuvi Sensors"

Gateway Settings: "When you add a URL here, the app will execute an HTTP POST with the linked tags when it does background scanning." -> "When you add a URL here, the app will execute an HTTP POST with the linked sensors when it does background scanning."

About/Help: Seen tags, Added tags -> Seen sensors, Added sensors

Also adopt this practise to Play Store updates if we give info what changes are made

**Comment by DG12** [comment]
Is the "word" RuuviTag acceptable?

**Comment by markoaamunkajo** [comment]
@DG12 we will use RuuviTag since it's product name. QA passed.
