### ISSUE TITLE
1.4.11 HTTP Post contains mention of "tags"

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#218]
Description:

User sets up App Gateway URL to send sensor data to Gateway. Looks like this data still uses word "tags" at the beginning of the message.

Is it possible to change this to "sensors"? (Looks like Gateway documentation requires rewriting as well).

**Comment by markoaamunkajo** [comment]
Tested briefly in hookb.in

![Screenshot 2020-12-18 at 9 58 26](https://user-images.githubusercontent.com/50437378/102569203-997b9b00-4117-11eb-8978-3f470ca89eae.png)

**Comment by andreevdenis** [comment]
yep, but changing this will broke someones logic on server
