### ISSUE TITLE
Update Android UI/UX documentation

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#219]
Update document https://ruuvi.atlassian.net/wiki/spaces/RS/pages/56098817/Ruuvi+Station+Android+UI+UX+test+documentation

**Comment by DG12** [comment]
Cab you please publish the document elsewhere or invite dgermanatl@Real-World-Systems.com to ruuvi.atlassian.net. Thank you

**Comment by markoaamunkajo** [comment]
@laurijamsa please invite @DG12 for now let's think about documentation location later.

**Comment by markoaamunkajo** [comment]
Document updated.

**Comment by laurijamsa** [comment]
> @laurijamsa please invite @DG12 for now let's think about documentation location later.

Unfortunately, that is a private team and outside collaborators cannot be added. Let's move the document instead.
