### ISSUE TITLE
Ruuvi Network: Old data is not refetched from Network after clearing graphs 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#220]
Tested on app version 1.5.0.

Expected behavior: After clearing graphs the history data can be refetched from network. 

Observed behavior: After clearing graphs only data after last network fetch is retrieved.

Steps to replicate:
1) Fetch history data from Network
2) Clear graphs
3) Fetch history data from Network
4) Note that there's only data from after the time of step 1.

**Comment by markoaamunkajo** [comment]
QA passed
