### ISSUE TITLE
Localisation missing from app OS settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#226]
Description:

User goes to Settings -> Apps and opens Ruuvi Station app settings
Under "Categories" there are categories for:
RuuviStation foreground scanner
Alert notifications

If user changes OS language to Finnish these are not translated.

Expected:

Remove:  "RuuviStation foreground scanner" (looks like it's a copy of Alert Notifications!!)

ENGLISH: Alert Notifications
FINNISH: Ilmoitukset

![Screenshot_20210105-112436_Settings](https://user-images.githubusercontent.com/50437378/103606965-61af8880-4f4a-11eb-9283-fa78bcdb03ab.jpg)
![Screenshot_20210105-112603_Settings](https://user-images.githubusercontent.com/50437378/103606971-64aa7900-4f4a-11eb-819e-44c33ca10afe.jpg)

**Comment by andreevdenis** [comment]
Not sure if it's a good idea to translate notification channel names. Let's return to this a little bit later

**Comment by andreevdenis** [comment]
No need to do it
