### ISSUE TITLE
A mechanism for sync to ignore data prior to mm/dd/yy hh:mm is needed  - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#228]
There needs to be a means to tell station to ignore data prior to a specified date & time.
For Example:
Take the ruuvi to the swamp, on Monday and leave it there.
Return on Wednesday and sync with station leave ruuvi there. Get home export data to laptop.
Return on Friday sync gets data since Monday!

Desired action is to only get data not previously retrieved.

Continuing... retrieve Ruuvi on Friday.
Saturday take Ruuvi to airport.
Sunday sync will retrieve all data from swamp the previous Monday, the data while Ruuvi was not deployed (i.e. in the office) as well as desired data since Saturday.

As second user scenario described  in https://github.com/ruuvi/ruuvi.firmware.c/issues/190
Requires no mechanism to clear log should be provided

**Comment by ojousima** [comment]
This is already implemented, although in the form "only data since last sync is requested."

**Comment by andreevdenis** [comment]
Closing. Implemented - Station remembers last sync datetime
