### ISSUE TITLE
Cannot submit sign in code - 1.5.0 - defect - low priority

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#234]
Received TOKEN=BZUM

And accessToken for DGermang@Real-World-Systems.com
At SIgnIn:;(ENTER CODE MANUALLY);  Sign in code (note space)_BZUM_______
Tap SUBMIT no response. 
Leaving Sign in code blank and tap SUBMIT no response.

Must be me?

{
    "result": "success",
    "data": {
        "email": "DGermang@Real-World-Systems.com",
        "accessToken": "753231/GcPdJ0UUfPoZp06qjcXD8uvouM9bHb95DtadehiT9X2XSurcaUVdjVGZMuCKJsUj",
        "newUser": true
    }
}

**Comment by andreevdenis** [comment]
Please try 1.5.2. Sign in should be better there

**Comment by DG12** [comment]
Fixed in 1.5.2
