### ISSUE TITLE
Adding a new sensor jumps around a little too fast - 1.5.0 - enhancement -minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#235]
It's a nice idea to sort the Ruuvi by RSSI but sampling a little too fast makes them jump around and appear and disappear. Just saying.

**Comment by andreevdenis** [comment]
Yeah, agree, it was annoying me too

**Comment by DG12** [comment]
in fact better don.t clear them out on each pass. Once a RuuviTag is seen, leave in the same place even if not seen on this pass.

**Comment by andreevdenis** [comment]
This will be updated in next version (1.5.x):
- Show sensor for 60 seconds since last broadcast
- Update 'Add a New Sensor' screen not so frequently to have less jumping sensors 
- Sensors without recent broadcast (older than 10 seconds) will be shown with gray

**Comment by markoaamunkajo** [comment]
QA passed
