### ISSUE TITLE
"Ruuvi station keeps stopping" means crashing ? -1.5.0 - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#236]
I went to the App Settings/gateway settings and put in the IP address of the gateway , 192.162.1.63 , response "nope it did not work "

OOPS It says App act as gateway (read the manual) :-)

Tried to re-enter but now won't stay running.
Removed but playstore still thinks its there!
Shutdown/boot GAWK! its still there! I don't see it but when I got to playstore it offers. "open".
Ahh. Playstore offers uninstall.
 
OK All better now

**Comment by andreevdenis** [comment]
Did you try 1.5.2? Or all good now? Can I close this?

**Comment by andreevdenis** [comment]
Not actual version
