### ISSUE TITLE
More datapoints than was requested by settings

### ISSUE THREAD

**Issue by attemarkula** [ruuvi/com.ruuvi.station#237]
use case: Ruuvi station remains on background, phone left on charger for the night.
In the late morning I check data, scrolling graph feels sluggish (all points visible, count limited usually by sampling interval) and when zoomed in, shows more than normal 20 min interval data points.
My expectation was that 20 min period would not result in more than 1 scan and 1 data point.
Same thing happens during day usage too, but not constantly.

- I expect that charging disables power saving/battery optimization.
- exported log file show ~20 samples per minute.
- Background scan interval set to 20 minutes, 0 seconds
- I have tried to restart app by force and rebooted phone, no change.
- same oversampling seem to happend during day.

I'm I just misunderstanding how continuous background scanning should work, or is there something weird happening?

Device: QUALCOMM YotaDevices YOTA 3+
Android version: 8.1.0
App: Ruuvi Station 1.4.10 

[F9_93_71_95_04_13_210119-0529.csv.txt](https://github.com/ruuvi/com.ruuvi.station/files/5836923/F9_93_71_95_04_13_210119-0529.csv.txt)

![Screenshot_20210119-132014](https://user-images.githubusercontent.com/66369715/105057028-7a0cc080-5a7d-11eb-97e9-9f7c1b8adcd1.png)
![Screenshot_20210119-172550](https://user-images.githubusercontent.com/66369715/105057032-7aa55700-5a7d-11eb-8727-3b170db399f3.png)

**Comment by andreevdenis** [comment]
It was working correctly until 7:36:57. Did you check app at this moment? Btw data logging interval is only applied to background work. If app is in foreground - it will save all the data it recieves. So short intervals of high density data points are ok if you were using app at these intervals.

**Comment by attemarkula** [comment]
Well, I woke around 12:27, at least according to my tracker that has been pretty accurate.
There were no active alarms or anything like that before it. So if phone was activated, "it did it itself". (But it should have been stopped by PIN request. idk.)

So this is normal behavior then. I guess limiter would be nice to have one day, if there's not one now, but I do understand that there's a point of view why it might not be required from client side. Maybe from sensor side. 
Well, it's more want and less of need so, case closed I assume.

**Comment by andreevdenis** [comment]
No, difinetly not a normal behaviour for background scan. Will try to investigate and find solution for this.

**Comment by markoaamunkajo** [comment]
This issue has been replicated, it has something to do with too many datapoints collected with background scan interval. Discussed with Denis, moving back.

**Comment by markoaamunkajo** [comment]
Appears to be fixed in 1.4.26

**Comment by attemarkula** [comment]
looks good, thanks.
