### ISSUE TITLE
Add progress bar to GATT sync

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#240]
Description:

Now when we are adding ability to sync large amounts of data to charts:

Hide dialog for gatt sync and show it in place of buttons at the bottom of charts page during sync (same as iOS)
Cancel sync button during sync
When sync completed buttons reappear

**Comment by markoaamunkajo** [comment]
How it's done on iOS:
https://user-images.githubusercontent.com/50437378/110471887-45c59000-810f-11eb-9b47-a22e9f5f8569.mp4

**Comment by DG12** [comment]
This needs to be designed/tested with a RuuviTag at the edge of the transmission range, in-range and as it moves out of range.

**Comment by andreevdenis** [comment]
Can be tested in 1.5.8

**Comment by markoaamunkajo** [comment]
If user disabled Bluetooth during synch it doesn't timeout. Please add timeout if Bluetooth connection disrupted.

**Comment by andreevdenis** [comment]
Can you check it @io53 ?

**Comment by io53** [comment]
Sure, will do.

**Comment by io53** [comment]
Please try again @markoaamunkajo after a build is released with this.
"works on my phone"- stamp

**Comment by andreevdenis** [comment]
merging this to 1.5.12

**Comment by markoaamunkajo** [comment]
QA passed
