### ISSUE TITLE
Improve timeline for graphs (dates and time)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#241]

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
Reopening this issue. I can see double horizontal lines, vertical lines are not synced with hours but they are random, on landscape mode there are too many rows and dates are not following country guidelines. See: https://en.wikipedia.org/wiki/Date_format_by_country

For example, we cannot use 04/02 for the both U.S. and European users... And also, the slash character is not used in Finland to divide days and months. And the redundant zeros should be dropped, too. Meaning, "04/02" should be "4.2.". All the se should be fixed on iOS also if they are currently not working well.

Let's try to find some elegant solution to handle these issues...

![image](https://user-images.githubusercontent.com/1311912/106969542-9ac35e80-677d-11eb-8db1-6482c4685258.png)

![image](https://user-images.githubusercontent.com/1311912/106970152-e0345b80-677e-11eb-8cf1-974e030672dd.png)

**Comment by DG12** [comment]
US users (at least me) would like leading 0 for the day example 4/02 (but maybe its just me?) Nope, the supreme authority (wife) likes 4/02 also :-)

**Comment by andreevdenis** [comment]
@DG12 sorry to disapoint your wife, but format for US is m/d/yyyy so no extra zeros

**Comment by frspp** [comment]
Suggestion/Feature request:

On all graphs show full hours and quarters. If zoomed every show five minutes. 
13:00 13:15 13:30 13:45

insted of messy
13:03 13:23 13:34 13:48

Improves readability and usability HUGELY!

**Comment by jmullo** [comment]
Yeah, the way it currently selects the X-axis tick line positions is pretty useless.

Here it manages to skip one whole day:

![ruuvistation](https://user-images.githubusercontent.com/7224076/143788679-5652258e-2bc4-4ce3-b084-b53448ca75ed.jpg)

**Comment by andreevdenis** [comment]
1.8.0

**Comment by andreevdenis** [comment]
1.8.1

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by andreevdenis** [comment]
@frspp @jmullo Check latest beta version of Ruuvi Station Android 1.8.2 for timeline improvements.
