### ISSUE TITLE
After clicking SUBMIT on the Sign In view after entering email address, nothing happens

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#242]
Totally nothing happens no matter how many times I press the button.

There is also no user feedback on the button press and no loading icon that would play until successful action (and probably no timeout?).

Build 1.5.2 on Samsung Galaxy Note S20 Ultra (Android 11).

**Comment by laurijamsa** [comment]
After uninstall & install this works again. I previously installed 1.5.2 APK on top of 1.5.0.

**Comment by andreevdenis** [comment]
Can't reproduce. Tried update from 1.5.0 to 1.5.2 -  sign in worked as always.
