### ISSUE TITLE
Add synchronizing info during network sync

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#245]
Description:

Please add to sensor card bottom left corner text "Synchronizing" with animated three dots
This will be shown on network sensor cards when sync is in progress.

**Comment by DG12** [comment]
PLEASE do not use animated three dots which indicate something is happening when in fact no data may be transferring! 
Rather "manually" change image as syncing progresses.

**Comment by markoaamunkajo** [comment]
QA passed
