### ISSUE TITLE
Add "Beta" to Ruuvi Network signin

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#246]
Description:

Please add "Beta" to Ruuvi Network Signin menu item, so people know that network product is an early beta.

See beta in screenshot

**Comment by markoaamunkajo** [comment]
<img width="93" alt="Screenshot 2021-01-30 at 16 18 28" src="https://user-images.githubusercontent.com/50437378/106352571-de017580-6316-11eb-9c3d-66ccc8c07267.png">

**Comment by andreevdenis** [comment]
Couldn't do it exactly like in design with small blood. It's possible but will take more time

**Comment by markoaamunkajo** [comment]
Call it a "beta version of beta" 🤣

**Comment by DG12** [comment]
> Call it a "beta version of beta" 🤣

How 'bout a better version of the  Beta 🤣🤣
