### ISSUE TITLE
Translation issue when setting alerts

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#248]
Some extra words here. Double check also if the issue is only with Finnish & Android or also with iOS and other languages.

![image](https://user-images.githubusercontent.com/1311912/106403039-1ca24780-645f-11eb-8804-cc477c91c4df.png)

**Comment by andreevdenis** [comment]
iOS has different strings for temp, humidity and pressure for Suomi, but English, Svenska and Russian versions are universal:
Alert when less than {value} or more than {value}

**Comment by markoaamunkajo** [comment]
QA passed
