### ISSUE TITLE
No sleep for alert if notification dismissed from notification drawer

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#251]
Description:

Remove ability to make alerts sleep for 1 hour when notification dismissed from notification drawer.
Keep ability to disable alert.

Update: decided to add mute button to notification, this will make clear for user what he's doing

**Comment by laurijamsa** [comment]
Got a customer feedback related to this:

"I think the alerts one can set on - for example - humidity being outside the chosen range are getting sent again and again, sometimes even like every few seconds (while the measured value is outside the range).

At least my watch (Samsung Galaxy Watch Active2 or something) keeps repeating the alert, and it's very annoying. Solved the annoyance by blocking Ruuvi Station notifications from my watch, but figured this is still an issue you ought to know about."
                      
Device: samsung SM-G986B
Android version: 11
App: Ruuvi Station 1.4.18

**Comment by markoaamunkajo** [comment]
QA passed
