### ISSUE TITLE
Movement counter  and MessageSeqNum should be  displayed - 1.5.2 - deficiency

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#255]
Format rawV2, aka 05, includes:
1) uint8 at offset 15 from the 05, just after the batteryVoltage&TX dBm known as movementCounter range 0..254. It should be displayed.

2) uint16 at offset 16 from 05, known as MeasureSequence Number
it should be displayed.

In my opinion acceleration X,Y,Z could be on one line .

**Comment by andreevdenis** [comment]
Already working on this. Duplicates #186
