### ISSUE TITLE
Temperature rounding issue in csv export

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#259]
Description:

User has set temperature units to Kelvin
Exported csv file shows a huge number of decimals in temperature

Expected:
Show 2 decimals

**Comment by markoaamunkajo** [comment]
Decimals for temperature now correct. Acceleration is good to show 3 decimals but what about Voltage?

**Comment by DG12** [comment]
FYI Regarding humidity : 4 digits (ie. ii.ff ) for humidity is well beyond the accuracy of most sensors in this price range especially the BME208.

**Comment by andreevdenis** [comment]
We export voltage same way as we show it Sensor settings. I think everything is fine here

**Comment by markoaamunkajo** [comment]
QA passed
