### ISSUE TITLE
Save background image to network

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#265]

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by andreevdenis** [comment]
Please recheck it in 1.5.5

**Comment by markoaamunkajo** [comment]
1.5.5. user updated background picture to sensor card, synchronised to network, then uninstalled app and reinstalled app, signed back into network

Actual: background picture was updated but sensor data is now not downloaded.

![Screenshot_20210323-143347_Ruuvi Station](https://user-images.githubusercontent.com/50437378/112110478-84fee100-8be5-11eb-813b-414be0ae471d.jpg)

**Comment by andreevdenis** [comment]
Can't reproduce this. Do you have measurement data for this sensor in Network? You can claim sensor in app and set image to it but for history it need to be in range of gateway. This looks like this sensor have no history in Network.

**Comment by markoaamunkajo** [comment]
QA passed
