### ISSUE TITLE
1.4.21 Air Pressure alert range can be 300-300 or 1100-1100

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#267]
Description:

Air pressure alert range can be set to for example 300-300

Expected:
It should be 300-301 1099-1100
Reference from other alert types

**Comment by andreevdenis** [comment]
Under the hood it work with Pa, and if you see range as 300-300 hPa in reality it's something like 30001-30002Pa and after conversion to hPa we see 300-300

**Comment by andreevdenis** [comment]
I can change this by setting minimal gap for as 100 Pa

**Comment by andreevdenis** [comment]
What do you think @markoaamunkajo @laurijamsa ?

**Comment by markoaamunkajo** [comment]
In my opinion gap should be always available. Good point though.

**Comment by markoaamunkajo** [comment]
Ok let's keep it as reason is library. QA passed.
