### ISSUE TITLE
1.4.21 Switching language issue Sensor settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#268]
Description:
S8, OS9

User sets phone language to Finnish and checks sensor settings, then changes language back to English

Actual:
Half of the Sensor settings screen alert titles are still in Finnish
It can be fixed by exiting settings screen and coming back but should rather update correct titles when changing language

https://user-images.githubusercontent.com/50437378/107373964-ac0fc080-6b19-11eb-94c0-446abec3d959.mp4

**Comment by andreevdenis** [comment]
Actually you can see these alerts doubled: Lampotila and Temperature at the same time.

**Comment by markoaamunkajo** [comment]
QA passed
