### ISSUE TITLE
Location permission is not forced to be enabled on all phones

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#272]
We receive a lot of feedback about not being able to find nearby sensors and 90% time the issue has been that no location permission granted and Android cannot see anything because of that.

On my Android 11 phone I do get the "Enable Bluetooth Scanning" note if location permission is denied but apparently on all phones users are not seeing this note.

There is also a bug related to this on my phone. Reproduce:

1) Disable location permission
2) Try to add a sensor
3) The "Enable Bluetooth Scanning" dialog pops up
4) When pressing OK, the dialog just blinks and appears again and the app gets unresponsive and has to be killed. 

EDIT: A user commented that on his Huawei phone he sees no dialogs about this.

"Device: HUAWEI VOG-L29
Android version: 10
App: Ruuvi Station 1.4.18"

**Comment by andreevdenis** [comment]
We have permission requests on 3 screens: main sensors screen, dashboard and add sensors. I've unified user experience for all of these. Permission requests work good on all of my phones.

**Comment by andreevdenis** [comment]
Also request to enable Location added if it's disabled

**Comment by markoaamunkajo** [comment]
QA passed
