### ISSUE TITLE
Scan RuuviTag with NFC in Ruuvi Station

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#273]
Description:

Scanning a RuuviTag with NFC when user has Ruuvi Station at foreground will trigger two actions:

- If RuuviTag has not been added to Ruuvi Station scanning with NFC will add sensor to Ruuvi Station
- If RuuviTag has been added to Ruuvi Station scanning with NFC will show it's firmware version and shows update instructions

Popup:

Firmware version: 2.5.9
Update firmware: lab.ruuvi.com/dfu (link will open in browser)

**Comment by ojousima** [comment]
Let's continue the discussion here: https://feedback.ruuvi.com/posts/26/nfc-feature-for-ruuvi-station
