### ISSUE TITLE
Sensor offset calibration

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#274]
Description:

Remove old Calibrate Hygrometer button in Sensor Settings.

Add new Offset Calibration feature under new menu item Offset Calibration in Sensor Settings under Alerts. This feature will enable user to set custom offset for:

Temperature
Relative Air Humidity
Air Pressure (hPa)

1. Offset will be converted accordingly if other global unit is selected in App Settings ie Celsius -> Kelvin
2. Temperature, Relative Air Humidity, Air Pressure hPa will be only supported for offset

Every Offset Calibration page has:

1. Description text (to be added later)
2. Original measured value (updated live)
3. Target value (default empty with description text "Add", not updated live), Offset in parenthesis (updated live)

CSV export will show calibrated values (as is currently with humidity).

<img width="315" alt="Screenshot 2021-02-20 at 13 55 56" src="https://user-images.githubusercontent.com/50437378/108586815-635ecf80-7383-11eb-95f9-dd17f8824b4d.png">

<img width="308" alt="Screenshot 2021-02-20 at 13 42 45" src="https://user-images.githubusercontent.com/50437378/108586801-4de9a580-7383-11eb-8cf7-3070d6279a6b.png">

**Comment by DG12** [comment]
Rather than including the text describing the method of calibration, a link to a web page should be used.
That would allow easy localization and permit changing the text should it be necessary. As the user rarely performs this activity the need to have a network connection is not an issue.

**Comment by DG12** [comment]
Regarding humidity calibration and offset: The deviation of the reading to the offset is not linear. It must at least be in 2 ranges each with it's own offset!

**Comment by markoaamunkajo** [comment]
Changing device language resets calibration 1.5.12

**Comment by markoaamunkajo** [comment]
Sorry my bad, it was another sensor settings shown!
