### ISSUE TITLE
App gateway feature occasionally sends data too often

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#277]
This is a user feedback. I have not tried to reproduce the issue. Expectation is that data should be posted in every 5 minutes if background scanning setting is set to 5 minutes.

"We’re using a Nokia smartphone to pickup the Ruuvi measurements and transmit those using the gateway settings. Continuous background scanning is set to 5 minutes. Posting the data works fine. But there’s a problem after the phone reboots. Then the app starts posting the data almost continuously instead of every 5 minutes. It seems that after I go into the settings screen of the app (Ruuvi Station) and move around a bit, it starts logging again every 5 minutes. I don’t have this issue on a Samsung tablet though. I’ve found a forum issue that’s about the same problem: https://f.ruuvi.com/t/ruuvi-station-calling-gateway-constantly/4604 "

**Comment by andreevdenis** [comment]
Most likely connected to #237

**Comment by markoaamunkajo** [comment]
I have 1.4.25 single tag, no app power optimizations, switched bg scanning to 5 minutes, minimized app, rebooted phone and left it to bg scanning while went out to eat. Returned back to view graphs I see bunch of datapoints collected at 5 min points. 

[Tigga_210224-0848.csv.zip](https://github.com/ruuvi/com.ruuvi.station/files/6036400/Tigga_210224-0848.csv.zip)

**Comment by markoaamunkajo** [comment]
Fixed in 1.4.26 but test gateway blocks me when testing GW side, so have to rely on user feedback
