### ISSUE TITLE
CSV export: in file name hh is in 12 hour

### ISSUE THREAD

**Issue by frspp** [ruuvi/com.ruuvi.station#281]
Hi!

I got confused with csv exports because I took them at "2242" but file name read "1042". Maybe change to 24h?

**Comment by DG12** [comment]
I can confirm Version 1.5.2 has this problem

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by andreevdenis** [comment]
No way! Wait for 1.5.5 to test

**Comment by markoaamunkajo** [comment]
So this is default filename when exporting not inside logs?

**Comment by andreevdenis** [comment]
Yes, it's about csv filename

**Comment by markoaamunkajo** [comment]
Filename now has 24 hours. QA passed.
