### ISSUE TITLE
CSV export contains only time span shown in graph

### ISSUE THREAD

**Issue by frspp** [ruuvi/com.ruuvi.station#284]
Ruuvi Tag with firmware 3.xx is said to log 12 days to internal memory. How to get this log out of the device? 

Current csv export is 24 hours so I quess csv export contains only data shown in graph? Would make sense to export whole history in csv and still show chosen time span in graph.

**Comment by andreevdenis** [comment]
Currently you can sync data and get last 72 hours history from sensor memory. You may need to change chart settings to see it. But for csv we only export last 24 hours and it's a bug. I think it should be same as chart history period or all stored data. Also we'll extend currently stored sensor data from 72 hours to 10 days.

**Comment by andreevdenis** [comment]
Now will export all stored history - up to 10 days

**Comment by frspp** [comment]
Cool! Thanks! When new beta version will be available and includes this?

**Comment by andreevdenis** [comment]
It will be in beta within a week or two. This fix comes with many other changes and we want to check it carefully

**Comment by andreevdenis** [comment]
If it's urgent, I can provide link to test build apk.

**Comment by markoaamunkajo** [comment]
QA passed
