### ISSUE TITLE
Slower broadcast rate tags keep popping in and out from add tag view

### ISSUE THREAD

**Issue by Scrin** [ruuvi/com.ruuvi.station#285]
When going to Menu -> Add a New Sensor, tags with a relatively infrequent broadcast interval (and/or poor signal with a lot lost packets) keep popping in and out. This becomes extra problematic when there is a longer list of tags and you want to find a specific tag from the list, and the list keeps changing every second as tags pop in and out of the list.

Judging by the duration between appearing and disappearing, I believe a tag is removed from the list after 5 seconds of not receiving a broadcast from it, perhaps this could be increased a little?

I don't see any practical reason why a tag should disappear within 5 seconds from the list, as some tags either have a longer broadcast interval or simply located in a place where a significant portion of the broadcasts are simply lost. (Which is not an issue in a typical scenario where even just a few broadcasts per minute is sufficient anyway)

Suggestion: Increase the duration before a tag is removed from the new tag list from 5(?) seconds to 30-60 seconds, with optionally a "fade out", ie. after 5-10 seconds the tag text would start to fade away indicating a tag not recently heard, but still on the list and be clickable

**Comment by andreevdenis** [comment]
I feel your pain, this behaviour annoys me too. We'll do something with it soon. Also we have a feature to add tag by NFC-scanning in our roadmap.

**Comment by DG12** [comment]
See also issue #235

**Comment by DG12** [comment]
Add by NFC requires proximity to RuuviTag nice ? but ...

**Comment by andreevdenis** [comment]
This will be updated in next version (1.5.x):
- Show sensor for 60 seconds since last broadcast
- Update 'Add a New Sensor' screen not so frequently to have less jumping sensors 
- Sensors without recent broadcast (older than 10 seconds) will be shown with gray

**Comment by markoaamunkajo** [comment]
Solved with same solution as #235
