### ISSUE TITLE
Alerting notification about the continuous background scanning gets occasionally killed

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#289]
Yesterday I noticed that even the notification was gone, the app had continued background scanning because history logs didn't have any gaps without collected data points.

I don't know exactly how much earlier the notification got vanished before I opened the app, so this issue need more testing before can say anything for sure. This has happened before but at those times I think the background scanning got paused too.

![image](https://user-images.githubusercontent.com/1311912/110190891-294bfe00-7e58-11eb-8448-3d9facf728a9.png)

**Comment by andreevdenis** [comment]
See #371
