### ISSUE TITLE
Redundant timestamp on the background scanning notification bar

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#290]
I see no use for the timestamp (23:10 in this case) that tells when the background scanning has been started. Seems that other alerting notifications my phone has don't have such timestamps visible.

![image](https://user-images.githubusercontent.com/1311912/110191039-2e5d7d00-7e59-11eb-9b7c-83c18149f4c4.png)

**Comment by andreevdenis** [comment]
From 1.5.27

**Comment by markoaamunkajo** [comment]
QA passed
