### ISSUE TITLE
Descriptions don't fit in the buttons

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#291]
The buttons should automatically get wider if longer texts on them.

![image](https://user-images.githubusercontent.com/1311912/110192805-0246f980-7e63-11eb-939a-cdc415335e9e.png)

**Comment by markoaamunkajo** [comment]
I cannot replicate this because my screen is probably not so slim as Lauris phone. Will pass QA on this version.
