### ISSUE TITLE
Software does not work on Android 7.1.1

### ISSUE THREAD

**Issue by jusju** [ruuvi/com.ruuvi.station#30]
Cannot pair The Bluetooth device. Same tags work with Android 6.0.1. I use a RuuvitagScanner.apk version 0.7.4-beta.

**Comment by jusju** [comment]
Did anybody notice my message?

**Comment by io53** [comment]
Yes. The device was a OnePlus 3T, right?
I've been using it on android 7.1.1 just fine on multiple devices.
I can try to compile a new apk for you to test that does not use androids 'new' BluetoothLeScanner. But  it will be in the evening/tomorrow. Are you available on slack?

**Comment by jusju** [comment]
I am at slack. Jukka Juslin is slack name. Others reported that also does not work on 7.1.1

**Comment by laurijamsa** [comment]
Closing. If the latest builds have issues, open a new one.
