### ISSUE TITLE
1.5.4 Add network sensors after the rightmost card

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#303]
Description:

User has 1 physical local sensor in Ruuvi Station
User signs into network, there is single network sensor named "Anturi" assigned in his account

Actual:
Network sensor is added to leftmost location in row before any other sensor cards

Expected:
Add new sensors to rightmost location

**Comment by andreevdenis** [comment]
1.5.5

**Comment by markoaamunkajo** [comment]
User had one local sensor in Ruuvi Station called "Hehhe", and one sensor in network called "Anturi"
Signed into network, and data was synced

Actual: Card "Hehhe" disappeared and was replaced with "Anturi" background picture and name, but data looks same as local sensor "Hehhe"

**Comment by markoaamunkajo** [comment]
Ok issue found, they are same tag MAC is matching.
Requested fix is working so QA passed.
