### ISSUE TITLE
FR: alert log

### ISSUE THREAD

**Issue by frspp** [ruuvi/com.ruuvi.station#305]
Hi! 

Feature request: Would be nice to have alert log. 

In log show: device name, time, alert details. One row per alert to have space for many alert.

Shelly app has good log:
https://homekitnews.com/wp-content/uploads/2020/03/shelly-ht-event-log.jpg

**Comment by laurijamsa** [comment]
Thank you for the feature suggestion. We have future plans similar to this. But as this isn't an Android related issue and implementing this would need cloud support, I'm closing this ticket as a redundant one. But don't worry, the idea and suggestion is registered and will not be forgotten. Thanks!
