### ISSUE TITLE
1.5.5 app is freezing in charts view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#309]
Description:

Samsung S8, 1 single tag, app version 1.5.5.
User has app running for long time in foreground without background scanning enabled
Then he taps on charts icon and activates background scanning when  prompted

Actual: Now when opening charts view the app almost freezes completely.
Expected: No freezing

**Comment by andreevdenis** [comment]
How many datapoints collected?

**Comment by markoaamunkajo** [comment]
About 14k, now it's crashing

**Comment by markoaamunkajo** [comment]
You can see phone went to sleep every now and then between

![Screenshot_20210323-135654_Ruuvi Station](https://user-images.githubusercontent.com/50437378/112106080-c5f3f700-8bdf-11eb-86a5-a6bc4b16e7cd.jpg)

**Comment by markoaamunkajo** [comment]
Caused by same sensor being assigned as Network sensor in iOS. Maybe discussion for future?

**Comment by andreevdenis** [comment]
This was hot fixed for now while we make specidication on how charts should behave for iOS/Android. 
Changes: 
 - by default not showing all points
 changes for pruning mode:
 - if points quantity is less than 1000 - showing all
 - always showing all the points for last 15 minutes of history
 - removed setting for chart point interval (we recalc interval to show approximately 3000 points) - it might be 3000 points 1 day of history or 3000 points for 10 days of history - interval might vary

**Comment by markoaamunkajo** [comment]
QA passed
