### ISSUE TITLE
If user has selected shorter history on chart settings, Bluetooth sync still downloads full 10 days

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#324]
This makes syncing 10 times slower. Expected behaviour would be to read 1 day history if user is interested in to see only 1 day history.

**Comment by andreevdenis** [comment]
Current sync algorithm (for GATT and for Network) stores last sync timestamp for each sensor and next time sync will start from stored date. Implementing what you asking might be a problem if user sync with 1 day setting and then change setting to more days and expect to see longer history. We may figure something out but right now I don't see perfect solution.

**Comment by andreevdenis** [comment]
from 1.5.27

**Comment by markoaamunkajo** [comment]
Works really well for me. QA passed.
