### ISSUE TITLE
New humidity cap rules

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#326]
Lauri: So could we decide the following:

3.x FW will not cap BME280

Android & iOS BLE libs should not cap humi to 100%

Humi should not be capped to 100% before humi calibration on the apps

Humi should be capped to 100% before dew/abs calculations and of course the calibrated humi value should be used on the formulas

Humi should not be capped to 100% on exports

Humi should be capped to 100% on the apps otherwise always when showing it to users

**Comment by DG12** [comment]
IMHO Humi SHOULD be capped for BOTH "exports" and "otherwise showing to users". i.e. whenever viewable by users.

PS Please use adjustment not calibration. :-)

Lauri: Your call.

**Comment by laurijamsa** [comment]
Actually, we discussed this internally further and came to a conclusion that we'll continue clipping BME280 humidity readings to 100% on the firmware side also in the future. 2.5.9 firmware is also doing so. So, I'm closing this issue because no actions needed on the mobile apps for now.
