### ISSUE TITLE
Remove timezone and "Updated" texts of the last updated messages globally on the app

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#332]
![image](https://user-images.githubusercontent.com/1311912/114677595-a65e7300-9d34-11eb-8c52-1525e441b6cc.png)

![image](https://user-images.githubusercontent.com/1311912/114677263-554e7f00-9d34-11eb-952e-fc6e1376b005.png)

Fix also localisation on the dates shown. Seems that currently it says in English "Fri Mar" even if app language is Finnish.

Tagging @rinat-enikeev, if iOS lacks these updates, please create and issue.

**Comment by andreevdenis** [comment]
test from version 1.5.15+

**Comment by markoaamunkajo** [comment]
@andreevdenis if I choose language French it will show only "0 s" instead of "0 s ago", is it because French translation doesn't include string?

**Comment by laurijamsa** [comment]
Seems that the French translation is empty:

{
      "ident_ios": "ago",
      "ident_android": "ago",
      "en": "ago",
      "fi": "sitten",
      "ru": "назад",
      "sv": "sedan",
      "fr": " "
}

Let's assume that it's correct, but we can double check it.

**Comment by andreevdenis** [comment]
Nice catch! It's empty for French "ago" because it should go before time and it was with "Updated". Not really a good design, I'll fix it when Alexis answer me to confirm

**Comment by andreevdenis** [comment]
This is how it should be 
![image](https://user-images.githubusercontent.com/24788772/115990320-3325ee00-a5cb-11eb-8b21-e6d01247372e.png)

**Comment by andreevdenis** [comment]
check 1.5.16 for French fix

**Comment by markoaamunkajo** [comment]
QA passed.
