### ISSUE TITLE
Show an icon depending on where the most recent data came from

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#333]
Option 1: Via Ruuvi Gateway

Option 2: Bluetooth (broadcast)

Option 3: Bluetooth (connected, currently available only on iOS)

Option 4: From OpenWeatherMap (Virtual sensors, currently available only on iOS)

![image](https://user-images.githubusercontent.com/1311912/114691985-6900e200-9d42-11eb-8302-42050652b7f8.png)

Icons are attached on the ZIP file. Use 50% transparency on the icons. Align to right (same as the text).

[icons.zip](https://github.com/ruuvi/com.ruuvi.station/files/6310004/icons.zip)

**Comment by andreevdenis** [comment]
test from version 1.5.15+

**Comment by DG12** [comment]
Sounds good.

**Comment by markoaamunkajo** [comment]
Cannot get any tag data from gateway now. Not sure if the server is down.
None of my sensors are getting data from gateway. I reset gw and added it to network, took my phone far away from sensor reach and made sure I'm on 4G network not home wifi.

**Comment by ojousima** [comment]
"Works fine for me"

**Comment by markoaamunkajo** [comment]
QA passed
