### ISSUE TITLE
Show a battery capacity indicator

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#335]
This issue is to discuss about on how we could estimate if battery should be replaced or not.

Currently, RuuviTag reports battery voltage but that doesn't really help non-technical users. And even if users would know how voltage levels on coin cell batteries' discharge curves look should look like, things get more complicated because operating temperature has a pretty noticeable effect on the voltages reported.

So, we'd need to come up with a simple algorithm that would estimate remaining battery capacity percentage using the voltage and temperature information. After we've decided on how to estimate the capacity, let's add the info next to the voltage reading on the sensor settings views on Android and iOS.

It's not really necessary to tell the estimated percentage to users because it's not accurate but instead we could show following:

"Battery capacity <30%"
"Battery capacity 30-70%"
"Battery capacity 70-100%"

Tagging @ojousima, please share your thoughts and suggestions on this. We should add this feature because we pretty frequently receive feedback from users that it'd be really good to know if the battery should be replaced or not.

**Comment by ojousima** [comment]
I would track the reboots or uptime of tag to estimate when it's time to change the battery, that's the most reliable indicator we have

**Comment by laurijamsa** [comment]
What'd be your approach to track reboots or uptime of RuuviTags reliably on mobile devices that may have or may not have history logs available or Ruuvi Station app may have or may have not been reinstalled the phone? Keeping track of sensors' uptimes in local or remote database sounds like a complicated and not so reliable solution to me.

When a device starts to reboot due to a low battery, it's also too late to make any predictive maintenance. We don't need the most reliable indicator available, we just need some rule to roughly estimate if battery should be replaced so that no reboots will start to happen anytime soon.

**Comment by io53** [comment]
How steep is the voltage drop typically when the battery capacity is getting low? If it is not too steep and as long as the battery indicator does not become intrusive I think just looking at the voltage could be enough, false positive is better than false natives in this case I think. We would need to account from temperature tho. And if the temperature is too low maybe there could even be a (!) icon, with the explanation that the battery temperature is too low to know the level.

**Comment by DG12** [comment]
There is some thoughts on the battery : [here](https://github.com/ruuvi/ruuvitag_fw/wiki/FAQ:-battery)

How do other systems judge remaining battery life?

Any ideas from Nordic?

**Comment by Fugit185** [comment]
What about collecting data from field (battery voltage, tag type(4/3 sensors) and temperture) and then make self adjusting/learning algorithm. Then user message would be (in application) "with current usage your RT batteri will last x months/weeks/days etc."?

**Comment by ojousima** [comment]
That probably would be technically possible with all the data Ruuvi Cloud has. In meanwhile we could use the thresholds used for DFU

**Comment by mpvader** [comment]
Hi, I found this issue since we planned to do something similar. I’d prefer to keep our implementation real simple.

is there something against giving a warning at <= 2.5V and an alarm <= 2.3 volt?

**Comment by laurijamsa** [comment]
@mpvader we have recently added low battery threshold levels to warn user before trying to update firmware: https://github.com/ruuvi/com.ruuvi.station/issues/538

Those levels should be pretty good guesses. Note that they depend on the temperature.

**Comment by DG12** [comment]
I have several systems that run a long time (months) with less than 2.3 volts.
I refer [[to](https://github.com/ruuvi/ruuvitag_fw/wiki/FAQ:-battery)](https://github.com/ruuvi/ruuvitag_fw/wiki/FAQ:-battery)

**Comment by laurijamsa** [comment]
Let's finally implement this simple low battery indicator using the same logic we are using when updating the firmware, it's described here: #538 

The message should be shown next to the voltage reading in the sensor settings page:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1311912/164592558-cddd974a-f71c-4dcd-83b8-0a3ac6f21be8.png">

English strings: "(Replace battery!)" "(Battery OK)"
Finnish strings: "(Vaihda paristo!)" "(Paristo OK)"

It would look like this basically then:

**Battery Voltage** _____________ (Replace battery!) 2.152 V
**Battery Voltage** _____________ (Battery OK) 2.752 V

**Comment by markoaamunkajo** [comment]
1.10.2

Spotted so far

Replace battery! indicator shown for battery with 2.331V at temperature 22C
Battery OK indicator shown for battery with 2.911V at temperature 6,32C

**Comment by markoaamunkajo** [comment]
Finally got back to this task with precise voltage provided from special lab device.

if temp is less than -20C, low battery threshold = 2V

This one seems not to be working correctly, it should alert only after voltage is under 2V

![Screenshot_20220704-072856_Ruuvi Station](https://user-images.githubusercontent.com/50437378/177063074-da4e3dca-3a3d-4ff4-8c50-6538b53f6e37.jpg)
![Screenshot_20220704-072849_Ruuvi Station](https://user-images.githubusercontent.com/50437378/177063081-f40dde90-e1ba-4d13-9ebf-540aca51d0ef.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
