### ISSUE TITLE
sensor already claimed - now what -1.5.8

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#336]
Tapping on claim station reports 
Failed to claim tag, Sensor already claimed. Even though Owner says none.

Station should display additional information like obfuscated ID of user who has already claimed it laur***sa , IP address like 202.44.197.*, time and date of claim, time data of last update.

Maybe even offer to send secret email to current user, that user den**eev , from IP.....,attempted to claim on yyddmm hh:mm.

Application should suggest "lf you really want to claim this RuuviTag...

**Comment by andreevdenis** [comment]
Issue for server side development will be created.
