### ISSUE TITLE
Already shared - needs to display who tag data is shared with - 1.5.8

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#338]
Up to 10 friends should be displayed and allow user to "unfriend" one.

"user not found" should include something like: Have your friend register by ....

**Comment by andreevdenis** [comment]
Works for me. To be implemented soon - send invitation email to not registered user when someone shares sensor to him.

![photo_2021-04-21_19-27-19](https://user-images.githubusercontent.com/24788772/115588890-e5159f80-a2d7-11eb-8ec3-bde680d3c67b.jpg)
