### ISSUE TITLE
Attempt to share fails with no data although synchronized and claimed - 1.5.8 - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#339]
1) Starting a new tag cannot claim, no data however export shows 25 data points.

2) Now tag is claimed and reports synchro successfully 5 minutets ago, but cannot share (PS synchro successful message needs to stay present longer)

3) App should check for data before user enters email address.

user is dgerman@Real-World-Systems.com

**Comment by andreevdenis** [comment]
It is mandatory to have measurements in Network to be able to share sensor and only Ruuvi Gateway can send data to Network. Agree, we should add check before trying to share.

**Comment by andreevdenis** [comment]
Sami is working on improving sharing api. We'll be able to improve UX when it's done

**Comment by andreevdenis** [comment]
@markoaamunkajo Many words in description but I only did this: **App should check for data before user enters email address**

Sami implemented new API for shared sensors and now when I open this dialog I already know if I can share sensor or not (in case if sensor has no data in Network). I can disable send button in this scenario, but it would be also nice to tell user why it's disabled.

Lauri: Only sensors within range of your Ruuvi Gateway can be shared. If you don't have one, get it on ruuvi.com

**Comment by markoaamunkajo** [comment]
QA passed
