### ISSUE TITLE
Feature request: one-time alerts

### ISSUE THREAD

**Issue by Z1ni** [ruuvi/com.ruuvi.station#341]
It would be nice to support one-time alerts/notifications without constantly creating the notification while the value is below/over the threshold. Currently if the user dismisses the alert notification, it gets created again and again until the value is between the lower and upper thresholds.
There are situations where one would want to only be notified of a change, but wouldn't want to be notified about it constantly.

For example: outside temperature hit 25 degrees Celsius, notify user one time, but don't alert them constantly.

**Comment by andreevdenis** [comment]
We'll consider this, but for now I want to mention that you have additional options in current solution: disable alarm completely or mute it for an hour:
![photo_2021-04-21_19-15-12](https://user-images.githubusercontent.com/24788772/115587120-f65dac80-a2d5-11eb-863a-b9bad9f65c4d.jpg)

**Comment by andreevdenis** [comment]
Just click "Disable this alarm" on first notification you get.
