### ISSUE TITLE
Attempt to claim with no network connectivity causes crash - 1.5.8 - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#350]
If user attempts to claim and out of range of wifi or wifi turned off app crashes.
May be same issue as #351

**Comment by markoaamunkajo** [comment]
1.5.16 Trying to signin to Ruuvi Network without wifi/network connectivity causes crash.

**Comment by markoaamunkajo** [comment]
Same in 1.5.18

**Comment by andreevdenis** [comment]
Fixed in 1.5.19

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
As of 1.5.25
In portrait orientation reports 
"Failed to claim tag. Unable to resolve host "network.ruuvi.com" 
No address associated with..."

In landscape orientation message continues:
"hostname"

No crash occurs. :-)
