### ISSUE TITLE
NETWORK INFO should include timestamps and count - 1.5.8 - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#352]
NETWORK INFOrmation should include information like
first seen :  mm/dd/yy hh:mm:ss
last seen :  mm/dd/yy hh:mm:ss
last updated  :  mm/dd/yy hh:mm:ss
number of samples

Is issue #339 Attempt to share fails with no data although synchronized and claimed related?

Is there any way to know if the tag has sent data to the gateway and the network?

**Comment by andreevdenis** [comment]
We got last updated info on sensor card. All other info is not crucial for most of the users
