### ISSUE TITLE
exported CSV is inconsistent with IOS version - 1.5.8 - minor defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#353]
Android:

Timestamp,Temperature (°F), Humidity (%), Pressure (hPa),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Voltage,Movement counter,Measurement sequence number
2021-04-17T13:10:45-0400,53.69,48.31,991.73,-80,0.724,0.672,0.172,2.455,84,15021
+++++++++++++++++++++++++++++++
IOS:

Ruuvi 06DC 
"Date","ISO8601","Temperature (°F)","Humidity (%)","Pressure (hPa)",Acceleration X,Acceleration Y,Acceleration Z,"Voltage (V)","Movement Counter", "Measurement Sequence Number","TX Power"
"2021-04-20 17:27:31",2021-04-20T21:27:31.878Z,73.07,38.99,995.43,0.056,0.004,1.011,2.685,64,58645,4
++++++++++++++++++++++++++++++
IOS data includes device name  as first row - good
IOS Date column is in quotes - is that necessary?
IOS includes ISO8601 date-time - good
Android includes RSSI - good
IOS SOME headers include quotes - not so good (better if they all did ?)
IOS includes TX power -  why?

FIle name has spaces replaced with underscores ("_") - good

**Comment by andreevdenis** [comment]
@markoaamunkajo please check this one

**Comment by markoaamunkajo** [comment]
Android uses ISO8601 in Timestamp row, no need to adjust imo. We will make changes to iOS side.

**Comment by andreevdenis** [comment]
Sure. Closing this one?

**Comment by markoaamunkajo** [comment]
Closed after an intensive debate

**Comment by DG12** [comment]
Please reopen this
IOS format includes important first line containing sensor name for example :**Ruuvi BB12 water inlet**
1)Android is missing this.

Unnecessarily includes Tx power (it's a constant and well known by owner and not even intestering) bu
2)omits RSSI which should be included as it is in the database.

IOS and Android format column title are "Voltage" and "Voltage(V)"
IOS:
Ruuvi BB12 water inlet
"Date","ISO8601","Temperature (°F)","Humidity (%)","Pressure (inHg)",RSSI,Acceleration X,Acceleration Y,Acceleration Z,"Voltage (V)","Movement Counter","Measurement Sequence Number","TX Power"
"2022-04-15 18:40:40",2022-04-15T22:40:40.000Z,65.38,49.06,29.52,-76,0.004,1.012,-0.040,2.696,109,787,4

Android:
Timestamp,Temperature (°F), Humidity (%), Pressure (inHg),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Voltage,Movement counter,Measurement sequence number,TX Power
2022-04-15T18:55:41-0400,65.4,48.97,29.52,-75,0.004,1.008,-0.036,2.707,109,1137,4.0

**Comment by laurijamsa** [comment]
Reopenind and assigning to Marko to recheck.

**Comment by markoaamunkajo** [comment]
CSV unification for all platforms is handled on card https://github.com/ruuvi/com.ruuvi.station/issues/745
Will close this issue now.
