### ISSUE TITLE
Login to Ruuvi Network text obscures text box - 15.5.14

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#358]

**Comment by andreevdenis** [comment]
what do you mean?

**Comment by DG12** [comment]
Standby trying to post screen shot

**Comment by DG12** [comment]
![networkLoginObscuresTextbox](https://user-images.githubusercontent.com/2365961/115933112-3a7ab980-a45c-11eb-8e98-60c4c88281c2.png)

**Comment by DG12** [comment]
Got it?

**Comment by andreevdenis** [comment]
What phone is it?

**Comment by DG12** [comment]
Moto E

**Comment by andreevdenis** [comment]
Did you increase system settings for font size?

**Comment by DG12** [comment]
I don't recall changing font size

**Comment by andreevdenis** [comment]
Build for testing
https://github.com/ruuvi/com.ruuvi.station/actions/runs/779358012

**Comment by DG12** [comment]
![login1155](https://user-images.githubusercontent.com/2365961/115943097-fac3ca00-a47b-11eb-8d18-b68246ed24a1.png)

Thanks

Looks good even at "largest

(at least with my short email address. I'm used to my longer email address not fitting)

**Comment by markoaamunkajo** [comment]
Samsung phones are able to choose super large font but even on that I can now fill the email field. Btw most apps layout will break with it, even Slack becomes a mess.

QA passed.
