### ISSUE TITLE
displays 32F (aka 0C) with no data . Should be "--.--" or "no data" - 1.5.15 - minor - cosmetic

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#360]
Not sure how I managed to delete all the info for sensor F7:FA:74:4A:1E:1A,
It seems that temperature is initialized to 0 C which converts to 32.00F which should be suppressed.

Icon for "last source" seems to default to gateway should also be surpassed.

Remaining "Sensor Settings" panel correctly suppresses. "MORE INFO"

**Comment by andreevdenis** [comment]
I don't understand. Can you add screenshots?

**Comment by DG12** [comment]
Sorry I meant to include a screen shot but I have the hardest time with the slipperiness of the phone.

**Comment by andreevdenis** [comment]
Now you will see last known data from sensor or won't see this sensor at all if no data available for last 10 days
