### ISSUE TITLE
Network update should say what (if anything it did) -1.5.15 - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#362]
Instead of just 
"sync successful",
 message should include number of tags synced.
Even first network data date/time, most recent network date date/time
It is currently nearly impossible to determine if the gateway is running and updating.

Really helpful would be fields on EACH panel  like:

Last network sync at mm/dd/yy hh:mm:ss
Last network data from mm/dd/yy hh:mm:ss

**Comment by andreevdenis** [comment]
See #401
