### ISSUE TITLE
Dark mode (theme)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#366]
If user's phone has the dark theme enabled, use dark theme on the Ruuvi Station. Add a toggle switch on the App Settings view to toggle between normal and dark themes.

https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by andreevdenis** [comment]
1.12.2

**Comment by andreevdenis** [comment]
check #703 for dark mode styles

**Comment by sini-maaria** [comment]
Icon color for alerts on dashboard: #35ad9f

**Comment by sini-maaria** [comment]
![Screenshot 2022-06-15 at 10 37 26](https://user-images.githubusercontent.com/19531763/173770291-106cbb72-57d2-4793-a033-8ee637630537.png)

**Comment by sini-maaria** [comment]
![Screenshot 2022-06-15 at 10 39 31](https://user-images.githubusercontent.com/19531763/173770614-070fd638-528e-4ec4-aa07-c58e4f8f28f5.png)

**Comment by sini-maaria** [comment]
Font in the top header (for example "Sensor Settings") is Montserrat Regular 18px.

**Comment by sini-maaria** [comment]
While you are adjusting colors: #35ad9f, 15%

<img width="853" alt="Screenshot 2022-06-16 at 14 58 17" src="https://user-images.githubusercontent.com/19531763/174065111-2b7796cd-6e62-45ca-93c9-186bcda11289.png">

**Comment by sini-maaria** [comment]
- Icon color on signal icons should be darker.
- Is the "dBm" 50% or is the color on dashboard too dark? They should be the same.

<img width="974" alt="Screenshot 2022-06-21 at 12 14 09" src="https://user-images.githubusercontent.com/19531763/174763775-14870734-47ad-4252-9ed8-6b59471e634e.png">

**Comment by sini-maaria** [comment]
LIGHT MODE
80% opacity for subtitles and text is good in the dark theme. But, please change all light theme texts to 100%.

**Comment by sini-maaria** [comment]
On switch looks different here:

![Screenshot_20220626-194704_Ruuvi Station](https://user-images.githubusercontent.com/19531763/175825866-78ef5dd7-4e6d-497f-b83e-21d23f51af1c.jpg)

**Comment by sini-maaria** [comment]
Add title styles here:

![Screenshot_20220626-194752_Ruuvi Station](https://user-images.githubusercontent.com/19531763/175825927-34b9caf6-0c24-4e76-9c8e-1b0339db9307.jpg)

**Comment by andreevdenis** [comment]
@markoaamunkajo please check how the app is working after implementing dark theme.

**Comment by markoaamunkajo** [comment]
QA passed
