### ISSUE TITLE
Crash on GATT sync (from crashlytics)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#367]
Try to push sync and then switch from graph view and (maybe) change sensor
![image](https://user-images.githubusercontent.com/24788772/116442036-b6a93e80-a85a-11eb-9085-28f4c11173da.png)
![image](https://user-images.githubusercontent.com/24788772/116442058-bb6df280-a85a-11eb-9e81-36153407fa97.png)

**Comment by andreevdenis** [comment]
in 1.5.20

**Comment by markoaamunkajo** [comment]
QA passed
