### ISSUE TITLE
Replace signal strength with movement counter and vice versa

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#368]
Let's bring the movement counter info on the card view and dashboard. Move the signal strength info to under More Info section on sensor settings view.

One reason we delayed creating issue about this swap is that the movement counter rolls over to 0 after it has reached 255 and this may confuse users. And for this reason we're planning to introduce informational popup tip boxes when user taps any of the variables (temperature, humidity, pressure, movement) on the card view. But we'll have a separate issue task about that.

Find icon for the movement counter attached:

[movement_icons.zip](https://github.com/ruuvi/com.ruuvi.station/files/6395804/movement_icons.zip)

**Comment by DG12** [comment]
Future enhancement will be to permit user to select which sensors are displayed on the card view and which are only available under more info. 
Should this be a seperate issue?

**Comment by laurijamsa** [comment]
No need to create a separate issue. That feature is already included in our future ux update plans.

**Comment by andreevdenis** [comment]
check in 1.5.19

**Comment by markoaamunkajo** [comment]
I have trouble getting the measurement sequence to update in the app
Tried fresh installation and sensors with fw 2.5.9 and 3.x

https://drive.google.com/file/d/16LBJWYdiLHV8vwZ2FIVguw-57NQtRZfh/view?usp=sharing

**Comment by markoaamunkajo** [comment]
Had issue with one 2.5.9 tag. Reflashed it and now works perfectly reading movement measurements.
QA passed
