### ISSUE TITLE
[DISCUSS] Unify user experience when using charts in mobile app for iOS/Android

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#369]
Currently both apps have many differences in charts. Let's make user experience similar as much as possible. First step is to create universal guideline for charts.

Known differences:

1. Android version has syncronized transition and zooom for all 3 charts. I think it's a must have feature and should be added to iOS

2. Android has a real time update feature when you can see new points on chart right after they were writen to DB. It's mostly useful when you just added new sensor. But when you have long history already it's unnoticable for user (you can see updates if you zoom in to end of chart). Not sure if we really need it in current state. Maybe we should update it in real-time only if count of datapoint is less then 100 (for example). Or implement some new alternative real-time mode for charts (showing always only last 5/15/30/60 minutes of history)

3. Different algorithms of downsampling. Android currently supports only decreasing number of points by selecting only 1 datapoint for each 1 to 60 minutes. iOS have more complicated LTTB algorithm (not sure if it's suitable for 3 syncronized charts)

4. Different seetings for charts. Android has support of changing history view period and to enable drawing point on graph.

**Comment by priyonto** [comment]
1. I believe the first one is already available on iOS. 
2. I am not sure about the number 2, as we have discussed it yesterday, especially in cases for the not connectable tags. If we consider storing data in the foreground just like android then the real-time update makes more sense. Right now we receive advertisements but that does not reflect immediately on the chart after adding a new tag.

3. A bit more explanation would be helpful for me on the 3rd one. 
4. This one is pretty clear.

**Comment by laurijamsa** [comment]
Is the 1) really available on the iOS? When you're zooming one of the graphs (for example temperature), do the other ones zoom too?

**Comment by priyonto** [comment]
Yes, I believe so. I have pinched only one at a time here. 

https://user-images.githubusercontent.com/24395776/154227124-aadd3bd0-9786-4ae7-bb1c-50f3071d20f5.MP4

**Comment by andreevdenis** [comment]
2) If you'll add new sensor and switch to chart you'll notice that new points appear in real time as we save them to db in foreground. Even if you have long history you can zoom in to the end of the chart and see how new points appear.

3) How downsampling works in Android. 
Display all data in chart - will display everything without downsampling. 
If it's disabled then:
1) if history has less than 1000 points - show everything
2) We divide selected by user view period on 3000 pieces and show only 1 point from each piece (getting it by a simple SQL query)
3) Always showing all points from the latest 15 minutes

iOS got much more intelegent way to downsample data based on some math algorithm.

**Comment by priyonto** [comment]
@laurijamsa 

About point 2: I am unsure how frequently we are able to store data on the iOS now to show the real-time update just like the android app. Especially if we consider the not connectable tags. I need a bit more guidance here. 

About point 3: Should we unify the downsampling algorithm on both of the platforms? Right now it looks to be working pretty well. Just not exactly the same I believe.

**Comment by laurijamsa** [comment]
I suggest to work with more urgent matters first and specify later together with Denis and Elias common practice on this downsampling thing. The point 2 needs also some more thoughts before rushing to implementing. I may share more comments about this later and we can have a meeting about this too.

**Comment by priyonto** [comment]
@laurijamsa Agree completely. Thank you :)

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like all of these are otherwise done, is this one also completed? Can this card be closed?

_3. Different algorithms of downsampling. Android currently supports only decreasing number of points by selecting only 1 datapoint for each 1 to 60 minutes. iOS have more complicated LTTB algorithm (not sure if it's suitable for 3 syncronized charts)_

**Comment by andreevdenis** [comment]
Agree
