### ISSUE TITLE
Humidity calibration "See Calibration tips are available on xxx " need correction -1.5.16 - minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#370]
It does not got to a specific page.

**Comment by andreevdenis** [comment]
It goes to ruuvi.com/support at least on 1.5.16. You have different behaviour?

**Comment by DG12** [comment]
Perhaps it should go to [https://ruuvi.com/humidity-sensor-on-ruuvitag/](https://ruuvi.com/humidity-sensor-on-ruuvitag/) .

I had a hard time finding that article from the support page

Although that currently is specific to BME280 however , hopefully with the SHTC3 no one will care about this issue.

**Comment by andreevdenis** [comment]
New articles will be added to ruuvi.com/support
