### ISSUE TITLE
Implement Network Alerts

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#377]
Network currently supports alert only for temperature, humidity and pressure. Also no support for custom description. Consider this when testing

**Comment by markoaamunkajo** [comment]
Network alert Emails received for:
Humidity
Pressure
Temperature

Sensor name formatting and custom alert texts are missing in email.

Movement and RSSI doesn't seem to trigger any alert.

**Comment by andreevdenis** [comment]
Yes. It's not yet fully implemented on Network side, but sync of alerts is ready. Check if we can store/restore alerts with Network. Sami should finish his part of the job soon.

Local alerts should work as before if you getting measurements from Bluetooth.

**Comment by markoaamunkajo** [comment]
QA passed.
Network not handled on this card.
