### ISSUE TITLE
1.5.18 Syncing single network sensor with all datapoints setting enabled will freeze app.

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#380]
Description:

User has 1 sensor with 9 days of data that was added to network. User set chart settings to display all data in chart enabled and draw dots in chart enabled. Chart history is full 9 days.

Actual: After syncing data from network and going to chart view app starts slowing down and goes to total freeze until it crashes.

Expected:
Not sure what is expected, it seems like this setting might be the culprit and it causes data arriving from network to freeze app.

https://drive.google.com/file/d/15AWxCAYbI--e9_HG04Kn_Yx-68SV9WX5/view?usp=sharing

**Comment by andreevdenis** [comment]
How many data points?

**Comment by markoaamunkajo** [comment]
Looks like 11,309 according to About page. It's single sensor.

**Comment by andreevdenis** [comment]
Too much :(

**Comment by markoaamunkajo** [comment]
To be clear the whole app freezes when I open charts view, not when I'm on sensor card view or elsewhere in app.

**Comment by andreevdenis** [comment]
Same problem as #149
