### ISSUE TITLE
[DISCUSS] Reword "Gateway" feature on the app so that it cannot be mixed with Ruuvi Gateway

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#383]
@io53 @andreevdenis @ojousima please suggest correct wordings for the feature. I cannot right now come up with anything I would be happy with, so better that I don't suggest anything.

**Comment by markoaamunkajo** [comment]
POST Center
Data Stream

**Comment by io53** [comment]
Something in line with Data Endpoint or Data Relay Endpoint would work too

**Comment by DG12** [comment]
mutteri, (it's where the ruuvi [data] goes into)

**Comment by andreevdenis** [comment]
renamed to data forwarding

**Comment by markoaamunkajo** [comment]
QA passed
