### ISSUE TITLE
Make it possible to configure multiple alerts per one environmental variable

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#387]
This is a user feedback. Opening an issue so that we won't forget it. Let's decide later if we'd like to take action.

"Would be nice to be able to configure a couple of different alerts. For example in sauna I would like to know when it reaches 65C (ready) and when it's 80C (too hot)"

**Comment by andreevdenis** [comment]
@laurijamsa put it to user feedback
