### ISSUE TITLE
Reboot Bluetooth in the app if it gets jammed somehow (investigation)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#389]
Sometimes Bluetooth scanning mysteriously stops on some phone models and even killing the app doesn't help. If it's possible to somehow initialise the Bluetooth scanning service, the manual refresh could do that. This should be possible also without being logged in.

**Comment by laurijamsa** [comment]
The same user who originally reported this bought a new phone (OnePlus) and is still having the same issue. The issue is that even when opening the app to foreground, Bluetooth scanning doesn't start and sensors don't update, not even if waiting tens of seconds and the sensors are within 2 meters from the phone. Then, after restarting the app 1-3 times, it starts to scan again.

The original phone:

Device: OnePlus GM1903
Android version: 11
App: Ruuvi Station 1.5.16

The new one is most probably running on Android 12.

**Comment by markoaamunkajo** [comment]
Another user reported the same on

Device: OnePlus LE2113
Android version: 12
App: Ruuvi Station 1.12.11

**Comment by laurijamsa** [comment]
Increasing priority of this investigation because recently we've received a couple of new feedback about app not always updating when on foreground.

**Comment by markoaamunkajo** [comment]
@andreevdenis can we reboot Bluetooth when reopening the app, and without interrupting connection to other connected devices, ie Bluetooth headphones?

**Comment by markoaamunkajo** [comment]
Investigated this a little bit. I cannot make the connection jammed yet with my devices on Huawei Nova 3i, OS12.
Need to add some BT headphones etc when back home and see if I see the crash.

**Comment by markoaamunkajo** [comment]
Continuing on card https://github.com/ruuvi/com.ruuvi.station/issues/986
