### ISSUE TITLE
1.5.19 Network sensor with fw 2.5.9 crashes when trying to open chart

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#390]
Description:

User made clean install of 1.5.19 and signed into network. His account has two sensors , fw 3.x and fw 2.5.9.
Data is downloaded and cards are created on signin. User then tries to open charts view on 2.5.9 sensor

Actual: chart is showing briefly and tells charts are empty, then app crashes.
Expected: data was downloaded successfully and chart opens.

Extra note: I was testing clearing charts data and syncing data from network on iOS app earlier. Sent error report via reporter too.

**Comment by andreevdenis** [comment]
I doubt this was caused by charts or sensor with specific FW version. Check if you can reproduce this in 1.5.20

**Comment by markoaamunkajo** [comment]
Hi @andreevdenis  can reproduce in 1.5.20, clean install, sign into network and trying to open charts view.

**Comment by andreevdenis** [comment]
Wait, sounds weird anyway. We shouldn't have crashes with any humidity unit

**Comment by markoaamunkajo** [comment]
It's super weird but I have no clue what would have caused it.
I reflashed fw, synced strange app settings on ios to network, reinstalled, now it never crashes.
