### ISSUE TITLE
sync should progress and results - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#391]
I suggested in Issue # 413 IOS
 Sync should report what it had and what it got - enhancement 0.6.1(18) #143

in addition, Please don't just say. Synchronizing. Instead report progress. for example:

- syncing 
- syncing connecting to mutteri
- syncing connected to mutteri
- syncing 1
- syncing 10
- syncing 100
- syncing 1000
- syncing 2000
- ...
- syncing disconnecting
- syncing disconnected 
- syncing complete 4321 events received    (wait for 5+ seconds for user to see

Although normally this stuff (except the last message) will just flash by,
it is very helpful when there is a problem especially if it is intermittent.

Maybe an  additional diagnostic card with LOG.DEBUG, LOG.INFO, LOG.WARNING, LOG.ERROR.
When customers are having problems this will be even more important and helpful.

This applies to GATT sync as well mutteri [ ruuvi cloud  :-)  ]

This applies to both android and IOS.

**Comment by andreevdenis** [comment]
Will be implemented in #401
