### ISSUE TITLE
Cloud management functions: suspend/reactivate & delete 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#402]
There needs to be a means to delete a tag that is lost, broken etc.

There needs to be a means to suspend a tag (in particular related to subscription plan).
Scenario is I have 10 active(max free subscription). I deploy 3 to the field i.e. out of range. 
I buy 3 more. I retrieve 1 from the field and suspend  (at least 1) etc, etc

See also network-serverlesst issue #85.

**Comment by andreevdenis** [comment]
Delete sensor to unclaim it

**Comment by DG12** [comment]
I guess unclaim would handle suspend and claim would handle resume but it still feels like that is not the same thing. I cannot put my finger on it right now.  There may be some sharing considerations.? 
Example I HAVE several tags. I share them with you and Lauri.  The tags are deployed remotely and currently not updating. I want to notify the cloud that they are suspended( aka inactive).
If you or Lauri "look" at them will they appear as "defective" I.e. not updating?



unclaim does not delete data on cloud.
