### ISSUE TITLE
Compose: Add possibility to display long Tag names

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station#406]
see https://github.com/ruuvi/com.ruuvi.station.ios/issues/147

just multiline label

**Comment by andreevdenis** [comment]
Changing this behaviour is bloked in currently used UI components. Can't fix without serious refactoring.

**Comment by markoaamunkajo** [comment]
Possibly related to compose

**Comment by markoaamunkajo** [comment]
QA passed
