### ISSUE TITLE
GATT sync occasionally gives a Disconnected pop-up

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#413]
Firmware 3.30.2 and Android app 1.5.24 and 1.5.26. Phone Samsung Galaxy S20 Note Ultra.

Disconnected message appears after successfully synced. I have reproduced this several times but it doesn't happen every time. Syncing time <1min so should not be related to the firmware timeout which is 5min afaik.

It is unclear if this is issue of Android or the firmware. I have not tried to reproduce on iOS.

Another possibly related thing:

Today on 1.5.24 before updating to 1.5.26 I did not press OK on the Disconnected dialog in a few minutes and then when I tried to press it, the app had frozen and was totally unresponsive for ~1min until it suddenly recovered. The phone had only ~10k datapoints in the local database, so should not be directly related to performance issues. Background scanning was off.

**Comment by andreevdenis** [comment]
from 1.5.27

**Comment by markoaamunkajo** [comment]
I had this happen on single tag couple of times then it disappeared. It disconnected almost at the end after 2000+ readings and tag was in range in same room about -70dB away from me.

Samsung S8 with OS 9
I was specifically trying to download full 10 days data. Firmware on tag is 3.30.2+default  and data format 5 according to NFC reader. Only this one sensor added to Ruuvi Station.

**Comment by markoaamunkajo** [comment]
Tested this with S8, fw 3.30.2+default and 1.6.4 and it doesn't disconnect for me anymore with 10 days data.
However if sensor is a little bit further away in same room the sync speed deteriorates quite significantly.

@laurijamsa Could you try with latest build if you still see Disconnection?

**Comment by markoaamunkajo** [comment]
Update: Next day after collecting data I tried to sync same sensor and it disconnects me all the time.

**Comment by andreevdenis** [comment]
This was because tiny timeout for connection. Please check version 1.6.6

**Comment by markoaamunkajo** [comment]
No issues detected on first day sync tests, will redo these again tomorrow.

**Comment by markoaamunkajo** [comment]
QA passed
