### ISSUE TITLE
App takes longer and longer each time the chart is rotated - defect -1,5,25

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#414]
Tap to display the graph.
Rotate to landscape.
Rotate back to portrait, observe some delay.
Rotate to landscape again, observer longer delay.
Rotate back to portrait, observe even longer delay.

See http://MyBeacons.info/station for video ( be advised it is a  247,277,218 byte file and takes 15minutes.
You could download it and play it a faster speed.

**Comment by andreevdenis** [comment]
@markoaamunkajo can you check this? I couldn't reproduce with samsung s6

**Comment by DG12** [comment]
$%$$%$ safari discarded my entry. trying again.
moto E4 Nougat
android 7.1.1  sprint version but non account wifi only
RAM 2GB 
only other (apparent) app is CPUn monitor
as of now 3,557 rows
PM me your email and I'll share it with you

**Comment by DG12** [comment]
Now that I went to the trouble to renter the specs (part of them)

The problem , which was very pronounced , seems to have "gone away"

I will reopen if I can duplicate.
