### ISSUE TITLE
1.5.26 User thrown to Dashboard view during network sync

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#416]
Description:

User with S20 Ultra kept app in foreground charts view, when network was synced and user was forwarded to Dashboard view.

Bluetooth seems to have stopped listening advertisements from this sensor.

Expected: keep user on current screen, keep listening

Note: it will not happen if user manually syncs with network using button in menu.

**Comment by andreevdenis** [comment]
Can't reproduce this one. Please check again. On sync in charts screen I currently can see only issue #484

**Comment by markoaamunkajo** [comment]
Qa passed not reproducable anymore.
