### ISSUE TITLE
Add Firebase analytics

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#418]
Add firebase analytics
Sensor count up to 25
More than 25

**Comment by andreevdenis** [comment]
Changes made on Android side:


added_tags - exact number of added sensors
claimed_tags - exact number of sensors claimed by user
offline_tags - not claimed and not shared to user (Bluetooth only sensors) 
signed_in - (true/false) user signed in to cloud or not

**Comment by markoaamunkajo** [comment]
Moving to done
