### ISSUE TITLE
Unification: Ruuvi logo

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#420]
Description:

Please use new Ruuvi logo everywhere in the app (without the eye or banner)

**Comment by andreevdenis** [comment]
1.5.43

**Comment by markoaamunkajo** [comment]
In app all good, just want to remind about the Play Store screenshots whoever will replace those.

![app_screenshots_playstore](https://user-images.githubusercontent.com/50437378/133715190-2526f413-4249-42f2-9194-0ff0c26c1771.jpg)

**Comment by andreevdenis** [comment]
It should be different task in my opinion. This one for example: https://github.com/ruuvi/com.ruuvi.station/issues/498
