### ISSUE TITLE
Unification: Background Scanning Settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#423]
Description:

Let's use iOS Data Logging Interval style
Steps, all, 1 min steps until 60 min

Default interval: 5 mins

**Comment by andreevdenis** [comment]
Decided to hide possibility to save 'all' under experimental features

**Comment by markoaamunkajo** [comment]
Missing a FI string for "Background scanning" in the new style settings.

FI: Taustaskannaus

![Screenshot_20220110-221616_Ruuvi Station](https://user-images.githubusercontent.com/50437378/148790218-c719ffdc-ccf0-46db-80a6-ea5f203113fe.jpg)

**Comment by markoaamunkajo** [comment]
Default interval should be 5 mins. Now it's 15 mins.

**Comment by markoaamunkajo** [comment]
QA passed
