### ISSUE TITLE
Prepare/check app for upcoming Android 12

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#428]
Check how app perform with beta version of Android 12

**Comment by andreevdenis** [comment]
Starting from version 1.6.6 **Log In** link from email opens in Ruuvi Station app - similar to how it worked with previous Android versions.

**Comment by markoaamunkajo** [comment]
Log in link tested as well as spent some time testing the app, I didn't find any issues. No access to OS12.
