### ISSUE TITLE
Sensor sharing keyboard layout is not correct

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#434]
The keyboard is not for email input. Meaning, there are no @ and .com keys to help with typing email addresses faster. Check also other keyboard layout styles on the app if they are correct.

![Screenshot_20210724-104954_Ruuvi Station.jpg](https://user-images.githubusercontent.com/1311912/126861644-5a2a91b2-cf28-4210-8f4b-90500c084a65.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
