### ISSUE TITLE
There is no user feedback after sharing a sensor

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#435]
After giving friend's email address, the SEND button does not give any feedback if the sharing worked or not. Only feedback is clearing the address field. I would expect to see a loading icon until email invitation is successfully sent and after that I would expect to see the friend's email on a sharee list on the sensor setting page. Now I have no idea if it is shared or not and to whom and how many of the 10 max shares I have used.

**Comment by andreevdenis** [comment]
List of users updated after successful share, but it might take some time with slow internet. Solution: add message about successful share. Also hiding "Already shared" when list of users is empty.

**Comment by markoaamunkajo** [comment]
1.5.28 user shared sensor to new email address. The sharing successful message arrived but the emails list doesn't update even after syncing network, so this part must be broken.

**Comment by andreevdenis** [comment]
It's not yet ready for testing until it's assigned to you @markoaamunkajo

**Comment by markoaamunkajo** [comment]
Oh sorry I saw the mentioned build under actions thought it was ready...

**Comment by markoaamunkajo** [comment]
QA passed
