### ISSUE TITLE
App is requesting sparse data from the cloud when it should ask for dense data

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#436]
One of my Ruuvi Gateways got whitelisted about an hour ago and its data is now stored to the cloud. If I clear local data on the Android app and then sync with the cloud, I get datapoints every ~15 minutes. On station.ruuvi.com I see dense data (~1min interval). App version 1.5.27

**Comment by laurijamsa** [comment]
After a clear&new sync (sparse data and some dense data):

![image](https://user-images.githubusercontent.com/1311912/127829669-79f6bc5b-a570-4a88-99d5-093027118c1c.png)

And after another clear&sync (only sparse data):

![image](https://user-images.githubusercontent.com/1311912/127829744-63d4c1a0-6b1d-4447-bda1-d26e19758117.png)

And another (sparse data and one extra dense datapoint):

![image](https://user-images.githubusercontent.com/1311912/127829786-b1777dbe-b50a-4b93-9300-bfd8994bdfcc.png)

(Note that I'm not in range of Bluetooth so this is cloud data only)

**Comment by andreevdenis** [comment]
fixed in 1.5.28

**Comment by markoaamunkajo** [comment]
QA passed both clean install fresh network sync and clear chart + network sync now showing 1 min interval data.
