### ISSUE TITLE
DFU unsuccessful 0.7.2(120)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#438]
" Latest available Ruuvi Firmware version: V3.30.2"
Current version:Ruuvi FW v3.30.2-RC3+default
updating 0% Device failed to connect

current version:  Ruuvi FW v3.30.3+RC1+default.
DFU Service not found

Ruuvi FW v3.30+default
Device failed to connect 

Maybe it would be a good idea to display some initial interchanges until DFU gets into actually sending the update.

**Comment by ojousima** [comment]
Is this Android or iOS issue? The tags are probably not in updatable mode in this case
