### ISSUE TITLE
Modify sensor settings page to make it easier to use the new cloud features

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#440]
Okay, I'm updating this issue now. Earlier the plan was to add more popup messages to help with the cloud features, but then we came to a conclusion that it'd be better that user would see the instructions before tapping the buttons. So, let's add more sub-pages where a feature is explained first and then user can act on it if wanted.

This is layout how those features (offsets, owner, sharing, remove) should approximately look like on the sensor settings page:

![image](https://user-images.githubusercontent.com/1311912/129333873-db015262-ea26-42e2-be59-9276f024c9d6.png)

.
.
.
.

Order of the sensor settings page:

GENERAL
Name
Owner
Share

ALERTS
Temperature
Air Humidity
Air Pressure
Signal Strength (RSS)
Movement

OFFSET CORRECTION
Temperature
Humidity
Pressure

MORE INFO
MAC address
Data format
Battery voltage
Acceleration X
Acceleration Y
Acceleration Z
TX power
Signal strength (RSSI)
Measurement sequence number

REMOVE
Remove this sensor

.
.
.
.

This is layout for all the sub-pages (offsets, ownership, sharing, remove) that are accessible under sensor settings: 

![image](https://user-images.githubusercontent.com/1311912/129333946-b6a99fb9-4b69-4663-8b2d-c7d4985e9032.png)

.
.
.
.

OWNER sub-page content (show on sensor settings page only if logged in, possible values shown on sensor settings page: Not set / Someone else / email of the one who shared the sensor with you / You):

Do you own this sensor? If yes, please claim ownership of the sensor and it'll be added to your Ruuvi account. Every Ruuvi sensor can have only one owner.

Benefits:

- Sensor names, background images, offsets and alert settings will be securely stored in the cloud
- Access sensors remotely over the Internet (requires a Ruuvi Gateway)
- Share sensors with friends and family (requires a Ruuvi Gateway)
- Browse up to 2 years of history on **station.ruuvi.com** (requires a Ruuvi Gateway)

CLAIM OWNERSHIP

.
.
.
.

SHARE sub-page content (show on sensor settings page only if logged in and if sensor is claimed by the logged in user, possible values on sensor settings page: Not shared, Shared):

You can share the sensor with friends and family if it's in range of a Ruuvi Gateway.

Receiver will be notified by email. If the receiver doesn't have a Ruuvi account, a free Ruuvi account will be automatically created at first log in.

Note that sensor's custom name and background image will be shared. The name and image sync is one time and they can be customised by the receiver. Offset values (if any) will be automatically synced, and the receiver will always see the corrected values.

**Add a friend:**

SHARE

**Already shared with:**

friend1@email.com          X
friend2@email.com          X

.
.
.
.

REMOVE sub-page content (show always but depending on if user has logged in and claimed the ownership, show different texts):

Option 1: Sensor is claimed by the user

By removing the sensor, your sensor ownership status will be revoked. After removal, someone else can claim ownership of the sensor. Every Ruuvi sensor can have only one owner.

Option 2: Sensor is a shared sensor

If you remove the sensor, owner of the sensor will be notified and you cannot access the sensor anymore.

Option 3: User hasn't logged in or hasn't claimed the ownership

Do you want to remove the sensor? You can add it again later, if needed.

REMOVE

**Comment by andreevdenis** [comment]
![image](https://user-images.githubusercontent.com/24788772/128941821-b0f562d9-0db6-42c4-af83-cbe0e73655cc.png)

**Comment by markoaamunkajo** [comment]
I'm still not 100% sure that export and remove would need their own subpages but I consider this more of a styling issue than UX.

**Comment by andreevdenis** [comment]
My suggestion for rearranging menu. **Owner** and **Share sensor** will be seen only when user logged in.


![image](https://user-images.githubusercontent.com/24788772/129712446-01859e75-0b0f-46e6-9543-b6738248cfd7.png)

**Comment by laurijamsa** [comment]
This works. But the Owner line has to have also that arrow to the right because it has a sub page. And if the sensor is a shared sensor, owner can be shown like that without the arrow and the sub page cannot be accessed in that case. I will update the issue according this.

**Comment by DG12** [comment]
After starting to write a response I realize that the current "settings page" is actually a combination of settings and status (i.e. measSeq#, battery, x,y,z movement counter, RSSI)

If a single page is retained I would prefer **status** be on the top since they change.

alerts next

After that things that don't change but need a one (+/-) time update : Name, MAC, corrections, 
keep connected , disconnected. (kinda ambiguous ) is that to the tag to to the cloud?

UUID I still don't know what that tells me especially since it changes.
TXdBm   seems unhelpful as it never changes.
Data received  via , although currently important, but Isn't that  duplicated with the icon on the main ruuvitag page?

Although owner, MAC and share are HOT items right now. 
once things have settled down I don't need to see them at the top.
 
It would be nice it the gear touch area was bigger and more separate from chart(graph) button.

**Comment by markoaamunkajo** [comment]
Looking good to me. Needs FI language implemented for this release.

**Comment by markoaamunkajo** [comment]
QA passed for the feature
