### ISSUE TITLE
Remove sensor automatically from the app if owner cancelled sharing

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#443]
Currently, if my friend shares a sensor with me and later removes the sharing, the sensor stays on my mobile app but it just stops updating and I wonder that what's wrong. I would have expected it to be automatically removed because it got automatically removed from the web app too.

It could be possible to also keep it in the app and notify user that it's not updating because it's not shared with you anymore but that would be more complex solution and it would also lead to situation that web app sensor listing would not have it but mobile would.

So, I think removing it automatically from the apps would be the best choice for now. And additionally, the cloud should send me an email that my friend cancelled the sensor sharing and for that reason I won't see it anymore. However, let's discuss about this before implementing and creating an issue of the new email notification type. This issue is duplcated to the iOS repo.

**Comment by laurijamsa** [comment]
I have discussed about this with some team members and we agreed that this would be a good modification. Later, once push messages are implemented, probably some of the email notifications can be replaced with push messages. Moving this to todo.

**Comment by markoaamunkajo** [comment]
I believe network side is now working, waiting for clients https://github.com/ruuvi/ruuvi-network-serverless/issues/117

**Comment by andreevdenis** [comment]
1.5.36

**Comment by markoaamunkajo** [comment]
QA passed
