### ISSUE TITLE
Unification: show/hide SYNC button in charts

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#444]
Description:

Let's make same way for showing/hiding SYNC button in charts view.

"I decide to show or not to show these buttons depending on connectable bit from advertisement. I can reassign this for data from network and set it as always false. I was planning to do so anyway. Local sensors will have buttons visible and remote not."

Maybe this is already in Android, if yes then for reference only.

**Comment by andreevdenis** [comment]
1.5.43

**Comment by markoaamunkajo** [comment]
QA passed
