### ISSUE TITLE
Synchronization failed, syntax error SQLITE ERROR

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#445]
I got this error message a few times when tried to sync with the cloud. Cannot reproduce anymore so maybe the server was down for a while. But if that happens, the error message shown to user should be more user friendly. Something more like "Trying to connect to the server..."

![image](https://user-images.githubusercontent.com/1311912/129948905-fa95b3b4-9069-4126-ad90-3e3cafb04a10.png)

**Comment by andreevdenis** [comment]
It's a local DB error and I already fixed it. Will be included in next build

**Comment by andreevdenis** [comment]
Should be fixed in 1.5.29

**Comment by markoaamunkajo** [comment]
@rinat-enikeev for your eyes too if something similar on iOS is possible

**Comment by andreevdenis** [comment]
No, it's our local Android bug.

**Comment by markoaamunkajo** [comment]
Haven't seen it in few installs and multiple network tests so will close this case.
