### ISSUE TITLE
Adjusting alerts when logged in doesn't save the settings to the cloud

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#446]
Renaming a sensor and adjusting offsets saves instantly to the cloud on Android and iOS.

Also adjusting alerts saves to the cloud but on iOS only. On Android, user has to close the settings page using device's back button/arrow in order to sync the modifications with the cloud.

Please make Android work the same way. Otherwise I would imagine users will configure alerts and close the app and the app didn't sync the new settings to the cloud.

**Comment by markoaamunkajo** [comment]
Reproduced.

**Comment by markoaamunkajo** [comment]
QA passed
