### ISSUE TITLE
Disabling an alarm from a notification doesn't update settings to the cloud

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#447]
If I tap "Disable alarm", the alarm gets disabled in the app locally but cloud settings don't get updated. I didn't test this on iOS. Please test on the iOS and open a separate ticket if needed.

![image](https://user-images.githubusercontent.com/1311912/130015052-6fc28165-d8e1-4889-bc1d-b32b79127e3c.png)

**Comment by andreevdenis** [comment]
1.5.33

**Comment by markoaamunkajo** [comment]
QA passed will test iOS separately.
