### ISSUE TITLE
Remove claimed and shared sensors when on logging out

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#448]
After user logs out, claimed sensors and sensors someone else shared to you should be removed from the app.

A story behind this:

A friend registered a user account, claimed a sensor and configured some alerts for the sensor. Then he shared the sensor with another email account he owns. Then he logged out (and the claimed sensor didn't get automatically removed from the app) and registered and logged in using the other email address. Instantly after logged in, the alert settings got automatically applied to the shared sensor and he started to receive email alerts. That was really confusing and that shouldn't have happened because alert settings aren't shared during sensor sharing.

**Comment by andreevdenis** [comment]
Message to confirm sign out: "When you sign out, sensors of which ownerships you've claimed on the sensor settings page, will be automatically removed from the app. When you sign in again using the same email address, the sensors will be returned from the cloud."

**Comment by andreevdenis** [comment]
1.5.34

**Comment by markoaamunkajo** [comment]
@laurijamsa It's still a rather strange experience for user who had shared sensor and sharing is ended (no logout occurring).
Should we somehow mark this sensor is not getting updates from cloud anymore? Like showing sharing has ended at last updated instead of running counter?

**Comment by laurijamsa** [comment]
Sharee receives also an email that explains that sharing has ended. We should also automatically remove the sensor (it's removed from the webui automatically) and we have an open issue about it: https://github.com/ruuvi/com.ruuvi.station/issues/443

**Comment by laurijamsa** [comment]
This works when I'm testing. But 2 comments:

1) We'd need a loading icon on Android that would be shown when something is loading. Otherwise user has no idea if something is happening or did the app just froze. iOS has one. I'll open an issue about this.
2) When the sensors are returned from the cloud after logging in again, they are returned in a random order. Because we don't yet have support in the cloud to remember the order, on the webui we decided to order alphabetically. I think we have three options here to choose: 


2.1) add support to the cloud API and sync order of the sensors always if logged in and make it possible to reorganise the sensors in the app (more work but best result)
2.2) auto organise in the app alphabetically according sensor names (quick and allows user to reorganise by renaming)
2.3) do nothing (easiest but the worst user experience)

I think 2.2 would be a pretty good choice to go with. What do you think?

**Comment by laurijamsa** [comment]
I have discussed with Denis about this and we've came to a conclusion that it'd be good to auto organise order of the sensors in the apps but before doing this, show a message to user that he/she would know what happened. I will open a new issue about this.

**Comment by andreevdenis** [comment]
We have tasks #472 and #471. So if removing on log out works as expected then this issue can be closed @markoaamunkajo

**Comment by markoaamunkajo** [comment]
QA passed
