### ISSUE TITLE
The datetime format passed to the gateway is not in a standard format

### ISSUE THREAD

**Issue by lovasoa** [ruuvi/com.ruuvi.station#45]
The datetime format passed to the gateway gives things like "Mar 24, 2018 19:32:53". It would be helpful if it were in a standard format, like [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by lovasoa** [comment]
One can use 

```java
Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").create();
```

to create a gson object and

```java
 Ion.getDefault(this).configure().setGson()
```

to have ion use it.

**Comment by io53** [comment]
Good catch. Will definitely fix this 👍

**Comment by oherrala** [comment]
@io53 while there, please convert the time into UTC timezone or include timezone information.

For server receiving the JSON it is otherwise impossible (or difficult) to decipher what timezone the sender is.

**Comment by io53** [comment]
This is fixed and will be included in the next release.
