### ISSUE TITLE
Disabling a movement alert from the notification doesn't work

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#450]
The alert stays on. 

![Screenshot_20210823-182107_One UI Home.jpg](https://user-images.githubusercontent.com/1311912/130473478-00ae7dfa-4e15-4f52-a968-a04d3ad4aca3.jpg)

**Comment by andreevdenis** [comment]
1.5.33

**Comment by markoaamunkajo** [comment]
QA passed
