### ISSUE TITLE
No enough data downloaded from the cloud when synced

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#451]
If I configure app to show 10 days history, then clearing local history of a sensor using the CLEAR button on the app, and then syncing with the cloud, only 1 day of history is downloaded.

**Comment by io53** [comment]
Sounds like it is downloading just dense data. @andreevdenis change the request to download 'mixed' data. It returns dense as much as it can and the rest as sparse.

**Comment by andreevdenis** [comment]
Thanks @io53

**Comment by markoaamunkajo** [comment]
QA passed
