### ISSUE TITLE
Unification: rename Ruuvi Network to Ruuvi cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#452]
Description:

Please remove mentions of Ruuvi Network and simply refer to "Ruuvi cloud" in network related items in app, example

Sign In email screen
Sign In code screen
Menu: Ruuvi network status -> "Ruuvi cloud status"
Sensor settings: Data Received via "Cloud"
Sensor settings: Network info -> "Cloud info"

iOS with card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/554

**Comment by markoaamunkajo** [comment]
@andreevdenis Lauri has made a new pull request for language strings (I was already asleep) so this needs recheck for next build.

**Comment by andreevdenis** [comment]
Changes included now

**Comment by markoaamunkajo** [comment]
"Logged in:" is missing translation string in language file

FI translation: "Kirjautunut:"

![Screenshot_20210902-093636_Ruuvi Station](https://user-images.githubusercontent.com/50437378/131772963-6a4d9707-4715-4c83-ba8d-10eced4628ac.jpg)

**Comment by andreevdenis** [comment]
1.5.36

**Comment by markoaamunkajo** [comment]
QA passed
