### ISSUE TITLE
Ruuvi Station loses connection very often even for sensors very near

### ISSUE THREAD

**Issue by anttin2020** [ruuvi/com.ruuvi.station#455]
Hi!
RuuviTag itself works fine but when I use Ruuvi Station on my phone (Samsung Galaxy A51-5g) to view data, it only works for few minutes, then loses connection and in most cases I need to switch to some other app and came back to get it connected again. Even that is not 100% sure way to reconnect.
Because of that alarms are pretty useless as there can be 15 minutes of gap in data.
It seems even worse in background but even if I have the sensor within 1 m from the phone and have it active all the time, the connection is just lost very often.

I heard that some phone models have problems with Bluetooth so I might be unlucky owner of one of those but still, as the switching app usually fixes the connection, could it be possible to some 'force reconnect' when the connection is lost?

I am willing to do beta testing if that helps :)

Thanks! 

Antti

**Comment by andreevdenis** [comment]
Hey! 
What do you mean by connection? We don't keep constant connection to sensor in Android app. Application just receive broadcasts sent by sensor. Can you describe your use case with more details?

**Comment by anttin2020** [comment]
Hi!
I mean that when I have Ruuvi Station open and active on my phone and I watch the chart drawing in real time, very often that just stops for 1-15 minutes unless I switch to another app and come back.
That happens even more when Ruuvi Station is not active and so the alarms are useless (I have 2 min background scan but gap may be even hours).
So the 'connection' I'm, referring to is that Ruuvi Station does not get signal from the sensor even when Ruuvi Station is active on the phone screen :)

**Comment by laurijamsa** [comment]
We have received also other complaints about this "scanning stops when the app is on foreground and need to relaunch the app". Has happened to me too sometimes, but not frequently at all. But I'm testing with only one phone model, so it doesn't mean much if it's not happening to me.

Maybe we could kick the scanning on somehow automatically if it stops?

**Comment by andreevdenis** [comment]
I'll try to reproduce on my side

**Comment by andreevdenis** [comment]
Hey @anttin2020! It's very unusual when app stop receiving signal from sensor in foreground mode. Personally I never seen this with my phones. It may be some hardware issues with Bluetooth on your phone. Probably we can detect this situation and re-initialize Bluetooth scanning. It would be great if you could help with diagnosing what is really happening. We have special app build that is writing log into file. You can get it here:  https://github.com/ruuvi/com.ruuvi.station/actions/runs/1471451402
You'll need to download **withFilelogsTestApk**
Install and run this app. Then wait till it stops getting new data from sensor. You can find log file in Downloads folder. Send it to denis@ruuvi.com

As for working in background - it is common problem especially for Samsung phones. You can find useful advices how to make app work in background here: 
https://dontkillmyapp.com/samsung

**Comment by anttin2020** [comment]
This is weird, I got notification that this issue was updated and it says above that it was commented 2 hours ago. But I installed that special version already on September 1st and now I cannot even find where I got it. I discussed about this issue with Lauri Jämsä back then but I cannot find email that has link to that or attachment :o
I also cannot find any email with log that I had sent to Denis so now I'm confused. It may be that the problem was solved by those tricks on that other site so I didn't need to do the log. But I always reply to some request so this latest comment must be new even though I have already done what it suggests :D I even discussed about this special software version with Lauri Jämsä but still cannot find the link to download it in any email :o

Anyway, the issue was not only on my phone but my father had the same problem (also Samsung phone) but the tricks on that other site solved it mostly, only occasionally it may lose data for a longer time but it is not a problem anymore.

**Comment by andreevdenis** [comment]
Ok. Sorry for confusion. Can we close this now?

**Comment by anttin2020** [comment]
No problem but was this really new comment or was it some github hickup? :)
But yes this issue can be closed, thank you!

**Comment by andreevdenis** [comment]
Yes, it was new comment.

**Comment by hakunti** [comment]
I got report from another customer today that he has similar issues. He installed app again, added RuuviTag again and it started working. Now today it doesn't get any data from RuuviTags.

**Comment by anttin2020** [comment]
oh, ok, then it was not even meant for me, sorry to interfere :D
But yes, my issue seems to be solved 90%, thank you!
