### ISSUE TITLE
Share Ruuvi sensor page doesn't show how many sensors out of max 10 shared

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#459]
Description:

1.5.31 build
Share Ruuvi sensor page has a list of already shared email addresses. We show a number of shares on iOS and we should show on Android too. Maximum is 10.

Example: "Already shared 3/10"

**Comment by andreevdenis** [comment]
1.5.42

**Comment by markoaamunkajo** [comment]
QA passed
