### ISSUE TITLE
Fi language doesn't fit email in remove sharing popup

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#460]
Description:

User has FI language in Ruuvi Station
On Share Ruuvi Sensor page he decides to remove sharing for one of his friends and is shown a popup to confirm

Actual: email doesn't fit in the popup

![Screenshot_20210830-192601_Ruuvi Station](https://user-images.githubusercontent.com/50437378/131339501-102b85a1-5258-4295-95b9-b77332b28004.jpg)

**Comment by andreevdenis** [comment]
fixed
![photo_2021-08-30_22-22-23](https://user-images.githubusercontent.com/24788772/131393431-6599d5c1-c14d-406b-b499-e29bce0b3e98.jpg)

**Comment by andreevdenis** [comment]
1.5.33

**Comment by markoaamunkajo** [comment]
QA passed
