### ISSUE TITLE
No FI string for Invalid E-Mail given error (sensor share)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#462]
Description:

There is no language string for email error toast here

![Screenshot_20210830-193804_Ruuvi Station](https://user-images.githubusercontent.com/50437378/131340253-3f3fea6b-9d52-4fdc-9851-879d85762728.jpg)

**Comment by andreevdenis** [comment]
1.5.42

**Comment by markoaamunkajo** [comment]
QA passed
