### ISSUE TITLE
Refresh cloud data automatically and simplify the menu

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#469]
If data of any of the cloud sensor's (claimed or shared) is older than 1 minute and 1 second, update automatically if app is on foreground.

Simplify the menu like this:

![image](https://user-images.githubusercontent.com/1311912/131483404-1148a30c-e7cc-4c8b-891c-d9d83e9f4be8.png)

If not logged in, do not show anything on the bottom of the menu drawer.

With the auto update feature, the refresh button becomes pretty much useless because settings are stored instantly when modified and sensors are updated when new data is expected to be available. And data is also updated on app open. We've received also comments that users didn't even understand that the refresh icon could be pressed.

We can worry about extended bandwidth usage later if it'll grow too much at some point.

**Comment by andreevdenis** [comment]
1.5.35

**Comment by markoaamunkajo** [comment]
QA passed
