### ISSUE TITLE
Shared sensor is "returned" should owners shared list be updated?

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#475]
Description:

Owner is sharing sensor to user@xx.com, user has synced sensor to his Ruuvi Station app. User then decides to delete the sensor and it stops syncing to his device, in effect the sensor has been "returned" to the owner.

But owner still sees the users email address user@xx.com in his shared sensors list.
Shouldn't the email be removed? Does this require something from app side?

**Comment by laurijamsa** [comment]
On my app this is working. When sharee removes the sensor, sharee's email gets removec from the Already Shared list on owner's app.

**Comment by andreevdenis** [comment]
It should work like you expect @markoaamunkajo but not in real-time.  At least reopen sensor settings to refresh email list.

**Comment by markoaamunkajo** [comment]
1.5.37 
I had more time to play with it and now I understand what happens: if user who received the shared sensor renames sensor and deletes it it will not delete from the shared list of the owner. See video:


https://user-images.githubusercontent.com/50437378/132273235-ebead20b-2649-46db-ac9f-1c3a039454a3.mov

**Comment by laurijamsa** [comment]
I still cannot reproduce this issue.

**Comment by andreevdenis** [comment]
1.5.38

**Comment by markoaamunkajo** [comment]
QA passed
