### ISSUE TITLE
Auto capitalise when renaming sensors

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#481]
Currently, when renaming, name of the sensor starts with a lower case letter and user has to change it manually.

**Comment by DG12** [comment]
I would prefer to not have station change the capitalization I enter.
For example BackDoor should not be changed.

**Comment by laurijamsa** [comment]
By auto capitalisation I mean only that Android's keyboard layout should offer the first letter to be a capital letter.

**Comment by andreevdenis** [comment]
1.5.42

**Comment by markoaamunkajo** [comment]
QA passed
