### ISSUE TITLE
Force capital letters when typing the one time code

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#482]
I think this would make the user experience better because then user wouldn't need to wonder will lower case letters work or not. Create also a unification issue to the iOS repo if needed.

**Comment by DG12** [comment]
Please see also suggestions: 
https://feedback.ruuvi.com/posts/36/easier-network-login
https://feedback.ruuvi.com/posts/45/one-time-an-activation-code-is-correctly-should-be-enough

**Comment by andreevdenis** [comment]
1.5.42

**Comment by markoaamunkajo** [comment]
QA passed
