### ISSUE TITLE
Scandic alphabet ordering is incorrect

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#486]
Description:

Scandic letters are still not organized alphabetically correct for me in this build I see sensor name starting with Ö coming before sensor starting with P.

Language FI
Synced sensors from cloud

**Comment by andreevdenis** [comment]
This may occur if you installed app while your system language wasn't Finnish and after app install you switch language. For some phones restarting app will help (works for my Pixel 4a). For Huawei phone reinstalling app with selected Finnish language helped. 

I think if user from Finland prefer to use English as system language he will encounter wrong sorting anyway. If he uses Finnish language then most likely app will sort correctly for him.

**Comment by andreevdenis** [comment]
same as #487
