### ISSUE TITLE
Switching language on phone affects auto-organising sensors alphabetically

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#487]
Description:

User installed app when device language was set to English, then synced sensors from cloud, it organises scandic letters to wrong order (Ö becomes before P). Switching device language to Finnish doesn't now auto-organise sensors.

But if user installed app when device language was set to Finnish, synced sensors were organised correctly.
In future we will possibly make it an option to change language from the app. This card to backlog.

**Comment by andreevdenis** [comment]
Fixed. But user still need to restart app to different sorting. 
1.7.11

**Comment by markoaamunkajo** [comment]
QA passed
