### ISSUE TITLE
1.5.42 Dashboard arrow exists app first time after cloud sync 

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#492]
Description:

Couldn't find a card for this. 
User has set dashboard view and synced it to cloud, then signs out from app and signs in to cloud again.
Actual: user will see cards view with arrow at top left corner. Tap on arrow closes app.

Expected: go to dashboard view.

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/133627550-bd8b5874-d7a9-4659-b6b9-ba5789579f66.mp4

**Comment by andreevdenis** [comment]
1.5.45

**Comment by andreevdenis** [comment]
Can be tested @markoaamunkajo
