### ISSUE TITLE
Sensors cannot be claimed or shared if phone's default font size is too big

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#500]
The views cannot be scrolled. Double check also all other pages that they don't have the same issue.

Screenshots:

![Screenshot_20210919-203202_Ruuvi Station.jpg](https://user-images.githubusercontent.com/1311912/133937189-9a99f416-86e4-424a-9aa8-a08e4e509163.jpg)

![Screenshot_20210919-203222_Ruuvi Station.jpg](https://user-images.githubusercontent.com/1311912/133937192-8e07a6b5-24e8-4f1a-b2a2-90b66b09468b.jpg)

**Comment by markoaamunkajo** [comment]
Reproduced

**Comment by andreevdenis** [comment]
1.5.44
Also fixed dashboard view

**Comment by markoaamunkajo** [comment]
QA passed
