### ISSUE TITLE
Request user review for app in Google Play

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#503]

**Comment by andreevdenis** [comment]
User will be asked to make a review if he use app for at least 7 days and have at least 1 sensor.

![image](https://user-images.githubusercontent.com/24788772/134395841-75d2d864-8aff-4210-8af8-2227cdeaf8a6.png)

**Comment by andreevdenis** [comment]
1.5.47

**Comment by markoaamunkajo** [comment]
Oh man did I just reinstall app instead of update... 🙄

**Comment by markoaamunkajo** [comment]
QA passed
