### ISSUE TITLE
1.5.45 Oversized font and Dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#504]
Description:

Found one glitch on dashboard with oversized font, for consideration.

https://user-images.githubusercontent.com/50437378/134188146-2cd3e492-21bc-475c-a8e1-97c31c145aa7.mp4

**Comment by andreevdenis** [comment]
@markoaamunkajo please re-check this one
Should be fixed already in #458

**Comment by markoaamunkajo** [comment]
QA passed
