### ISSUE TITLE
Display firmware version of tag in settings

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#508]
e.g. under MAC address,
```
MAC Address:       AA:BB:CC:DD:EE:FF
Firmware version: v3.30.4+default
Data Format:         5
```
Firmware version is the same as read from Device Information Service through GATT. It should be stored when logs are read, and when firmware is updated through app (not yet implemented). Maybe a button for "refresh" should be added?

[iOS version of issue](https://github.com/ruuvi/com.ruuvi.station.ios/issues/594)

**Comment by andreevdenis** [comment]
Added automatic update

**Comment by andreevdenis** [comment]
1.7.8

**Comment by markoaamunkajo** [comment]
Let's add the case for old firmware like 2.5.9:

Yeah that's a good idea. I think it could say on Android and iOS simply: "Very old" "Fin: Hyvin vanha" and because under this string there is a button to initiate updating, everyone will understand what to do.

**Comment by markoaamunkajo** [comment]
Show "very old" on df3 mode
QA passed
