### ISSUE TITLE
GATT: A non-connectable advertisement during / right after sync causes UI glitch in graphs

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#510]
Tag keeps advertising as non-connectable device during GATT connection. The tag may also send a few (1-2) non-connectable advertisements after disconnection. 

This causes graph view to switch "non-connectable tag" mode.

**Comment by andreevdenis** [comment]
1.7.15

**Comment by andreevdenis** [comment]
1.8.0

**Comment by markoaamunkajo** [comment]
Not spotted anymore, moving to done.
