### ISSUE TITLE
DFU: add timeout for case when set to bootloader and battery removed

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#517]
Description:

On DFU screen we are waiting to find sensor that is in bootloader mode. Once it's there it enables button.
But we should also have timeout and rescan for this in case user decides to exit bootloader or remove battery. On iOS this is 10 seconds if I remember correctly.

![Screenshot_20211019-164005_Ruuvi Station](https://user-images.githubusercontent.com/50437378/137892652-f1684301-783c-47a8-a3b2-6d0d9b415416.jpg)

**Comment by andreevdenis** [comment]
@markoaamunkajo can you describe it with more details? What if user remove battery after 10 second?

**Comment by markoaamunkajo** [comment]
We should also have timeout during the update. Now user has "run out of battery".
In this case we should probably stop update and show error so user understands to start the process again. Is there any danger of bricking the device at any step in the process?

![Screenshot 2021-10-22 at 10 29 22](https://user-images.githubusercontent.com/50437378/138388849-f3b8929d-52ff-4698-a791-6a3a8bc6fd32.png)
