### ISSUE TITLE
Check if it is possible to get rid of location permissions with targetSDK 31

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#521]

**Comment by andreevdenis** [comment]
@markoaamunkajo it should work like before for Android 6-11, but it's possible I did broke something. App needs a good full test.

There's no location permission request for Android 12 users.

**Comment by andreevdenis** [comment]
Currently in internal/alpha version 1.6.7

**Comment by markoaamunkajo** [comment]
QA passed, tested with OS6, OS9, OS10
