### ISSUE TITLE
DFU Issues related to updating 2.5.9 firmware

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#524]
Description:

User has 2.5.9 fw sensor and is trying to update its firmware
He goes to firmware update page, sets sensor to bootloader mode and begins update, but middle of update presses R to exit from bootloader mode and update fails.

1. If he now tries to update same sensor, it will continue from same percentage he quit at, but he will receive DFU CRC error, sensor cannot be updated anymore
2. If he now tries to update any other sensor, the process is stuck at 0% (this issue can be resolved by restarting app and trying again)

**Comment by markoaamunkajo** [comment]
@ojousima suggested that the  issue could be possibly solved by forcing the firmware update to start from beginning. It might help with these different experiences.

**Comment by andreevdenis** [comment]
I've checked again with Samsung S8. In one case I removed battery after 50% and in second case pressed R. In both cases I was able to update firmware from app. Can you re-check again?

**Comment by markoaamunkajo** [comment]
1.6.6 I have various different results trying to update 2.5.9 sensor.

Case 1. Clean install:

https://user-images.githubusercontent.com/50437378/142759373-533dc444-f8c5-433c-830b-b6fac40a13e9.mov

Case 2. Retrying after failed error:
https://user-images.githubusercontent.com/50437378/142759399-dbf80591-bcba-476b-b91c-2ba43f156f15.mov

One thing that I noticed is that if I try to reflash this sensor to 2.5.9 with nRF Connect fw upload is very slow, it's an old model sensor.

**Comment by andreevdenis** [comment]
@markoaamunkajo this should be in issue #522 
This issue was initially was about pressing R or removing battery.

**Comment by markoaamunkajo** [comment]
Tried removing battery again during fw update.

1. Reflash in nRF connect to 2.5.9
2. Clean install version  1.6.8
3. Begin firmware update, remove battery around 5%
4. Connection lost error shown, retrying firmware update
5. Firmware update starts around 5% then hops to around 2% then shows DFU CRC error

**Comment by andreevdenis** [comment]
Ok, one more try. Sensor is B7.1 with 2.5.9. Phone Samsung S9 as yours.

I've tried to press R and remove battery during update. In both cases second try was successfull.

**Comment by markoaamunkajo** [comment]
1.8.1

B7 sensor in df3 mode

Attempt 1:
Fresh install, firmware updater downloaded firmware 1.31.1 at beginning of process.
Running firmware update and removing battery from sensor in about 5% progress status. A moment later fw updater reports that update has failed. User reconnected battery to device, started firmware update again.

Actual: DFU error in about 5% progress.

Attempt 2:
Now retrying update after DFU error. Updater progress is stuck at 0% and no errors are reported, there is no timeout.

Attempt 3:
User killed app after attempt 2 and removed battery, rebooted device. Sensor in df3 mode.
In new firmware update attempt update goes to 7% and I see it stepping back to 4% and then very slowly progresses through update without any issues to 100% then seems to run again at the end from 0-100% with green led lit and reports success. Process was successful.

**Comment by markoaamunkajo** [comment]
1.8.1

User on Samsung S8 with B7 sensor with fw 2.5.9 starts firmware update process and kills app when reaching 2%. Sensor stays switches back to bootloader mode with red led.
User then restarts app and starts firmawre process again. Now progress bar is forever stuck at 2% and no progress will be made.

**Comment by andreevdenis** [comment]
Is it B7 or B7.1? I only have B6, B7.1 and B8

Not sure if this can affect somehow but I can't reproduce anything from your experience.

**Comment by markoaamunkajo** [comment]
S21,B7 sensor with 3.30.4, OS12

User updating firmware from 3.30.4 to 3.31.1 through normal update process failed at 13% with error Firmware update failed. RuuviTag stayed in updating status with green led lit.

**Comment by markoaamunkajo** [comment]
1.9.1. S8

I erased firmware on sensor, then installed 2.5.9 using Segger.
Made clean install of 1.9.1 and added this sensor only.

Disconnect still happened consistently 6 times in a row at 50%

Looking at the lights on the sensor it looks like sensor was reset at this point and after that the update fails. I hope it's visible on this video:

https://user-images.githubusercontent.com/50437378/162100497-7ff659b5-0a7f-4def-b1fa-a4845eadc88d.mp4

I also recycled between data format modes before attempting update to see if it made any difference - it didn't.

Attempt 7 was finally successful and firmware update finished as expected. Nothing was different to any other attempts. Tag was in df3 format during this attempt.

**Comment by markoaamunkajo** [comment]
1.9.1 S22

I erased firmware on sensor, then installed 2.5.9 using Segger.
Made clean install of 1.9.1 and added this sensor only. Cycled to df3 mode every time.

First 3 attempts were successful. After successful fw update I erased firmware on sensor and installed 2.5.9 using Segger.

Attempt 4 failed at 55%, sensor stayed with green led for over a minute and then changed to red.

Attempt 5-7 was again successful.

Attempt 8 failed at 65%, green led stayed lit for over a minute then changed to red. See video:

https://drive.google.com/file/d/1qxMJAe4wI8xQjhCSW7kQ2rN7U5cYNUnR/view?usp=sharing

**Comment by markoaamunkajo** [comment]
1.9.1 S22 Android 12 @andreevdenis

Method: Erased sensor with Segger and installed 3.30.4 with Segger, then updated firmware with app.
First 3 attempts were successful.
Attempt 4: update failed with error at 75%
Attempts 5-8 all successful.

No idea what happened at attempt 4.

**Comment by markoaamunkajo** [comment]
Waiting to get Segger replacement board

**Comment by markoaamunkajo** [comment]
Tested OS9 and OS 12 phones
Old and new version of RuuviTag

Normal updates
df3 mode
df5 mode
Resetting sensor with R
Removing battery
5%, 35%, 75%

All firmware uploads were successful

I think this card can be safely closed
