### ISSUE TITLE
Allow firmware downgrade (when latest released version is lesser than currently installed)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#529]

**Comment by andreevdenis** [comment]
1.6.4

**Comment by markoaamunkajo** [comment]
@andreevdenis Can I use version under Actions for this? Will it work?

**Comment by andreevdenis** [comment]
@markoaamunkajo yes, or version from Google Play internal will work too. 

Manually update sensor to 3.31.1 and then app will allow to update to latest release (v3.30.4)

**Comment by markoaamunkajo** [comment]
Perfect thanks!

**Comment by markoaamunkajo** [comment]
QA passed
