### ISSUE TITLE
Warn user before FW update if his battery level is low

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#538]
Some simple logic could be used because we know temperature of the battery

if temp is less than -20C, low battery threshold = 2V
 else if temp is less than 0C, low battery threshold = 2,3V
 else low battery threshold = 2,5V

**Comment by andreevdenis** [comment]
1.6.10

**Comment by andreevdenis** [comment]
can be tested now @markoaamunkajo

**Comment by markoaamunkajo** [comment]
QA passed.
