### ISSUE TITLE
Let's improve alert notification text.

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#544]
In the Ruuvi App the message "Temperature is too low/high" isn't very informative. 

Would it be possible to replace it with something like
"Temperature is under <low limit>/over <high limit> "?

**Comment by andreevdenis** [comment]
1.6.13

**Comment by markoaamunkajo** [comment]
Added translation strings for FI @andreevdenis

**Comment by andreevdenis** [comment]
Merged. Will include with next version.

**Comment by markoaamunkajo** [comment]
QA passed
