### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#549]

**Comment by markoaamunkajo** [comment]
Auto-update seems broken on OS10+ devices, such as Huawei Nova 5T

**Comment by jmullo** [comment]
"Select sensor" is not listing anything.

And why is it only talking about Ruuvi Gateway?

**Comment by laurijamsa** [comment]
The widgets are only for Ruuvi Cloud users (requires a Ruuvi Gateway router). You can purchase a Ruuvi Gateway here: ruuvi.com/gateway

**Comment by markoaamunkajo** [comment]
Auto-update is fixed for me in all cases when battery optimisation settings are disabled for Ruuvi Station, which is a known issue.
@laurijamsa should we add comment in documentation and close this case?

**Comment by jmullo** [comment]
> The widgets are only for Ruuvi Cloud users (requires a Ruuvi Gateway router). You can purchase a Ruuvi Gateway here: ruuvi.com/gateway

So you decided to make them 200e widgets :D No thanks.

**Comment by andreevdenis** [comment]
@markoaamunkajo in my opinion we can close this one, but also it may be helpfull to spend some time to try to reduce battery optimisation influence.

**Comment by markoaamunkajo** [comment]
Closing this issue
