### ISSUE TITLE
1.6.11 App shows double in app gallery when signed in with cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#558]
Description:

User is signed into Ruuvi cloud and after signing in checks app gallery
Actual: app shows in two versions in app gallery
Expected: show only one version

https://user-images.githubusercontent.com/50437378/146301269-b538b60f-dc7b-464d-87c2-df0f4e6c02da.mp4

**Comment by andreevdenis** [comment]
1.6.12

**Comment by markoaamunkajo** [comment]
QA passed
