### ISSUE TITLE
Return location to data forwarding

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#569]

**Comment by ojousima** [comment]
Let's follow https://docs.ruuvi.com/ruuvi-station-app/gateway as accurately as possible.

If data is not available, we could write it as 
```
"location": {
    "accuracy": undefined,
    "latitude": undefined,
    "longitude": undefined
  },
```
or undefined -> 0

**Comment by andreevdenis** [comment]
This is how currently data looks for basic sensor without pressure and humidity. Missing "pressure" field will be parsed to null value and it's completly ok for json. No need to send extra data for null. 

![image](https://user-images.githubusercontent.com/24788772/148958795-8f705328-468e-4c5b-98a1-b979c7d2323a.png)

Let's just mention in documentation that location won't be included if user opted out for this feature in settings or no location permission provided.

**Comment by andreevdenis** [comment]
New option in data forwarding settings:

![Screenshot_20220111-172227.png](https://user-images.githubusercontent.com/24788772/148960331-2080a7ed-83b9-4269-8025-858ea755cc4a.png)

**Comment by laurijamsa** [comment]
How can we know that it's ok for json parses our customers have created? It is possible that none of the old customers who are using this data forwarding feature have bought 2in1 or 3in1 sensors and they haven't noticed yet that some sensors may have no humidity and pressure fields available.

And if it would be perfectly ok to not to send null values and instead just drop the fields off from the sent json object, why do we send zero values if user hasn't configured offsets?

**Comment by andreevdenis** [comment]
Most likely customers use some 3rd party parsers for json and most of them should support this. From my experience there are no issues when value is just omitted. I get the data from our Cloud the same way. Also customer who asked about the field didn't mention that dissapeared location field crashed his server or something like that, he still getting data only without coordinates. 

Offsets initialized like 0 in app local db.

**Comment by markoaamunkajo** [comment]
Discussed in DM this doesn't work for me on S8,  OS9

**Comment by markoaamunkajo** [comment]
QA passed
