### ISSUE TITLE
Remove underline from the sensors name on the homepage and match iOS app

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station#570]
![Screenshot_20220111-125035_Ruuvi Station](https://user-images.githubusercontent.com/24395776/148938266-820f539e-f3e1-4bc1-95a8-dcc49342ad2d.png)

**Comment by ojousima** [comment]
@laurijamsa please check the UI, add underline to iOS or remove underline from Android

**Comment by laurijamsa** [comment]
Remove underline from Android. This was discussed and agreed on comments of an iOS issue

**Comment by andreevdenis** [comment]
Changing this behaviour is bloked in currently used UI components. Can't fix without serious refactoring. Can't even change indicator color to transparent - alpha chanel ignored.

**Comment by laurijamsa** [comment]
This is a duplicate with the #732, closing.
