### ISSUE TITLE
Ask user to update app to latest version

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#574]
Use this guide:
https://developer.android.com/guide/playcore/in-app-updates

**Comment by andreevdenis** [comment]
![Screenshot_20220308-111602.png](https://user-images.githubusercontent.com/24788772/157238896-8252a616-3fdb-40fe-bd59-c5f064297621.png)

![Screenshot_20220308-123339.png](https://user-images.githubusercontent.com/24788772/157238916-4f86fb85-aa99-4de8-b93a-b47da188f988.png)

**Comment by andreevdenis** [comment]
@markoaamunkajo It may be hard to check this. First you got to install app version that support this feature. Then wait till next release and it also may  require to wait additional day or two till you see dialog (at least it was the case for my phone). If user cancels update - then we'll wait for additional week to request update again.

**Comment by markoaamunkajo** [comment]
Spotted. Closing this issue.
