### ISSUE TITLE
Hide charts for missing sensors (pressure for example)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#575]

**Comment by andreevdenis** [comment]
1.7.7

**Comment by markoaamunkajo** [comment]
1.7.7 @andreevdenis looks like I cannot GATT sync this sensor. I am able to sync it on iOS.

**Comment by andreevdenis** [comment]
@markoaamunkajo maybe you got KeepCoonected enabled for iOS?

**Comment by andreevdenis** [comment]
Check again please. iPhone interfere here
![Screenshot_20220307-165839_Ruuvi Station](https://user-images.githubusercontent.com/24788772/157048272-bf66a4f4-9e9c-4403-ae65-221c2f829990.jpg)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
On second thought, let's fix the CSV export to ignore values if sensor doesn't exist.
I get mysterious readings in CSV after GATT syncing this sensor.

[Ruuvi 636A_20220309-1938.csv](https://github.com/ruuvi/com.ruuvi.station/files/8214705/Ruuvi.636A_20220309-1938.csv)

**Comment by markoaamunkajo** [comment]
Also: after GATT sync the missing sensor appeared in chart view. Let's keep it hidden.

**Comment by andreevdenis** [comment]
1.7.12

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
Reopening. I'm on 1.7.13 and I just received a couple of shared sensors from the cloud that don't have air pressure sensors on them. They both show 0,00hPa and also the graph. Should show "-" and no graph.

![image](https://user-images.githubusercontent.com/1311912/158390763-c9a71c1e-9446-44f9-aa64-3a494dabe625.png)

**Comment by andreevdenis** [comment]
Fixed. 1.7.14

Note: fix may not help right away if you already have history synced. 
So here are some options:
1) clear history
2) sign out then sign in (clears history too)
3) wait 10 days

It's not a big issue so I don't want to add extra code to overcome current behaviour.

**Comment by markoaamunkajo** [comment]
Ah it makes sense. Let's go with this solution.
