### ISSUE TITLE
Check updating FW from custom version (possible crashes)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#577]
If you try to update sensor with FW version like on pic - app will crash when trying to parse it.

![image](https://user-images.githubusercontent.com/24788772/154948718-23442115-a3a8-4c43-a815-c1dd4a562b3e.png)
![image](https://user-images.githubusercontent.com/24788772/154948836-ff5442ad-a5a0-4e32-a28b-5bb3cff8a426.png)

**Comment by andreevdenis** [comment]
[Uploading ruuvitag_b_armgcc_ruuvifw_default_bfb837c_dfu_app.zip…]()

**Comment by andreevdenis** [comment]
FW to reproduce
[ruuvitag_b_armgcc_ruuvifw_default_bfb837c_full.zip](https://github.com/ruuvi/com.ruuvi.station/files/8108763/ruuvitag_b_armgcc_ruuvifw_default_bfb837c_full.zip)

[ruuvitag_b_armgcc_ruuvifw_default_bfb837c_dfu_app.zip](https://github.com/ruuvi/com.ruuvi.station/files/8108761/ruuvitag_b_armgcc_ruuvifw_default_bfb837c_dfu_app.zip)

**Comment by andreevdenis** [comment]
1.4.6

**Comment by markoaamunkajo** [comment]
QA passed
