### ISSUE TITLE
Export CSV dissimilarities on iOS and Android 

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station#579]
I have exported CSV files from the same sensor from both iOS and Android apps and I have noticed a few dissimilarities. 

1. Column RSSI is missing on the iOS, and column TX Power is missing on the android. 
2. Android file showing floating points more than two decimal points. 

![419358cf-8e89-4ada-8308-2911e8db1647](https://user-images.githubusercontent.com/24395776/150321126-b4d2edd1-0061-40f1-8533-7c46e10f1a1a.jpeg)

3. Android exported near about 7556 rows and iOS exported 812 rows. 

[Android.csv](https://github.com/ruuvi/com.ruuvi.station/files/7904332/Android.csv)
[iOS.csv](https://github.com/ruuvi/com.ruuvi.station/files/7904333/iOS.csv)

I am not sure which is the ideal hence we need a discussion perhaps.

**Comment by ojousima** [comment]
I'm not certain if iOS can display RSSI, it might depend on sensor connection status. If iOS can display it, let's add.

Rounding should be done to resolution of data format, if that is complicated then we could pick three significant digits.

**Comment by markoaamunkajo** [comment]
QA passed
