### ISSUE TITLE
1.6.19 Chart History View period always resets to showing 10 days on cloud sensor sync

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#580]
Description:

User has few local sensors and has also signed into Ruuvi cloud and is syncing some sensors from cloud service.
He has configured Chart History View Period to 1 day in Chart Settings

Actual:
Local BT sensors charts will now show 1 days view in charts view
Cloud sensors charts view will reset to 10 days when cloud sensor data is synced

Expected:
Use local setting for charts view

**Comment by laurijamsa** [comment]
I couldn't reproduce this issue. Tried with 1 and 2 days settings.

**Comment by andreevdenis** [comment]
Looks like I've created duplicate of this task and linked fixes to it
https://github.com/ruuvi/com.ruuvi.station/issues/593
