### ISSUE TITLE
History reading gets stuck until app is closed if Bluetooth is turned off mid-read

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#587]
I was trying to reproduce https://github.com/ruuvi/ruuvi.firmware.c/issues/326 and noticed that if BLE is turned off the phone the app gets stuck in reading, no matter if I click "cancel" or re-enable BLE.
![image](https://user-images.githubusercontent.com/2360368/154294411-a5fa0f5a-475f-4ec9-b002-ec9f82d2dde9.png)

After restarting the app GATT connection works fine.

Ruuvi Station version:  v1.7.2
Ruuvi Firmware version: v3.31.1

**Comment by andreevdenis** [comment]
@markoaamunkajo can you check this? I was able at least to cancel sync on my phones.

**Comment by markoaamunkajo** [comment]
I get disconnected disabling bt
Cancel button visible during sync

QA passed
