### ISSUE TITLE
Complex widget

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#599]

**Comment by markoaamunkajo** [comment]
1.11.2 We should show value in this case of 0.000 g. There might be some cases where nul is present otherwise, there we should be using "-".

![nul](https://user-images.githubusercontent.com/50437378/169957497-22ede5fa-ffd0-4de4-8e95-41cdbed6ddda.jpg)

**Comment by markoaamunkajo** [comment]
Also I see Lauri commented for default selection under sensor to remove RSSI.

**Comment by markoaamunkajo** [comment]
@andreevdenis Could we make the widget default 4x1 to reduce amount of whitespace?

![photo_2022-06-03 12 20 20](https://user-images.githubusercontent.com/50437378/171791354-08475835-7f07-4928-9f17-2ff998cfdc1b.jpeg)
