### ISSUE TITLE
"Battery too low" even sensor doesn't report battery level

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#611]
When updating firmware that is using data format 2 or 4, battery level warning is shown even user just replaced the battery:

![image](https://user-images.githubusercontent.com/1311912/156985573-09ae80c8-e2ac-4a60-93e7-d00459b6cace.png)

Expected: do not show the battery level warning if battery level is not known.

**Comment by andreevdenis** [comment]
1.8.x

**Comment by markoaamunkajo** [comment]
QA passed
