### ISSUE TITLE
Firmware updating from a really old firmware got stuck, disconnecting battery recovered

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#612]
This user had a really old firmware, probably a Kickstarter era version because it was in low resolution URL mode according to the screenshots.

![image](https://user-images.githubusercontent.com/1311912/156986094-d43631b1-a44d-4a41-8f63-c7052c456365.png)
![image](https://user-images.githubusercontent.com/1311912/156986123-ff8efe7a-3577-4cb5-a29a-94a45e3ca343.png)

In English: 

**"1) update -> goes to 100%
2) does again 0 -> 100% and after that connection is lost and red light starts to blink 1,5s on and 0,5s off (repeat)
Removing battery recovered the sensor and after that, the firmware was up to date."**

This requires no actions before we can replicate this behaviour. If successful, try also on iOS. Assigning to Marko.

**Comment by DG12** [comment]
I just now successfully updated a SW Ruuvi 1.2.12 sensor tag via DFU   (just saying)

**Comment by ojousima** [comment]
1.X FWs do not have accurate battery measurement under load, best we can do is to ask users to change battery and try again.
