### ISSUE TITLE
Android 12 and firmwares that are broadcasting data in URL mode

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#613]
Currently, Android 12 phones cannot retrieve data from Ruuvi sensors that have old firmwares (data formats 2 and 4). This is because we decided not to ask a location permission on Android 12 and newer. Before 12 it was a requirement to scan nearby Bluetooth devices. But without this permission, sensors with really old firmwares are not visible at all. And now we occasionally get feedback from users with Android 12 saying that updating to 12 killed their Ruuvi sensors. They also cannot add the sensors in the app anymore if they've removed the sensors or the app. Only way to overcome this is to update firmwares manually using nRF Connect with these instructions: ruuvi.com/software-update 

We should come up with a solution on this and discuss what would be the best way to do it.

Option 1) Continue asking location permission also on Android 11+.
Pros: All sensors work
Cons: Allowing location permission shouldn't be needed as Ruuvi doesn't track app's location. This may make users feel unsafe.

Option 2) Show similar popups than iOS: https://github.com/ruuvi/com.ruuvi.station.ios/issues/739
Pros: Gives new features like internal history to old fw users, too
Cons: This doesn't help if someone has already updated to Android 12 and trying to add old sensors to a freshly installed app

Option 3) Do nothing and enhance support documentation

Something else? 

I think I would vote a combination of 2 and 3 at this point.

**Comment by laurijamsa** [comment]
Maybe here where user adds new sensors we could show a note (on Android 12 or newer):

![image](https://user-images.githubusercontent.com/1311912/156997007-2f4cecad-e22b-467c-8445-0ef93e98ae21.png)

"If you cannot see all your sensors, a manual update may be required. Instructions: ruuvi.com/software-update"

Another option here would be to say "If you cannot see all your sensors, give the app an additional permission to receive data also from older Ruuvi sensors. After this, please update firmware of your sensors." And if user taps this, the app would prompt the location permission dialog. This way user could use the app's DFU updating feature later on when prompted (option 2).

**Comment by andreevdenis** [comment]
Let's wait till 1.9 hits production and then send message to DF4 users via Firebase.

**Comment by laurijamsa** [comment]
They have been contacted now. Moving to backlog so that we can check back a bit later if more actions are needed.

**Comment by markoaamunkajo** [comment]
Closing this issue. We will continue showing in-app message as follows:

![inapp](https://user-images.githubusercontent.com/50437378/228433338-353f90ee-6fe1-41a3-861e-a18bae0cd357.jpg)


No feedback from users lately. We will not continue to support old firmware in app, only recommend users to update firmware by pointing them to https://ruuvi.com/software-update/
