### ISSUE TITLE
Not all simple widgets auto update

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#622]
If I create several widgets for the same sensor, only the first one is auto updating. See the timestamps:

![Screenshot_20220311-091818_One UI Home](https://user-images.githubusercontent.com/1311912/157789889-357ea19e-dfdb-4c4e-a97b-44381bc590f1.jpg)

Samsung Galaxy S21 Ultra and Android 12. App's battery optimisation is off.

**Comment by laurijamsa** [comment]
Now I'm on 1.7.14. Signed out and signed in using a different account. Then created some new widgets and noticed that none of them update automatically. Will continue testing by rebooting the phone, etc.

**Comment by laurijamsa** [comment]
After removing the widgets that were created using the previous account and after rebooting the phone, all the new widgets started to update automatically.

**Comment by andreevdenis** [comment]
For me I got situation when after turning on battery optimisation widgets stopped updating and disabling optimisation again didn't help. But after phone restart it's all working again. Checked on Pixel and Samsung S9

**Comment by laurijamsa** [comment]
I haven't been able to reproduce this lately, so closing for now.

**Comment by laurijamsa** [comment]
Now happened that my widgets jammed to "loading..." mode and refresh buttons were unreaponsive too. May be related to updating the app but because the recent updates ahpuld have not included any breaking changes to widgets, this has to be investigated more. Tried to sign in with different accounts and add widgets using both accounts but couldnt reproduce at this time. Marko, please test widgets more.

**Comment by laurijamsa** [comment]
The widgets have performed pretty well lately for me and we haven't received any user feedbacks about these issues. Closing.
