### ISSUE TITLE
Icon (gateway/BT) glitch when syncing remote sensor

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#626]
Lauri: Spotted another issue. After the first sync is completed, the Gateway icon switched to a Bluetooth icon for a second. Even this is a cloud sensor at other side ot the world.

https://user-images.githubusercontent.com/24788772/158587817-8a7c02ef-63b3-4450-a6f1-bea6f23bf392.mp4

**Comment by andreevdenis** [comment]
Can't reproduce. Can you try @markoaamunkajo?

**Comment by markoaamunkajo** [comment]
I also cannot reproduce yet. Will recheck with Android 12 device

**Comment by markoaamunkajo** [comment]
@andreevdenis I have not been able to reproduce this case.

**Comment by laurijamsa** [comment]
Tried and couldn't reproduce this time. Will try later again and if still cannot reproduce, let's close.

**Comment by andreevdenis** [comment]
This shouldn't be a thing in 2.0 version

**Comment by markoaamunkajo** [comment]
Not seen in 2.1.0
