### ISSUE TITLE
1.8.1 owner deleted sensor from Ruuvi cloud account another user claims it with masked email

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#636]
Description:

2.5.9 sensor was assigned to owner and another user tried to claim it on Android, getting error about ownership.
Original owner then signed to Ruuvi Cloud on web and Deleted sensor. Then another user claimed sensor successfully but his own email address is now shown masked with * on top of email address.

**Comment by andreevdenis** [comment]
1.8.2

**Comment by markoaamunkajo** [comment]
QA passed
