### ISSUE TITLE
Firmware update completed for cloud sensor but sensor info still reported old dataformat being used

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#637]
Description:

1.8.1
User updates B7 sensor with 2.5.9 to new 3.31.1 on Samsung S21.
This sensor is claimed to cloud and user has cloud mode active.

Firmware update is successful but after update user sees sensor being in data format 3.
This was fixed by user by switching cloud mode off momentarily. Now sensor reports being running in df5 correctly.

Can this experience be improved with minimal effort?

**Comment by andreevdenis** [comment]
Minimal effort would be just to wait for next cloud data sync a minite or two. Agree? 

And I don't think users care about data format.

**Comment by andreevdenis** [comment]
Data format in settings represent the status of latest measurement from the sensor. We should not change it manually after update. Data format will be updated with next sync.
