### ISSUE TITLE
Remove duplicate samples from the exported CSV

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station#638]
Exported CSV file of the tags contains duplicate samples. 

<img width="1899" alt="Screenshot 2022-03-24 at 10 48 04 AM" src="https://user-images.githubusercontent.com/24395776/159909229-705a62d5-fde7-4231-882a-93f37048af7e.png">

**File:** [Tag_20220324-1201.csv](https://github.com/ruuvi/com.ruuvi.station/files/8341123/Tag_20220324-1201.csv)

**Comment by andreevdenis** [comment]
The issue was with cloud sync. I was requesting data from last sync time and previously synced last point was included into new response. Now requesting from last sync time + 1 second.

**Comment by andreevdenis** [comment]
1.8.2

**Comment by priyonto** [comment]
Thank you @andreevdenis for quickly looking into it. I will check it again on 1.8.2.

**Comment by andreevdenis** [comment]
Previously synced duplicates will stay in app unless you sign out and sign in again.

**Comment by priyonto** [comment]
Yes, that's understandable.

**Comment by markoaamunkajo** [comment]
QA passed
