### ISSUE TITLE
(Unification) Ruuvi Cloud: change code text field to code boxes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#643]
Description:

Let's use code boxes for signin on Ruuvi Cloud signin page.
Basically copy the design that is used on Web.

Important: no OK button, when code filled should submit

<img width="362" alt="Screenshot 2022-03-29 at 8 13 06" src="https://user-images.githubusercontent.com/50437378/160512902-f70dfab8-7fb9-41d7-a871-3b1053b52755.png">

Card for iOS: https://github.com/ruuvi/com.ruuvi.station.ios/issues/816

**Comment by andreevdenis** [comment]
![Screenshot_20220412-120632_Ruuvi Station](https://user-images.githubusercontent.com/24788772/162924330-b01b0600-94e8-40a8-a973-fbd2226de812.jpg)

**Comment by markoaamunkajo** [comment]
1.10.0 Backspace should work for keyboard for user to jump back and clear previous codebox entry.
Maybe 1  backspace to clear 2 backspaces to jump to previous box?

**Comment by markoaamunkajo** [comment]
QA passed
