### ISSUE TITLE
Menu item: Get Ruuvi Gateway

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#645]
Description:

Add link under Get More Sensors

Link: https://ruuvi.com/gateway

Link for Get More sensors: http://ruuvi.com/products

**Comment by hakunti** [comment]
Proposal: 
Get More Sensor -> Buy Ruuvi Sensors
Get Ruuvi Gateway - Buy Ruuvi Gateway

**Comment by markoaamunkajo** [comment]
QA passed
