### ISSUE TITLE
Don't allow user to go to claim page when ownership is not his

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#655]
User adds new sensor to Ruuvi Station and tries to claim ownership, he gets error that sensor is already owned by xxx***@xx**.com
On Sensor Settings page he is still able to go to Claim Ownership page.

Expected:
When email is shown as hashed don't let user to Claim Ownership page.
![IMG_583A777F59EF-1](https://user-images.githubusercontent.com/50437378/160732962-f8550ac9-3c23-476e-845f-47c21cf62f2f.jpeg)

Card for iOS: https://github.com/ruuvi/com.ruuvi.station.ios/issues/823

**Comment by andreevdenis** [comment]
I believe this one was already implemented

**Comment by markoaamunkajo** [comment]
QA passed
