### ISSUE TITLE
Firmware update: make Android fw update work same way as on iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#656]
Description:

We tested that 3.30.4 update to 3.31.1 nordics library understands that it doesn't need to update the soft device protocol stack and on Android and iOS it goes only once and quite fast to 0-100%

BUT

On iOS when updating from 2.x to 3.x the progress bar understands that it has to go from 0-50% when updating soft device package and after that it pauses for few seconds, continues from 50-100% when updating application package.

This is the proper way to doing it, so let's do same on Android.

**Comment by markoaamunkajo** [comment]
1.9.0, S8

Updating 2.5.9 sensor firmware failed at 50% with connection lost error.
After failing looks like sensor falled back to 2.5.9 firmware.


![Screenshot_20220402-190333_Ruuvi Station](https://user-images.githubusercontent.com/50437378/161382372-90feb0b7-0c9c-4660-bde4-64206b622977.jpg)


I also see INVALID OBJECT error on some attempts and updating process fails right at the beginning in those cases.

**Comment by andreevdenis** [comment]
All the atempts were failed? Can you check if phone restart help?

**Comment by markoaamunkajo** [comment]
Restarted phone and recharged it a bit too. Makes no difference. Example video is in 2x speed.
https://user-images.githubusercontent.com/50437378/161384465-582c3d0f-79bc-4cfa-afbe-e3596bced6b5.mp4

**Comment by andreevdenis** [comment]
1.9.1

What I discovered: in some cases (60-75%) I was getting disconnect when dfu consitent in 2 parts. Added additional reconnect for these cases. I stil had GATT ERROR in 10% of attempts but stability of DFU is significantly increased.

@markoaamunkajo please try clean install and other phone. If some issues are still reproducable please describe in: 
https://github.com/ruuvi/com.ruuvi.station/issues/524

**Comment by markoaamunkajo** [comment]
1.9.1

Described update issues related to S8 in card #524 
In a nutshell: 1/7 attempts was successful.
On a positive note there were no error codes shown to me.

**Comment by markoaamunkajo** [comment]
1.9.1 @andreevdenis 

Described update issues related to S22 in card #524 
It seems this is even more inconsistent. But errors happened after 50% mark during testing. I didn't see any error codes in this case too.

**Comment by markoaamunkajo** [comment]
Will make 3.x fw update tests later

**Comment by markoaamunkajo** [comment]
1.9.1 S22 Android 12 @andreevdenis 

Method: Erased sensor with Segger and installed 3.30.4 with Segger, then updated firmware with app.
First 3 attempts were successful.
Attempt 4: update failed with error at 75%
Attempts 5-8 all successful.

No idea what happened at attempt 4.

**Comment by markoaamunkajo** [comment]
Moving this card about progress bar to done since that part seems to be working.
