### ISSUE TITLE
Firmware update instructions update

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#657]
Description:

New Firmware update strings have been updated to localization repo. Notice there is now 6 improved instruction strings.

prepare_your_sensor_instructions_1
prepare_your_sensor_instructions_2
prepare_your_sensor_instructions_3
prepare_your_sensor_instructions_4
prepare_your_sensor_instructions_5
prepare_your_sensor_instructions_6

https://github.com/ruuvi/station.localization/pull/90

RU, SV, FR, DE strings need to be updated to localization.

Card for iOS: https://github.com/ruuvi/com.ruuvi.station.ios/issues/824

**Comment by laurijamsa** [comment]
Let's add an image to help finding the button. Image location should be on above all the texts including "Prepare your sensor" title.

A zip file including transparent PNG (too large file to include in the app package) and a JPG (~300kB). You can also scale down resolution of the JPG if needed but make sure that it doesn't look blurry. When adding the image, make sure it's not too large on landscape mode.

[ruuvitag-b8-button-location.zip](https://github.com/ruuvi/com.ruuvi.station/files/8376730/ruuvitag-b8-button-location.zip)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
I have updated the PCB image. Find it here and scale down the resolution so that app package won't grow too much:

[updated-images-remember-to-scale-down.zip](https://github.com/ruuvi/com.ruuvi.station.ios/files/8417366/updated-images-remember-to-scale-down.zip)

**Comment by markoaamunkajo** [comment]
QA passed
