### ISSUE TITLE
Redesign for Charts view to make it more functional

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#675]
Description:

Discussed in meeting that we need a bit of redesign for Charts view on both Android and iOS to make it more functional and understandable.

Related cards:
https://github.com/ruuvi/com.ruuvi.station/issues/654
https://github.com/ruuvi/com.ruuvi.station.ios/issues/822

**Comment by laurijamsa** [comment]
We've decided to make the clear/sync buttons easier to understand by renaming them and also adding an export button on the graph view. UI instruction is coming.

Clear - Sync

to be:

Clear View - Download History - Export History

**Comment by sini-maaria** [comment]
Here:
<img width="778" alt="Screenshot 2022-09-22 at 11 47 58" src="https://user-images.githubusercontent.com/19531763/191703191-8181bb68-b3eb-4ccf-8b9c-9eba20e4278f.png">

"Synchronising.." text should use the same font and size as "Updated" text on the bottom.

**Comment by markoaamunkajo** [comment]
1.15.0 @andreevdenis 

Title is missing from "More..." popup
Title: Longer history
Text: Ruuvi Station mobile app supports maximum 10 days history. Ruuvi Cloud subscribers are able to view up to 2 years of historical data using web app at ruuvi.com/station (requires Ruuvi Gateway router).

Title FI: Pidempi historia
Text FI: Ruuvi Station -mobiilisovellus tukee maksimissaan 10 päivän historiaa. Ruuvi Cloud -tilaajat voivat tarkastella historiatietoja jopa 2 vuoden ajalta web-sovelluksessa osoitteessa ruuvi.com/fi/station (vaatii Ruuvi Gateway -reitittimen).

**Comment by markoaamunkajo** [comment]
1.15.5 @andreevdenis I still see old popup text in More... popup

**Comment by andreevdenis** [comment]
1.15.6

**Comment by markoaamunkajo** [comment]
QA passed
