### ISSUE TITLE
User gets alerts from missing humidity sensor

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#686]
User: today I installed the gateway and everything is ok, but it has started to send me alarm emails from a sensor tag pro that does not have humidity and sends them to me every hour, I attach screenshots to see if you know what can happen

![image](https://user-images.githubusercontent.com/24788772/167728214-0bb51352-451f-4afe-8433-6c15c43a9a8d.png)
![image](https://user-images.githubusercontent.com/24788772/167728232-b22dbc5f-f67f-491a-8c31-d6369059255b.png)
![image](https://user-images.githubusercontent.com/24788772/167728254-cc3845f3-5fad-4ed7-b1a4-a19345285e7f.png)

I think user set alert for humidity when it was possible in older app version. Alert wasn't bothering him in local mode. When we decide to hide UI for missing sensors (alerts and calibration) alert stayed in DB but was never disabled. Then it got synced to the cloud. Quick solution here should be removing and then adding sensor back.

Do we need to do something about it or just ignore because it's very rare situation?

Maybe something should be done at cloud side. Null humidity shouldn't trigger alarm (why it's 163%?)

**Comment by DG12** [comment]
Odd that 16384 decimal is x'4000' (or not)

**Comment by laurijamsa** [comment]
I think no need to do anything on the app side because this is probably a really rare situation. But should be fixed in the backend.

**Comment by andreevdenis** [comment]
Closing this if no actions needed
