### ISSUE TITLE
UI fix: Sensor settings

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#694]
![app-fixes-2022-settings-specs](https://user-images.githubusercontent.com/19531763/170473316-92bc5556-9e37-4391-a359-0ce39200acc8.jpg)

**Comment by sini-maaria** [comment]
Please note: I will confirm later the changes on alert and history section.

**Comment by sini-maaria** [comment]
Please go through the other UI fixes before this. 

I will update these sensor settings guides in the next coming days along with the general settings changes. 

Thanks.

**Comment by sini-maaria** [comment]
Final specs here: https://github.com/ruuvi/com.ruuvi.station/issues/703

**Comment by andreevdenis** [comment]
1.12.1

@markoaamunkajo Please check for style improvements from this task and #703 but not for changes in logic and significat UI remodeling. There will be separate issues for these changes.

**Comment by sini-maaria** [comment]
![app-fixes-2022-settings-small-fixes](https://user-images.githubusercontent.com/19531763/173797961-1612ecb1-5b9d-4722-8430-c89c8590abbd.jpg)

**Comment by sini-maaria** [comment]
Here is content and layout for the alert popup:

<img width="353" alt="Screenshot 2022-06-16 at 11 07 54" src="https://user-images.githubusercontent.com/19531763/174026082-0422b9c4-7089-4a43-9117-e021c21297ce.png">

**Comment by andreevdenis** [comment]
Alert popup changes will be implemented in task #711

**Comment by sini-maaria** [comment]
Check the line heights in the previous image.

**Comment by andreevdenis** [comment]
1.12.6
