### ISSUE TITLE
UI fix: Buttons

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#695]
BUTTONS
(All the buttons!)

Bg: #4bc9ba
Mulish Extrabold, 14px
line-height: 20px;
padding: 11px 25px;
min-width: 120px;
height: 42px;

<img width="826" alt="Screenshot 2022-05-26 at 14 01 20" src="https://user-images.githubusercontent.com/19531763/170475478-5abb490b-6371-4452-897d-e98281f941e1.png">

**Comment by DG12** [comment]
Gray for disabled is pretty standard.

**Comment by andreevdenis** [comment]
No need, I can repaint it. Should it be animated?

**Comment by andreevdenis** [comment]
![image](https://user-images.githubusercontent.com/24788772/172569030-f5a384fe-8fcb-4e2d-be19-95fec70e5ba6.png)
@sini-maaria  Apart from disabled style, we should define button pressed style.

**Comment by andreevdenis** [comment]
1.12.2

**Comment by sini-maaria** [comment]
Button pressed:

LIGHT
Background: #35ad9f

DARK
Background: #20746a

<img width="249" alt="Screenshot 2022-06-14 at 13 12 52" src="https://user-images.githubusercontent.com/19531763/173553596-4163a143-ae02-4f5e-8759-e83cf4be44be.png">
<img width="339" alt="Screenshot 2022-06-14 at 13 14 35" src="https://user-images.githubusercontent.com/19531763/173553888-5face8ac-12ba-4220-b41f-10c1a00a9e6a.png">

**Comment by sini-maaria** [comment]
Text is not quite in the center here:

<img width="551" alt="Screenshot 2022-06-16 at 12 28 04" src="https://user-images.githubusercontent.com/19531763/174040076-5a6fb6e5-b812-43f9-bbcb-b3a0a41581f2.png">

**Comment by sini-maaria** [comment]
Changed my mind about button disabled style. Here is a new one: 

DARK
Background: 50%
Text: #083c3d

LIGHT
Background: 50%
Text: #fff

Please, adjust also the spacing between buttons and between buttons and bottom screen according to the image.

<img width="838" alt="Screenshot 2022-06-16 at 14 44 52" src="https://user-images.githubusercontent.com/19531763/174062908-2f61e258-a05c-475a-ac19-c26e7b340bad.png">

<img width="834" alt="Screenshot 2022-06-16 at 14 44 37" src="https://user-images.githubusercontent.com/19531763/174062900-f62c05da-6ed3-45ff-a8c7-967d7837b845.png">

**Comment by sini-maaria** [comment]
Noticed that there is a mixup in colors: dark mode has light button and light mode has darker button. These should be other way around.

<img width="845" alt="Screenshot 2022-06-17 at 20 00 42" src="https://user-images.githubusercontent.com/19531763/174344296-e48556cd-abd6-4f67-b2c7-75843611f029.png">

**Comment by sini-maaria** [comment]
<img width="807" alt="Screenshot 2022-06-23 at 20 17 02" src="https://user-images.githubusercontent.com/19531763/175357094-d4dcf3ff-b3cc-4cc0-8c99-f3c3f90e37f5.png">

**Comment by sini-maaria** [comment]
Let's use the same button styles on welcome screens. Now welcome screens have two styles.

(I will also give you some new styles for these welcome screens in the next coming days. Nothing special, they should be fast to implement.)

![Screenshot_20220622-134313_Ruuvi Station](https://user-images.githubusercontent.com/19531763/175357261-a38ad169-94d9-43d0-88f7-3ec581c1e9a1.jpeg)

![Screenshot_20220622-134210_Ruuvi Station](https://user-images.githubusercontent.com/19531763/175357538-4dd70f23-cae4-4644-a4b0-8a1fa1dde7b2.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
