### ISSUE TITLE
UI fix: Fonts

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#696]
Subtitle:
Mulish Bold, 14px, line-height: 20px, #083c3d, 80%

Paragraph:
Mulish Regular, 14px, line-height: 20px, #083c3d, 80%

List style:
Circle: 7px, #4bc9ba

Paragraph “Small”:
Mulish Regular, 12px, line-height: 16px, #083c3d, 80%

Link style:
Mulish Bold,  #4bc9ba, undeline

Input:
Mulish Bold, 14px, #083c3d, 80%
Bottom border:  1px, #9dafaf

<img width="800" alt="Screenshot 2022-05-26 at 14 59 32" src="https://user-images.githubusercontent.com/19531763/170483828-f7af0ef5-29c1-4e0e-8a0d-a3666e742e7e.png">

**Comment by andreevdenis** [comment]
![Screenshot_20220602-182658.png](https://user-images.githubusercontent.com/24788772/171665590-e4dcaa4c-02ff-4c8e-8822-b8c0c73ad70a.png)

We got different style for active input.

**Comment by sini-maaria** [comment]
I will get back to that active input.

Here are some small fixes I noticed:

![Screenshot 2022-06-03 at 12 03 13](https://user-images.githubusercontent.com/19531763/171824143-02baffe5-7c8a-4957-8bed-2e9a1feda319.png)

**Comment by andreevdenis** [comment]
When user press test button he can see status messages below button:

![Screenshot_20220603-122116.png](https://user-images.githubusercontent.com/24788772/171827248-b35cf2dc-9675-407d-a312-d390eb962bf2.png)
![Screenshot_20220603-121955.png](https://user-images.githubusercontent.com/24788772/171827278-600fac48-68b9-4b4c-9efb-fde1e2fcf888.png)
![Screenshot_20220603-122132.png](https://user-images.githubusercontent.com/24788772/171827320-bf83bca2-884e-4d35-be2e-7fda7d924e8e.png)

**Comment by sini-maaria** [comment]
Mulish SemiBold Italic, 14px

![Screenshot 2022-06-08 at 9 06 02](https://user-images.githubusercontent.com/19531763/172543623-c8c4341b-f61a-4732-9a83-d17486f9a1fc.png)

**Comment by sini-maaria** [comment]
![Screenshot 2022-06-15 at 10 35 58](https://user-images.githubusercontent.com/19531763/173770128-43b9ccbf-77e3-4ba7-8c6b-95bc904615b0.png)
