### ISSUE TITLE
Make it possible to configure how accurately measurements are shown on the sensor card

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#697]
Often it's not important to know temperature, humidity and air pressure in 0.01 decimal resolution and we should allow users to decide if they would like to see the measurements in the live sensor card (and dashboard) in 0.01, 0.1 or 1 accuracy.

Make a new global app setting, a similar selection that temp/humi/pressure units currently have. Round the values like we normally do in the app (0.45 -> 0.5, 0,44 -> 0,4). Localise the decimal pointer ./, according user's language setting. Sync this setting to the cloud.

**Measurement Resolution**
======================

(*) 0.01
( ) 0.1
( ) 1

Select how accurately you'd like to see sensors' live measurement values in the app. This setting doesn't affect history graphs or alerts.

iOS issue: https://github.com/ruuvi/com.ruuvi.station.ios/issues/935

**Comment by andreevdenis** [comment]
Do I understand correctly that one setting will affect temperature, humidity and pressure at once?

What if we do this separately for each type of value? Current temperature unit settings screen will inlude also accuracy and the same will be for humidity and pressure. This doesn't sounds too hard to implement.

**Comment by laurijamsa** [comment]
That is a good idea, I like it.

**Comment by markoaamunkajo** [comment]
1.13.1

In description text please refer to "charts" and not graphs. We previously unified to use word "charts" everywhere in the app.
![charts_not_graphs](https://user-images.githubusercontent.com/50437378/180917951-3afa690d-47f2-4c25-b42a-16731b27b687.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
