### ISSUE TITLE
UI fix: Settings, subpages, popup / Light & dark

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#703]
LIGHT
Bg: #fff
Bg top: #083c3d
Bg accordion: #35ad9f , 25%
Bg accordion alerts: #fff, and alerts title #35ad9f, 15%
Button and icons: #4bc9ba
Lines: #e5eae9

Orange: #f48021, 80%

DARK
Bg: #001d1b
Bg top and accordion: #083c3d
Bg accordion alerts: #083c3d, 50%
Button and icons: #35ad9f
Lines: #e5eae9, 10%

![app-fixes-2022](https://user-images.githubusercontent.com/19531763/172354685-2cdac289-3dc9-439a-9d96-fee9805ec472.jpg)

**Comment by laurijamsa** [comment]
We need to have it manually editable, same way as it works in the station.ruuvi.com web ui. It is too hard to adjust especially air pressure levels accurately with the slider. Also, one may woyld like to put alert to let's say 20,5C and not 20C or 21C. Manual editing allows this already in thr web ui.
