### ISSUE TITLE
Incorrect restore of a sensor list from the Cloud for users without Gateway

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#704]
Probably there is an error in logic for restoring sensors from the Cloud in a case when user has no Gateway. Sensor is added to main list but no history is getting saved and the same sensor can be seen in "Add a new sensor" screen

**Comment by andreevdenis** [comment]
1.11.5

**Comment by markoaamunkajo** [comment]
QA passed
