### ISSUE TITLE
Changes to App Settings

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#710]
Change how app settings list looks like

![image](https://user-images.githubusercontent.com/24788772/173430678-75bcb70a-0d95-4d4f-89e6-68661f866127.png)
![image](https://user-images.githubusercontent.com/24788772/173430710-21ed8ee4-7462-4f05-ac11-11869a527e88.png)

Based on task #703

**Comment by markoaamunkajo** [comment]
QA passed
