### ISSUE TITLE
Changes to alert settings

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#711]
![image](https://user-images.githubusercontent.com/24788772/173431490-ed810416-ba97-4dbf-a47b-194649c5dadf.png)

Based on task #703 

@sini-maaria please describe how dialog should look like when user press pencil icon here
![image](https://user-images.githubusercontent.com/24788772/173431756-de847d47-0281-4b15-8bb2-37b524ef863c.png)

**Comment by sini-maaria** [comment]
On light theme, could you change the blue behind titles (General, Alerts..) to #d6eae7. Now the blue seems brighter than in my design.

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like alerts are not respecting localization or resolution.
I'm using Finnish locale and should be seeing , as separator.
Also, I set resolution to 2 decimals but I am not able to use this in alert settings.

![Resolution-set](https://user-images.githubusercontent.com/50437378/192423100-30ff4718-5446-46d7-95c4-26925035b218.jpg)
![Alert-range-set](https://user-images.githubusercontent.com/50437378/192423106-ef62df8c-d129-4a09-a07a-b169f18214ea.jpg)

**Comment by andreevdenis** [comment]
Agree about localization. But having 0,01 accuracy will get us into trouble with convertion from F to C. I think 0,1 accuracy will be enougth taking actual sensor accuracy into consideration.

**Comment by andreevdenis** [comment]
1.14.5

**Comment by markoaamunkajo** [comment]
1.14.6

@andreevdenis looks like for some reason the Alert is not triggered in app OR in dev web app for RSSI. But I do get email about triggered RSSI alert.

![rssi_notrigger](https://user-images.githubusercontent.com/50437378/194739007-e5e48b79-7ae6-45b0-a6f7-f0179d79285b.jpg)
<img width="645" alt="Screenshot 2022-10-09 at 12 04 01" src="https://user-images.githubusercontent.com/50437378/194739010-57275200-c9ec-4655-a7c7-0587aa13b6f4.png">
<img width="253" alt="Screenshot 2022-10-09 at 12 04 20" src="https://user-images.githubusercontent.com/50437378/194739012-df2a1570-e9e7-494c-9ea9-4edff1ebae21.png">

**Comment by andreevdenis** [comment]
Alert with notification will appear in app if you receiving BT advertisments. For remote sensors you only get emails. I checked latest version with local and remote sensors and it's working as expected for me. 

Is cloud mode enabled maybe?

**Comment by andreevdenis** [comment]
I'd say this one is very minor bug so let's fix it with next milestone.

**Comment by markoaamunkajo** [comment]
Agreed

**Comment by markoaamunkajo** [comment]
QA passed
