### ISSUE TITLE
Battery indicator in sensor settings changes

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#712]
![image](https://user-images.githubusercontent.com/24788772/173432198-771f4ca6-3f84-4c33-8018-c1f9ab7e2995.png)

Screenshot from web
![image](https://user-images.githubusercontent.com/24788772/173432847-a3a8ea83-bf75-4d91-aa33-358d3bd1058e.png)

Based on #703

**Comment by sini-maaria** [comment]
Good idea. We can use the dark orange (error color).

**Comment by DG12** [comment]
I previously mentioned that the arrangement of the items in Sensor settings (which is actually more than just settings) should show dynamic data like temperature, X,Y,Z, battery voltage before static items like offset correction, MAC address, data format Issue#373.

Now that battery replacement has been added it seems even more important to re arrange the items.

A better location for the warning indicator would be next to the alarm bell shown as a depleted battery icon for example: 
![image](https://user-images.githubusercontent.com/2365961/174070663-bf324f13-9ecb-4c70-b16a-f355295561a0.png)

**Comment by markoaamunkajo** [comment]
This issue was resolved in 2.0
