### ISSUE TITLE
UI fix: Dashboard small changes

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#719]
![Screenshot 2022-06-15 at 10 18 54](https://user-images.githubusercontent.com/19531763/173766865-23ad59d8-4253-41d1-b1b6-a03d42838de6.png)

**Comment by sini-maaria** [comment]
![Screenshot 2022-06-17 at 9 46 21](https://user-images.githubusercontent.com/19531763/174241454-e60f7808-f7b2-42eb-9daf-020c153c1c4c.png)

**Comment by andreevdenis** [comment]
Titles are already centered vertically - "android style centered". I can take a look at this problem later.

**Comment by andreevdenis** [comment]
1.12.6

**Comment by sini-maaria** [comment]
Something weird is happening with the icon opacity. When I first opened the app, "alert off" icon was 50%, but now it is again 100%.

**Comment by andreevdenis** [comment]
I noticed it too. I will try to investigate this today.

**Comment by sini-maaria** [comment]
Circle colors for the dashboard which work in both themes. (These are also a general button color and button hover color.)

First circle:
Buttons and icons aqua: #35AD9F

Second circle:
Buttons hover aqua: #1F9385

![Screenshot 2022-06-21 at 12 44 59](https://user-images.githubusercontent.com/19531763/174770456-15117813-dbbd-48ec-b461-24ce6b9e9cd6.png)
![Screenshot 2022-06-21 at 12 44 03](https://user-images.githubusercontent.com/19531763/174770446-b2a351f9-dcbf-44b5-bdac-a25d83e1e425.png)
