### ISSUE TITLE
UI fix: Export history

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#720]
This icon on top header is unclear. Let's add this feature to the end of the settings list (before "Remove").

Lauri will write the subpage text content.

<img width="577" alt="Screenshot 2022-06-15 at 12 30 16" src="https://user-images.githubusercontent.com/19531763/173794584-6ce91287-0b44-43db-a532-3e18c7162d21.png">

**Comment by sini-maaria** [comment]
Icon is better on iOS. But still, you can't really tell what will be exported, unless there is an explanation on subpage.

**Comment by laurijamsa** [comment]
Closing this one, a new instruction will be coming soon.
