### ISSUE TITLE
UI fix: Alert section small changes

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#729]
If we won't make the big changes yet, let's at least make the current section a bit prettier.

I added paddings, popup for custom description and the slider has smaller circle and thinner line. Slider has also the new icon color.

![Screenshot 2022-06-17 at 10 41 14](https://user-images.githubusercontent.com/19531763/174250566-4017a014-6654-42d8-a0b7-960f1b7dbae9.png)

**Comment by sini-maaria** [comment]
Alert custom description = Aseta hälytysviesti

Please try to fix the circles as well.

**Comment by andreevdenis** [comment]
Changing thumb (circle) size is impossible with current library we are using. Also it supports appliing drawable on top of the circle but for some reason not vector drawables. It's possible to make changes to original library like we do with Chart library, but I think we better should invest time into rewriting the whole UI here with different library after finishing first iteration of redesigning.

**Comment by sini-maaria** [comment]
Ok, that's fine.

**Comment by sini-maaria** [comment]
Sorry, could you still add this. Then it is quite good. :)

<img width="563" alt="Screenshot 2022-06-21 at 12 09 25" src="https://user-images.githubusercontent.com/19531763/174762756-a17fc9c9-0793-47a1-b5cf-a921a8f967e2.png">

**Comment by andreevdenis** [comment]
Sure

**Comment by sini-maaria** [comment]
<img width="559" alt="Screenshot 2022-06-21 at 12 12 12" src="https://user-images.githubusercontent.com/19531763/174763403-5b8caeb6-ec56-47a6-aa04-7ba7e7e983ac.png">

**Comment by sini-maaria** [comment]
Fix line color here:
![Screenshot_20220626-194229_Ruuvi Station](https://user-images.githubusercontent.com/19531763/175825806-7055481f-1cbf-4b2b-b74b-f358c54de443.jpg)
