### ISSUE TITLE
UI fix: Change title typography on sensor view

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#732]
- Title style is the same as on settings page. Add space on top of the title row.
- Leave out the underline. (At least I would like to see if it is better without the line.)

<img width="754" alt="Screenshot 2022-06-21 at 20 10 14" src="https://user-images.githubusercontent.com/19531763/174858497-9f0b0262-4181-4090-bdde-4e88370ffded.png">

**Comment by laurijamsa** [comment]
I think we discussed about this some months ago and the conclusion was that our current ui libraries don't allow us to easily change this so we decided to keep it as it is for now. Moving to backlog.

**Comment by markoaamunkajo** [comment]
@sini-maaria is this card still valid?
Looks like in 2.0 the title has already been changed. Should we do this on Android asap?

**Comment by markoaamunkajo** [comment]
We will do the title formatting capital letter, small letters
Remove the underline
But keep the same location of title height-wise, we will not bring title down

**Comment by markoaamunkajo** [comment]
QA passed
