### ISSUE TITLE
Light Theme: menu top is grey

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#739]
Description:

In Dark Theme menu top is black
But in Light Theme menu top is grey, it would probably be more consistent if if used same dark as in the top bar area is used (under battery level indicator)

![289030209_1049391909114976_561848166550665709_n](https://user-images.githubusercontent.com/50437378/176985226-c2cd23f2-9160-4e63-a6a4-f72ce3a16441.jpg)

**Comment by andreevdenis** [comment]
![photo_2022-07-03_13-54-07](https://user-images.githubusercontent.com/24788772/177036353-1989cfd4-2901-4393-9e35-31c427cf7583.jpg)
As you can see here status bar is dark and transparent. Everything is looking darker under it. In your case white menu looks gray under status bar.
