### ISSUE TITLE
Android: The Great CSV Export Unification

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#745]
Description:

Unify CSV export format same as attached file.
Notice there is no filename row on sheet
Notice added units in parenthesis (g) (movements) (dBm)
Notice no value = empty field

[Ruuvi 636A_20220704-1817.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/9039577/Ruuvi.636A_20220704-1817.csv)

**Comment by markoaamunkajo** [comment]
1.13.5 Example CSV file is showing dBm value with single digit when there is no decimals

![Android_dBm](https://user-images.githubusercontent.com/50437378/185788085-a040c227-3671-491a-9047-23e7f3c8524a.jpg)

**Comment by andreevdenis** [comment]
1.13.6

**Comment by markoaamunkajo** [comment]
1.13.6

Please show empty field when no value instead of "null" or "0".

[Ruuvi 636A_20220829-0900.csv](https://github.com/ruuvi/com.ruuvi.station/files/9441052/Ruuvi.636A_20220829-0900.csv)

**Comment by andreevdenis** [comment]
1.13.7

**Comment by markoaamunkajo** [comment]
Last fix:
I added fix for FI string in 2 locations
https://github.com/ruuvi/station.localization/pull/102

Mittajärjestysnumero -> Mittausjärjestysnumero

**Comment by andreevdenis** [comment]
@markoaamunkajo can be checked with 1.14.2

**Comment by markoaamunkajo** [comment]
QA passed
