### ISSUE TITLE
Add "What to measure with Ruuvi?" link on the menu

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#746]
Add a similar link than the buy sensors and buy Gateway links are currently. This link should be before the other two links.

String in English: "What to measure with Ruuvi?"
String in Finnish: "Mitä mitata Ruuvilla?"

Link URL if app language is **something else than Finnish**: https://ruuvi.com/ideas/

Link URL if app language is Finnish: https://ruuvi.com/fi/ideat/

**Comment by markoaamunkajo** [comment]
@andreevdenis I already see this string on iOS for Swedish language, let's add it.

Vad ska man mäta med Ruuvi?

**Comment by markoaamunkajo** [comment]
QA passed
