### ISSUE TITLE
Gateway test sends event datetime in incorrect format

### ISSUE THREAD

**Issue by ankallio** [ruuvi/com.ruuvi.station#75]
The gateway test button sends a mostly empty event to the configured gateway URL. It contains the current time, but it is sometimes sent in incorrect format "Aug 19, 2019 11:27:19".

This likely happens if the test is run before the Http class initialises Ion defaults with a Gson instance with the correct datetime format. I can open the app, quickly open Settings and execute the gateway test, and it sends the incorrect format every time. After a minute or so (probably after the background service has uploaded a real event with Http) the gateway test starts to send in correct format.

I noticed this as our receiving server responds with an error code if the time is incorrect format.

One fix would be to initialise Ion and Gson in RuuviScannerApplication.onCreate() instead of in Http.

**Comment by laurijamsa** [comment]
@andreevdenis is this still relevant?

**Comment by markoaamunkajo** [comment]
QA passed
