### ISSUE TITLE
Xiaomi device keep asking for location even after it was granted

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#767]
![image](https://user-images.githubusercontent.com/24788772/183462069-37483499-c2c9-4a45-84cd-134bba4f4a61.png)

**Comment by andreevdenis** [comment]
Issue can be reproduced with version 1.13.4 on device without GPS.

**Comment by andreevdenis** [comment]
@markoaamunkajo if you don't have such device at least check how it works on your other devices. I've checked on mine devices -  works as expected.

**Comment by markoaamunkajo** [comment]
Tested 3 devices without issues detected but mine are unfortunately ones with GPS no Xiaomi in my setup.
