### ISSUE TITLE
humidity over 100% indicates error; display of humidity should be suppressed

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#77]
Most recent version of firmware i.e. 2.5.7 will report 120% if compensated value from humidity sensor returns a value greater than 120%.

( // Cap maximum reported value to 120% 
 	v_x1_u32r = (v_x1_u32r > 503316480 ? 503316480 : v_x1_u32r);
//note that 503316480 is 120 shifted left 12 then 10 bits for a return in 22.10 fixed point integer format
Actually any value over 99% is incorrect.
I would like to suggest either:

Suppress / dim display of humidity when value received is >99% ( really 100% doesn't even make sense and that was a previous value returned if value was greater than 100%)
Display the previous value

**Comment by ojousima** [comment]
Sending values over 100% is intentional. Even if the value does not make sense from physical point of view it allows compensating linear offsets. For example a sensor known to show +10 % can be calibrated from 105 % to 95 %.

**Comment by DG12** [comment]
This issue is not regarding transmission, rather the display.
Displaying a value over 100% discredits the app (as well as the tag)

**Comment by ojousima** [comment]
Reopening for discussion. @io53 @rinat-enikeev @laurijamsa your comments?

**Comment by laurijamsa** [comment]
Yes, I agree that no bigger than 100% values should be shown on Ruuvi Station (iOS/Android) even the data format allows >100% values. @io53 @rinat-enikeev let's cut to max 100% on the apps.

**Comment by laurijamsa** [comment]
I believe that this is not something to be fixed. Right, @andreevdenis ?

**Comment by andreevdenis** [comment]
Should be fixed already
