### ISSUE TITLE
Highlight the alerting value as WebUI does

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#772]

**Comment by ojousima** [comment]
See also: https://feedback.ruuvi.com/posts/99/sensor-settings-page-for-alerting-sensor-should-highlight-offending-alert

**Comment by andreevdenis** [comment]
I think we already implemented this one. With new collapsable design it's hard to scroll to alarms but we got a blinkiung bell for "offending" alert. @laurijamsa what do you think?

**Comment by laurijamsa** [comment]
Yeah, no need for actions right now. We're aiming to add a highlight color on the the upcoming dashboard new layout too. Closing this one.
