### ISSUE TITLE
Display cutouts

### ISSUE THREAD

**Issue by Scrin** [ruuvi/com.ruuvi.station#775]
It seems there is no proper support for display cutouts, or at least I couldn't find references to it in the code (or if there is support, there are some bugs).

For example, when I have a long list of tags and I scroll to the bottom of the list of tags in the "default list view", I can't properly see the last updated time (the one that says "4s ago" etc) of the bottom most tag since my phone (OnePlus Nord) has rounded corners and the bottom right rounded corner cuts out half of this text

![image](https://user-images.githubusercontent.com/6617316/187205052-07f4ab33-588a-4119-b5bb-28c348ed6015.png)

**Comment by andreevdenis** [comment]
Hey! What is your option for system navigation? I use geastures and this type of navigation still have some space occupied at the bottom of the screen.

![image](https://user-images.githubusercontent.com/24788772/187208039-d222f94a-baf3-4f4f-bc35-6e4760ecec27.png)

And on another phone: 
![image](https://user-images.githubusercontent.com/24788772/187208166-14dbb999-7a51-43b1-acce-7f0227eaedd2.png)

**Comment by Scrin** [comment]
I use gestures with the hidden bottom bar. If I either unhide the bottom bar or disable gestures, I get similar results as your first image, since the bottom bar or navigation buttons adds some "extra padding" to the bottom

**Comment by markoaamunkajo** [comment]
@Scrin Please check this on 2.0, looks like gestures or other types are fitting on my screen so closing this case.

**Comment by Scrin** [comment]
The new layout of the list view in 2.x resolves this issue. However I did notice that if I open a tag (by tapping on it from this view), the small bluetooth/gateway icon on the bottom right gets partially cut out, but that's a very minor issue since the icon is still easily recognizable. For comparison, the humidity, pressure and movement counter displays on bottom left of this view have no issue, since they are not placed to the absolute bottom of the view.
