### ISSUE TITLE
chart does not include   sync clear buttons

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#776]
chart does not include   sync clear buttons

![image](https://user-images.githubusercontent.com/2365961/188479537-778dca39-a1ae-4f35-8098-7159a67f7025.png)

**Comment by DG12** [comment]
Whoops , now it does ??
![image](https://user-images.githubusercontent.com/2365961/188481175-0fa6361d-41b5-431a-bfb9-37b2d5f3d582.png)

**Comment by andreevdenis** [comment]
Most likely this particular sensor is connected to your iOS device. 

Other options: 
 - Firmware of this sensor does not support syncing
 - this sensor is out of range and you getting measurements via Ruuvi Cloud

**Comment by andreevdenis** [comment]
Also syncing sensor with another phone will make sensor look as non connectable to other devices.

**Comment by DG12** [comment]
No other phone was syncing that time.  Notice a few minutes later, less than the screen shot indicates.

**Comment by DG12** [comment]
﻿
IOS station supports sync to this tag. But see recent related 
iOS  issue

**Comment by markoaamunkajo** [comment]
This is added in 2.0
