### ISSUE TITLE
Chart select baseline points incorrectly 01:00 instead 00:00

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#778]
Can't reproduce on my phone

![photo_2022-09-07_23-40-20](https://user-images.githubusercontent.com/24788772/188974625-1387acd9-5abe-4085-bf74-ac0bbaa23fcb.jpg)

**Comment by DG12** [comment]
Is this what you mean?
I don't understand the problem.
![image](https://user-images.githubusercontent.com/2365961/189391326-e3bd385e-7d39-4e23-bec8-37af0ab2c18c.png)

Version 1.13.7 English (United States)

Single digit day should be 0 filled. Example. 9/1 should be 9/01

**Comment by andreevdenis** [comment]
@DG12 it's better to have X axis point on midnight than on 1AM.

**Comment by andreevdenis** [comment]
The problem was with daylight saving. It's fixed now but I wonder how chart will look on the edge of time changing (few days after switching to winter time).

**Comment by andreevdenis** [comment]
1.14.3

**Comment by markoaamunkajo** [comment]
QA passed
