### ISSUE TITLE
"to replace" should be "replacing" - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#780]
Better English 
firmware update/ 
Sensor's battery voltage seems to be low... 
We recommend **replacing** the battery

**Comment by laurijamsa** [comment]
We have a separate repository for the strings that are used on Android, iOS and web UI. You can either create pull requests to the dev branch or open issues on that repo. We're soon planning to proofread all the strings and these kinds of small oddnesses will be fixed during the proofread. Closing this issue.

https://github.com/ruuvi/station.localization/blob/dev/station.localization.json
