### ISSUE TITLE
Investigate bg image cropping

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#781]
![image](https://user-images.githubusercontent.com/24788772/190407451-09eb573e-5c95-41a4-8921-5e65fffe82a0.png)![image](https://user-images.githubusercontent.com/24788772/190407214-74892a91-f597-4956-bd7e-213ffd2b92a7.png)

Lauri: I did some testing and seems that the cropping happens on the image itself, not afterwards when aligned on the screen. When I take a photo on ios app and it syncs to android, all looks ok. Please test too and lets create an issue. We've also discussed that in the future photos can be cropped to 1:2 aspect ratio

**Comment by andreevdenis** [comment]
Decided to disable cropping of original image. From now on image will be resized to width of 1080p (height can be different to keep original aspect rate).

**Comment by markoaamunkajo** [comment]
QA passed, it works for me as expected even with panoramic pictures
