### ISSUE TITLE
Redesign sensor settings

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#786]
![image](https://user-images.githubusercontent.com/24788772/191305429-f66e5d6d-ee6c-4857-bd6d-056a207acaeb.png)
Convert current groups of items in sensor settings into expandable containers. (except General)

**Comment by markoaamunkajo** [comment]
@andreevdenis I see (except General) in description, but was Alerts also intended to be left open?

**Comment by andreevdenis** [comment]
@markoaamunkajo yes

![image](https://user-images.githubusercontent.com/24788772/192483452-ecde008a-0c6e-4d28-8c76-938ea1dcb693.png)

**Comment by markoaamunkajo** [comment]
@andreevdenis app crashing for me when accessing sensor settings page
Samsung S8 OS9.

**Comment by DG12** [comment]
@markoaamunkajo my Galaxy S9 with android 9  
station 1.13.7 , 18361 measurements, 2.772KB database is GOOD

**Comment by markoaamunkajo** [comment]
1.14.6

Calibration settings should also respect localization or "," separator


![calib_finnish](https://user-images.githubusercontent.com/50437378/194739389-e722f041-76cd-4ee4-a78e-b45d5903197d.jpg)

**Comment by andreevdenis** [comment]
How this connected to this issue? I fixed this anyway..

**Comment by markoaamunkajo** [comment]
QA passed
