### ISSUE TITLE
Graph view changes (font, temperature text alignment..)

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#787]
1. Change font to Mulish Regular on graph view
2. Add padding to temperature text and make it the same size as numbers
3. Add current temperature/humidity/pressure

<img width="774" alt="Screenshot 2022-09-21 at 11 53 48" src="https://user-images.githubusercontent.com/19531763/191460786-6e10726e-23af-430d-bc2f-287623091a51.png">

**Comment by markoaamunkajo** [comment]
@andreevdenis Date is not fitting in the reserved space with new font
![Screenshot_20220927-102157_Ruuvi Station](https://user-images.githubusercontent.com/50437378/192424518-4eac5a3c-70ed-4932-8fd6-0553e34b2d42.jpg)

**Comment by andreevdenis** [comment]
Max font size on my phone


![Screenshot_20220927-121307.png](https://user-images.githubusercontent.com/24788772/192485989-ac537d6b-5839-47f6-9124-751a0e7980fd.png)

**Comment by andreevdenis** [comment]
I've increased space for captions and it should be fine for case above. But Samsungs have possibility to set font size to insane level so please don't go there ;)

**Comment by andreevdenis** [comment]
1.14.5

**Comment by markoaamunkajo** [comment]
1.14.5 @andreevdenis 
![Screenshot_20221004-165644_Ruuvi Station](https://user-images.githubusercontent.com/50437378/193791382-669d98ff-e7a3-4ee1-baf4-f45abc9046f0.jpg)

**Comment by DG12** [comment]
Parentheses around last value seem unnecessary.

Is 12:00 AM same as 00:00 ? 
is 24hour time an option? 

hh:mm_AM (i.e. space after mm)  should be between values
`12:00AM_12:00AM_ 12:00AM`

IMHO day is nicer zero padded i.e.  10/01.
Y axis for humidity should always be nn.n. i.e. 29 should be 29.0 .

**Comment by DG12** [comment]
Is beta version available?

**Comment by andreevdenis** [comment]
@DG12 it's in internal testing for now but soon it should go to alpha testing.

**Comment by markoaamunkajo** [comment]
Discussed, looks like the AM PM 12h time is not going to work in charts.
Instead, we should always use 24h and override the system setting.

Let's also see that 24h is used elsewhere, like in Data Forwarding.

**Comment by markoaamunkajo** [comment]
QA passed
