### ISSUE TITLE
Change graph view background layer opacity

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#788]
From 001D1B, 30 % to 001D1B, 80 %.

No other changes from this image.

<img width="772" alt="Screenshot 2022-09-21 at 12 30 10" src="https://user-images.githubusercontent.com/19531763/191469709-63c67751-9a9e-4a4e-b289-300281580e57.png">

**Comment by markoaamunkajo** [comment]
QA passed
