### ISSUE TITLE
UI change to Bluetooth/Gateway connection text on card view

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#789]
Make the text and icon smaller and place them on the same row.

<img width="818" alt="Screenshot 2022-09-22 at 11 54 48" src="https://user-images.githubusercontent.com/19531763/191703676-b4b5c965-17a7-4c21-b0db-79d3cab5a1e3.png">

**Comment by sini-maaria** [comment]
Icons should take the same space so that the text won't jump.

**Comment by sini-maaria** [comment]
<img width="280" alt="Screenshot 2022-09-22 at 11 58 56" src="https://user-images.githubusercontent.com/19531763/191704578-d44afdb4-01c4-4fc1-b3f7-c95858854b95.png">

**Comment by markoaamunkajo** [comment]
QA passed
