### ISSUE TITLE
New fill and line color for graphs

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#790]
fill: #46cab9, 0.3
line: #34ad9f

<img width="774" alt="Screenshot 2022-09-23 at 11 12 19" src="https://user-images.githubusercontent.com/19531763/191918319-3917a8c9-9f95-491e-8165-6fabdf05d207.png">

**Comment by markoaamunkajo** [comment]
Leaving this to @sini-maaria
