### ISSUE TITLE
Several settings options: entering data,  keypad obscures OK - 1.14.6

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#803]
Before keyboard popup:

![image](https://user-images.githubusercontent.com/2365961/194685576-bae1b85f-51e9-4ceb-8b81-270dc902fab2.png)

After. (Clicking [done] does not hide keyboard and reveal. [OK]

![image](https://user-images.githubusercontent.com/2365961/194685532-b3a38208-5000-41f5-9392-f75822e303b8.png)

**Comment by laurijamsa** [comment]
Confirmed. Another thing: when I go to edit manually a value that is for example -40 C degrees, it shows -40.00. The decimals are redundant here and would be better to not show them if they are zeros. Meaning, -40 should show -40 on the edit line and -39.5 should show -39.5 and not -39.50.

**Comment by DG12** [comment]
Naming has same problem

![image](https://user-images.githubusercontent.com/2365961/194718882-176adfe6-57c4-442d-b87f-f90b2cfd975c.png)

**Comment by markoaamunkajo** [comment]
QA passed
