### ISSUE TITLE
Bluetooth Layer Review

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station#81]
How to decouple app from the BT-related code so that community can build own apps on top of Ruuvi Android library?

**Comment by rinat-enikeev** [comment]
I can say that steps for iOS are: 

1. add https://github.com/rinat-enikeev/BTKit as a dependency to the project (either cocoa pods or SPM). 
2. call 
`BTForeground.shared.scan(self) { (observer, device) in
                             if let ruuviTag = device.ruuvi?.tag {
                                 print(ruuviTag)
                             }
                         }`

Result: you can print out values from Ruuvi Devices and do whatever you want with them.

**Comment by laurijamsa** [comment]
What's up with this issue? Any actions needed? @rinat-enikeev
