### ISSUE TITLE
Show cursor value by long tap on screen

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#817]
Description:

Webui supports dragging mouse over chart and showing precise values under chart area as "Time and value".

Let's implement this to iOS and Android apps for showing precise timestamp and values when long tap on screen.
Example: Time 15:32:14 Temperature (20 °C)

![cursor_time_value](https://user-images.githubusercontent.com/50437378/195970872-f0cbe780-6181-4b04-9bfa-9d0025c5b4c5.jpg)

Web implementation:
<img width="477" alt="Screenshot 2022-10-15 at 12 36 58" src="https://user-images.githubusercontent.com/50437378/195970802-0500e64f-e865-4146-a55d-ae966d2e893b.png">

https://user-images.githubusercontent.com/50437378/195970586-c8eddcb2-93ee-4a59-a980-1c4b287ed360.mov

**Comment by markoaamunkajo** [comment]
1.15.5 @andreevdenis I have difficulties using the cursor when I'm zoomed in on chart view. For example I set chart to show 2 days and when I'm zoomed out I can use the cursor easily, but when I zoom in to 15 min intervals and have a cursor set I am now unable to move the cursor anymore.

**Comment by andreevdenis** [comment]
If you zoomed in you can simply tap to change cursor position. But keep in mind that cursor can't be set somewhere in the middle between point. If you tap in the middle between of two points - the closest point will be selected.

**Comment by laurijamsa** [comment]
Hmm. I had to ask Denis how to move the cursor and Marko had to ask Denis how to move the cursor. It's 100% of the users who have given feedback so far I think :) Chances that other app users cannot understand how to move the cursor are pretty high. How could we make this better?

**Comment by andreevdenis** [comment]
Initial plan was to set cursor by long tap, curently it's even easier - just a tap. When chart is zoomed out we can use super nice selection by swyping back and forth. But when you zoomed in it's imposible to use same selection - we just don't know if user wants to select value or drag timeline. We could add some sort of switch that will change modes between selection and draggin but it might be an overcomplication. 

Also we could try to use different method for selection or draggin - using 2 fingers at once, for example. But since it's not supported by charts library it might be difficult and time consuming to implement.

**Comment by andreevdenis** [comment]
As simple solution we can show one time popup describing how to select a value.

**Comment by laurijamsa** [comment]
Or we could just disable the cursor value feature if zoom level is not 1:1 🤔  But maybe better to leave it like this for now.

**Comment by markoaamunkajo** [comment]
As a gesture I would maybe see if double-tapping on top of chart would enable/disable cursor mode, unless this is already reserved for something like zoom?

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
So far we've received one user feedback about this update. The user told that it's not always (when he has zoomed in) clear of what day is shown. Maybe adding date on here would solve this:

![image](https://user-images.githubusercontent.com/1311912/202370860-fc2ef5f3-1e7c-4a34-abed-b97bd3730950.png)

**Comment by markoaamunkajo** [comment]
This version feels much more intuitive to use. QA passed.
