### ISSUE TITLE
Alerts: Snoozing alert from notifications showing in sensor settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#818]
Description:

In previous version I was able to snooze triggered alert from notification drawer and it would show alert is snoozed (until time) in sensor settings. This doesn't exist in the new UI version, let's bring it back.

**Comment by andreevdenis** [comment]
![Screenshot_20221019-141528.png](https://user-images.githubusercontent.com/24788772/196676493-7b35f082-5f10-4053-9e28-c2fbf2a3b190.png)

**Comment by andreevdenis** [comment]
@sini-maaria what do you think about this solution?

**Comment by markoaamunkajo** [comment]
1.15.2 @andreevdenis 

I don't see snoozing timer after setting 1h snooze for alert in notifications drawer. Tried by adding local sensor, set temperature alert, minimized app and waited in notification screen, alert notification was triggered and then snoozed it for 1 hour and saved.


![snoozenotext](https://user-images.githubusercontent.com/50437378/197926714-10faf78d-9fc0-4270-8851-568bac70f2f3.jpg)

**Comment by markoaamunkajo** [comment]
I admit it... I used another "Snooze" feature I found in OS9.
Now retested my using "Mute for 1 hour" button in notification and it muted notifications for specific alert as expected.

QA passed.
