### ISSUE TITLE
Sound Alerts

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#819]
Description:

We will use custom alert sound in Ruuvi App to be played when alert is triggered in app.

1. Add "Sound Settings"  menu item to main menu under Alert Notifications
- Links to the system app notification page

2. Alert sound will be played when
- Alert is triggered via Bluetooth or push notification and app is in background

Sound file: (m4a format)
[ruuvi_speak_16bit_stereo.m4a.zip](https://github.com/ruuvi/com.ruuvi.station.ios/files/9791342/ruuvi_speak_16bit_stereo.m4a.zip)

Settings to be added under App Settings:

New App Settings menu item "Alert Notifications" and Sound Settings item to link to system app notification page.

Defaults:
Use sound (default: enabled)
Use vibration (default: enabled)

![Alert_Notifications_page1](https://user-images.githubusercontent.com/50437378/228132032-e15fdb42-9b8f-45f9-9afa-896b91898f3c.jpg)

Hide Email Alert and Push Alert will be handled on another card, not in this task.

![Alert_Notifications_page2](https://user-images.githubusercontent.com/50437378/228132075-a117b663-4276-49ee-a73f-c1b122a60be5.jpg)

**Comment by andreevdenis** [comment]
I did as we discussed during the meeting with Marko. No special page in settings, no override for silent mode. Current users might need to reinstall the app to hear new sound. Refactored the code to use same code base for local alerts and for pushes. These changes are not yet merged to 2.1. If something goes wrong we can rollback. Please test local alerts and pushes to decide if we include it to 2.1 or not.

**Comment by markoaamunkajo** [comment]
@andreevdenis seems like alert sound is only played once for sensor in my tests. I am not sure if this is the correct way, I think it should play again when alert is triggered.

**Comment by markoaamunkajo** [comment]
@andreevdenis 

S10+
When testing sounds in do not disturb mode, I am able to get vibration alert always.
When comparing with for example Facebook Messenger it is muting both sound and vibration.

S21 Ultra
When testing sounds in do not disturb mode, I will get visual notification + vibration alert in do not disturb mode.

We should be able to make sound and vibration muted and visual alert (Lauri's phone) off when in do not disturb mode?
We are not making do not disturb override right now.

**Comment by markoaamunkajo** [comment]
@andreevdenis please fix the design on the settings page same way as in the below example:

- Move arrow in same line with title
- More space between title and text
- Fix text colour

![example_fix_text_arrow_and_spacing](https://user-images.githubusercontent.com/50437378/228726855-1695d575-f443-4192-8fbb-8e4fea9d5988.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
