### ISSUE TITLE
occasional BTkit: device is not connectable

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#82]
After receiving advertisements from  for several minutes, last seqnum=401, 
Error BTkit: device is not connectable
pop up appears.
No addition error code is available.

version 0.4(42)
Firmware : longlife_75c03cb 12/17/19  Dec 17, 2019 3:09:11 PM

**Comment by rinat-enikeev** [comment]
@DG12 this is Android repo. Anyway, the issue was fixed here https://github.com/rinat-enikeev/BTKit/commit/a62fd621e2e5edab3894fddc2d49bfbd2a358b41
