### ISSUE TITLE
Support basic auth in the Ruuvi gateway URL

### ISSUE THREAD

**Issue by sergioisidoro** [ruuvi/com.ruuvi.station#83]
During this weekend I made a small side project ( [Here](https://github.com/sergioisidoro/ruuvi-gateway)) for a gateway for the Ruuvi app to push things to database backends. 

I gave it the ability to allow for basic_auth, but the app doesn't seem to support it by adding the user and pass in the url as such: `https://user:pass@url/path`

**Comment by laurijamsa** [comment]
Thanks and sorry that this issue hasn't been replied. Closing. Feel free to open new ones any time if you spot issues on the app.
