### ISSUE TITLE
Implement My Ruuvi Account page similar to iOS

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#835]

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Wow was almost too soon to pass this.

1.16.1 S8

I signed in to Ruuvi Cloud, it synced my sensor cards to the app and then logged out. All cards were removed.
But then I added 1 new local sensor card and I received some extra cards that were originally coming from cloud.
Looks like switching dashboard on or off doesn't affect this.

**Comment by markoaamunkajo** [comment]
@andreevdenis reproduced, related to sync being in progress like you mentioned. Will open new card for that and closing this one.
