### ISSUE TITLE
Clear view button doesn't always clear the view

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#838]
https://user-images.githubusercontent.com/1311912/198185578-ddd818b2-1ee3-49c5-a04a-f69023c4048e.mp4

**Comment by DG12** [comment]
I believe there is a design conflict in station in general.
Clearing the app history works (usually) however if tag it owned via gateway, once in gateway range prior history is downloaded.

I would suggest that in addition to clearing the data (a user settable) "marker" (earlist_time_to_chart) be set which station preserves. Any data before that "marker" is not displayed in the chart. User could "unclear" by nullifying  this as well as set to a different value which would be very helpful if the tag is moved to a different , unrelated location. This would be necessary when min, average, max are implemented.

**Comment by laurijamsa** [comment]
> I would suggest that in addition to clearing the data (a user settable) "marker" (earlist_time_to_chart) be set which Station preserves. Any data before that "marker" is not displayed in the chart. The user could "unclear" the Markey by nullifying it as well as setting it to a different value. This would be very helpful if the tag is moved to a different , unrelated location. This would be necessary when min, average, max are implemented.

Please post this suggestion to https://f.ruuvi.com/c/r/feature-requests-voting/66 if you think it's important. This issue is about fixing the clear view button :)

**Comment by andreevdenis** [comment]
1.15.4

**Comment by markoaamunkajo** [comment]
QA passed
