### ISSUE TITLE
24h dense data is not downloaded from the cloud

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#839]
Only latest 15 minutes of dense data (with 1min interval) is downloaded from the cloud. Should be 24h.

https://user-images.githubusercontent.com/1311912/198185578-ddd818b2-1ee3-49c5-a04a-f69023c4048e.mp4

Cloud has all the data (1min interval) when I check 1 day data from the web ui.

**Comment by andreevdenis** [comment]
Server side issue:
https://github.com/ruuvi/ruuvi.cloud.js/issues/46

**Comment by DG12** [comment]
What should the like be?
https://github.com/ruuvi/ruuvi.cloud.js/issues/46. <- 404

**Comment by andreevdenis** [comment]
@DG12 it's the link to a private repo issue

**Comment by andreevdenis** [comment]
Should be ok now.

**Comment by markoaamunkajo** [comment]
QA passed
