### ISSUE TITLE
Support contesting sensor ownership (deadline 6th Dec 2022)

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#840]
Users should have a "Force claim" button that lets them claim ownership of a sensor they have physical access to. 
Api proposal is documented here: https://docs.ruuvi.com/communication/cloud/user-api#contest-ownership-of-a-sensor-proposal Plan is to implement the API on second half of November on Cloud side. 

The sector can be read from Device information service over GATT after button press or NFC scan:
![image](https://user-images.githubusercontent.com/2360368/198219618-79204272-cfad-497b-a782-941017d5b884.png)

The secret should be stored in the app, since the secret can be used for fully buttonless firmware updates.
The task should be ready by beginning of December for security audit.

**Comment by markoaamunkajo** [comment]
Description:

User sees sensor that has been already claimed by someone else. Show arrow in every case when owner is someone else than logged in user, including if someone shared this sensor to you.

![Other_owner](https://user-images.githubusercontent.com/50437378/201008074-2a08b015-3bb1-46a6-9465-f0dc6fabf6ee.jpg)

Force Claim page 1:
-------------------

![Force_Claim_1](https://user-images.githubusercontent.com/50437378/201008118-7495b1b1-8516-4fb4-b3e6-b062d7e06ad6.jpg)

ENGLISH:

Page Title: Force Claim Sensor

This sensor has been claimed by another user.
You can force ownership to your account if you have physical access to this sensor. Every Ruuvi sensor can have only one owner.

Button: Force Claim

FINNISH:

Page Title: Vaihda omistajuus

Tällä anturilla on jo toinen omistaja.
Omistajuus voidaan vaihtaa pakotetusti, mikäli anturi on lähettyvilläsi. Jokaisella Ruuvi-anturilla voi olla vain yksi omistaja.

Button: Vaadi omistajuutta


Force Claim page 2:
-------------------

![Force_Claim_2](https://user-images.githubusercontent.com/50437378/201010295-5da9d805-ec03-411b-b0c1-7b2e1c96d317.jpg)


ENGLISH:

Page Title: Force Claim Sensor

Force Claim is done by using Near-Field Communication (NFC). Make sure NFC is enabled on your mobile device.

1. Touch your Ruuvi sensor with your mobile device to start the claiming process.
2. When successfully claimed you will be forwarded back to Sensor Settings.

If claiming was unsuccessful or NFC is not available on your device:

1. Open the cover of your Ruuvi sensor.
2. Locate round black button (or button B in case your sensor has 2 buttons) on white circuit board and press it briefly to start the claiming process.
3. When successfully claimed you will be forwarded back to Sensor Settings.

FINNISH:

Omistajuuden pakotettu vaihtaminen tapahtuu Near-Field Communication (NFC) ominaisuutta käyttämällä. Varmista että NFC on käytössä mobiililaitteessasi.

1. Aloita omistajuuden pakotettu vaihto koskettamalla Ruuvi-anturia mobiililaitteellasi.
2. Sinut siirretään takaisin Asetukset-sivulle onnistuneen vaihdon päätteeksi.

Mikäli pakotettu vaihto epäonnistui tai NFC-ominaisuutta ei ole saatavilla mobiililaitteessasi.

1. Avaa Ruuvi-anturin suojakotelo.
2. Paikanna valkoisella piirilevyllä oleva pieni musta painike (tai painike "B", mikäli anturissasi on 2 painiketta) ja napauta painiketta lyhyesti pakotetun vaihdon aloittamiseksi.
3. Sinut siirretään takaisin Asetukset-sivulle onnistuneen vaihdon päätteeksi.

---

User is shown his account email address as Owner on Sensor Settings page when forced claim was successful.

![After_Force_Claim](https://user-images.githubusercontent.com/50437378/201010480-7ea186da-1e10-4f85-8088-cb45b50ee4a1.jpg)

**Comment by markoaamunkajo** [comment]
@andreevdenis Please see the designs above

**Comment by andreevdenis** [comment]
Should be implemented before December 9.

**Comment by markoaamunkajo** [comment]
QA passed
Note for @ojousima @laurijamsa in the future if sensor was shared to others by previous owner should they receive email about sensor sharing was ended? Now it just bluntly disappears.

**Comment by ojousima** [comment]
>  if sensor was shared to others by previous owner should they receive email about sensor sharing was ended? 

Yes, if there is no email it's a bug on cloud end. I opened an issue on cloud side
