### ISSUE TITLE
Fonts on the graph view are too small on tablets

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#844]
This is a user feedback. He says that after a recent update, fonts got smaller and even if he adjusts system font size, the fonts remain too small to read.

Let's test and modify the sizes if the fonts really are too small.

Screenshots from the user:

![Screenshot_20221029-083527](https://user-images.githubusercontent.com/1311912/198863444-be2be79e-5ddc-4735-9fe5-c3ca6d52d9d8.png)
![Screenshot_20221029-080211](https://user-images.githubusercontent.com/1311912/198863446-39ce6acf-edbf-47d5-adc2-47432a33e9ac.jpg)
![Screenshot_20221029-080810](https://user-images.githubusercontent.com/1311912/198863447-c0cb65f8-fc8c-430c-a0da-06196223ca3a.jpg)

**Comment by andreevdenis** [comment]
Improved font size for tablets
![IMG_20221031_141559_edit_34530000730666](https://user-images.githubusercontent.com/24788772/198996266-930e8d85-8d89-40b9-a303-6cdd74c0d44c.jpg)

**Comment by andreevdenis** [comment]
1.15.4

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
Reopening. User has a tablet and 1.15.8 and fonts are really tiny and system font size setting doesn't help enough. Device is a Huawei Android tablet.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1311912/204169313-626b105a-8bc8-48fd-bf01-ff48c434bc78.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1311912/204169399-3a9a55f0-9f64-4b21-8925-96f5331d8954.png">

**Comment by andreevdenis** [comment]
@laurijamsa please request a model of tablet also.

**Comment by laurijamsa** [comment]
It's a Huawei MediaPad T8 8" 16 GB LTE. But user didn't confirm yet if he is using the latest app version for sure. I will update this once confirmed.

**Comment by andreevdenis** [comment]
In my opinion everything is working as expected. Default font size on tablet is x2 from font on phone. Both devices support increasing font size from global settings.

Phone:
![image](https://user-images.githubusercontent.com/24788772/222730780-84cf27fa-54dd-4d9b-af00-61684dac0970.png)
![image](https://user-images.githubusercontent.com/24788772/222730806-b46db451-ff52-4983-9f00-5355974edd63.png)


Tablet: 
![image](https://user-images.githubusercontent.com/24788772/222730890-481f7b23-7f04-488c-8386-edef8181a71e.png)
![image](https://user-images.githubusercontent.com/24788772/222730960-33e23f2c-72fa-4bf9-9ceb-5018e5cff471.png)

For some users it still will be too small.
But it's possible that we incorrectly identify tablet as phone. Possible for 8inch Huawei. If user is ok with installing Ruuvi Station apk with some diagnostic measurements I can provide this apk.

**Comment by markoaamunkajo** [comment]
@laurijamsa Do you think user would be ok with special apk for improving the app?

**Comment by markoaamunkajo** [comment]
Waiting to acquire tablet device for testing

**Comment by markoaamunkajo** [comment]
Tried this on counterfeit Samsung Tab, here are the results:


Second smallest font:
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/ee7aa649-e001-41f0-b54b-c7ea1ef1739e)

Largest font:
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/97f8248c-cd4f-4564-8a5b-4e9909b9d657)

**Comment by markoaamunkajo** [comment]
I have no trouble reading the screen now using default font size. I reckon it can be an issue for someone but can always turn the large font size on and it doesn't break the app in any of the views.

**Comment by andreevdenis** [comment]
![Image](https://github.com/user-attachments/assets/171e2ea2-7679-419d-98b9-2d37d67ae1d4)

**Comment by markoaamunkajo** [comment]
Texts are not fitting on screen in latest build in my old Galaxy Tab.

![Image](https://github.com/user-attachments/assets/0f474460-4d35-4bca-ab3f-b5efdb3917a4)
![Image](https://github.com/user-attachments/assets/e941fe5e-18ed-4ef1-9abd-b6df3aba6abc)
![Image](https://github.com/user-attachments/assets/7b5ee99c-fd2e-4cf7-8dd4-0baf555c19f0)

**Comment by andreevdenis** [comment]
How dasboard connected to this task? It was like this before. Screen has it's limits and extra big font will make some info cut out

@markoaamunkajo

**Comment by markoaamunkajo** [comment]
@andreevdenis Not very worried about text cutting I think it's understandable in this case, but the hPa cutting is sticking out a bit.
Well, small tablet issues all of them.

**Comment by markoaamunkajo** [comment]
QA passed
