### ISSUE TITLE
Small fixes on sensor naming popup

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#848]
- Capital first letter should be offered automatically.
- Popup goes behind the keypad.
- There is too much padding on input field (too much space between the name and line)

![b7012747-b3a6-49dc-bd56-7375df47ec9a](https://user-images.githubusercontent.com/19531763/199199916-00be8523-39cc-4dd5-a532-d44569cf1126.jpeg)

**Comment by andreevdenis** [comment]
> * Capital first letter should be offered automatically.
Easy fix. Will be included to 1.15


> * Popup goes behind the keypad.
> * There is too much padding on input field (too much space between the name and line)

Will try to implement with 1.16 milestone. This will require migration to freshier version of Compose (and Kotlin version as well).

**Comment by markoaamunkajo** [comment]
Let's include this in 2.1

**Comment by andreevdenis** [comment]
Changes will affect all the places where we use text input:
![image](https://user-images.githubusercontent.com/24788772/222796596-f8b65d34-2d48-482c-bd60-ed001d94bc32.png)
![image](https://user-images.githubusercontent.com/24788772/222796627-724a127b-c605-40d7-9846-0680739e9817.png)
![image](https://user-images.githubusercontent.com/24788772/222796646-7d0e80ad-5e64-4d1b-a6ee-f580783ad413.png)

**Comment by markoaamunkajo** [comment]
QA passed
