### ISSUE TITLE
Pressure resolution setting affects to humidity if RuuviTag has no pressure sensor

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#849]
This is a user feedback (thanks Jari!). I personally haven't tried to replicate the issue.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1311912/199207581-9dc78db2-5887-46b5-abd8-9455e30261c4.png">

**Comment by andreevdenis** [comment]
I've checked this one. It's already fixed in 1.15.4

**Comment by markoaamunkajo** [comment]
QA passed
