### ISSUE TITLE
Add details of where to find the latest firmware to the about/help section

### ISSUE THREAD

**Issue by nullr0ute** [ruuvi/com.ruuvi.station#85]
A link to where to find the latest firmware in the About/Help section of the app would be useful to be able to quickly find the latest firmware and how to update it.

**Comment by laurijamsa** [comment]
This is a good point, thanks! Actually, we're also aiming to have firmware updating integrated on the app relatively soon.

**Comment by andreevdenis** [comment]
Do we need it since we adding DFU update into app? @laurijamsa

**Comment by andreevdenis** [comment]
Closing because updating FW will be part of the app 
https://github.com/ruuvi/com.ruuvi.station/issues/410
