### ISSUE TITLE
1.15.5 Charts values overlapping and some hPa values not fitting

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#852]
Description:

Samsung S8

Some zoom levels X/Y values clashing in UI
hPa values not fitting on charts view 

![Screenshot_20221103-082600_Ruuvi Station](https://user-images.githubusercontent.com/50437378/199632705-4c7c463e-11fd-43a6-85d4-b7986e015b52.jpg)
![Screenshot_20221103-082734_Ruuvi Station](https://user-images.githubusercontent.com/50437378/199632726-f7c8766e-7251-4be0-9dc9-d17a1d4fd683.jpg)

**Comment by andreevdenis** [comment]
1.15.6

**Comment by markoaamunkajo** [comment]
QA passed
