### ISSUE TITLE
New dashboard layout

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#854]
![Screenshot 2022-11-03 at 14 30 56](https://user-images.githubusercontent.com/19531763/199720865-a05d981c-835c-4115-9fc2-a41fed99f0be.png)

**Comment by andreevdenis** [comment]
Full image view is the same as sensor card now?

**Comment by laurijamsa** [comment]
> Full image view is the same as sensor card now?

yeah, no modifications on the sensor card view (full image view)

**Comment by laurijamsa** [comment]
One spec that is missing I see is that where to forward user if he/she taps any of these areas (after custom background is set):

![image](https://user-images.githubusercontent.com/1311912/199725010-9109b9a2-4fd9-4d9c-84db-02475b7b7165.png)

I think it should forward to the current sensor card view (full image view) for now just like it's doing on the old dashboard.

**Comment by andreevdenis** [comment]
Do we have plans to modify sensor card? If so I suggest to specify changes now and implement changes to dashboard and sensor card at the same time because these two are connected.

**Comment by laurijamsa** [comment]
> no modifications on the sensor card view (full image view)

We agreed with S-M that sensor card will stay untouched for now.

**Comment by laurijamsa** [comment]
Suggestion:

Add "Change Background" option under the 3 dots dropdown menu. It can be the lowest one under the settings&alerts.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/1311912/201452813-aa3f4ce1-ec35-4454-b548-772671037109.png">

**Comment by markoaamunkajo** [comment]
@andreevdenis remember to add the placeholder text and link to Nearby Ruuvi sensors page to this view (same as in previous version) when no sensors are added yet

![Screenshot_20221125-084323_Ruuvi Station](https://user-images.githubusercontent.com/50437378/203883832-ca0aa54b-69ab-4548-aa55-3d3bd791e498.jpg)

**Comment by sini-maaria** [comment]
1. Some changes to "Image view" cards:
*  Cards' height can vary and image area stretch
* Small measurements' color: #fff with 80% opacity

2. Let's add "Simple view"
3. Add "View" menu with dropdown

(These cards are designed with an additional setting on Sensor Settings where user can select "Sensor Priority", but let's design the default cards first with four default sensors.)

<img width="698" alt="Screenshot 2022-11-28 at 14 14 34" src="https://user-images.githubusercontent.com/19531763/204275466-81420aad-c368-4b64-af5c-352a5cd17f64.png">

**Comment by andreevdenis** [comment]
@sini-maaria There was a good point in our Telegram channel about showing Voltage in card. Maybe we shouldn't show it all the time but instead show some low battery icon when voltage is low.

**Comment by laurijamsa** [comment]
> There was a good point in our Telegram channel about showing Voltage in card. Maybe we shouldn't show it all the time but instead show some low battery icon when voltage is low.

Yes, battery voltage shouldn't be shown on the mobile by default. The layout examples had it just as an example. We are planning to make the cards more customisable later.

**Comment by sini-maaria** [comment]
There are two things which will help the situation when we’d like to see as many sensors as possible at the same time.
1. Let’s hide the header when scrolling down. It should come back when user scrolls up.
2. Bottom menu could be transparent, same kind as on sensor page.

**Comment by DG12** [comment]
@andreevdenis can you please provide a link to 
"Telegram channel about showing Voltage in card."

**Comment by andreevdenis** [comment]
@DG12 https://t.me/ruuvicom/12592

**Comment by markoaamunkajo** [comment]
@laurijamsa How does one add a new sensor with the new view selector at top right corner? Bring also the "+" icon to top row?

**Comment by laurijamsa** [comment]
Let's forget the + icon for now. New sensors can be added from the menu.

**Comment by sini-maaria** [comment]
Remove Battery here:

<img width="339" alt="Screenshot 2022-12-21 at 12 33 04" src="https://user-images.githubusercontent.com/19531763/208885831-ec9a56c6-ae16-4eba-ab4e-fdfd48ec2d3f.png">

Use the same arrow as on the Settings page:

<img width="749" alt="Screenshot 2022-12-21 at 12 32 45" src="https://user-images.githubusercontent.com/19531763/208885797-7540eb9d-51f8-48e2-a524-b3ba2eda71c3.png">

Align the dropdown menu with he cards and arrow icon with the 3-dots on the cards:

<img width="372" alt="Screenshot 2022-12-21 at 12 37 13" src="https://user-images.githubusercontent.com/19531763/208885840-4405d17b-ed11-42ea-a9e5-7ae765e3cd22.png">

(Original design)
<img width="291" alt="Screenshot 2022-12-21 at 12 41 01" src="https://user-images.githubusercontent.com/19531763/208886285-95d5a6cd-d86b-49fb-89e5-73823ca7b3ed.png">

**Comment by sini-maaria** [comment]
<img width="1097" alt="Screenshot 2022-12-29 at 9 48 47" src="https://user-images.githubusercontent.com/19531763/209920593-4b76bc6c-49b5-474b-ad85-c1cff0ab4105.png">

**Comment by sini-maaria** [comment]
An other note: "4 s ago" and "Low battery" should be transparent, 50% #fff.

**Comment by sini-maaria** [comment]
Add more space under the title. It seems too tight.

<img width="929" alt="Screenshot 2022-12-29 at 11 44 32" src="https://user-images.githubusercontent.com/19531763/209933513-3d0c07ef-c83d-4cb1-a2ef-74e641b11bf7.png">

**Comment by sini-maaria** [comment]
Alert icon could be tiny bit smaller. The smaller size should be updated to alert settings page as well.

<img width="371" alt="Screenshot 2022-12-29 at 11 42 05" src="https://user-images.githubusercontent.com/19531763/209933768-aa05974d-5bf9-47c1-b0f0-e407202c25b0.png">

Here:
<img width="376" alt="Screenshot 2022-12-29 at 11 47 55" src="https://user-images.githubusercontent.com/19531763/209933859-85b37030-e27a-43b1-bef5-805fa4b2581e.png">

**Comment by sini-maaria** [comment]
About the transparent layer on top of dashboard images. They should be:
- On dark theme: 75% 
- On light theme: 30%

Now they seem to be the same:
<img width="591" alt="Screenshot 2022-12-29 at 12 08 05" src="https://user-images.githubusercontent.com/19531763/209936302-e6df0d78-a0cb-45d7-aa7d-077213eaa827.png">

**Comment by markoaamunkajo** [comment]
https://github.com/ruuvi/com.ruuvi.station/issues/906

**Comment by markoaamunkajo** [comment]
QA passed
