### ISSUE TITLE
Inform user when his token gets expired

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#858]
Based on user report from forum: https://f.ruuvi.com/t/ruuvi-station-android-updates/4262/56

Currently if users token gets exprired app just silently stops syncing with the Cloud and user don't understand what is the reason and gets confused. 

We should detect this situation and show some message to user with some actions (for example ignore or re-login). Let's discuss it during next meeting.

**Comment by andreevdenis** [comment]
Implemented simple behavior: when we receive ER_UNAUTHORIZED from cloud during sync -> app will sing off and open sign in screen.

**Comment by andreevdenis** [comment]
@markoaamunkajo to test this ask Otso to delete your latest used token from the cloud db.

**Comment by laurijamsa** [comment]
Guys, just a reminder, that let's remember to make sure that we have similar ticket on iOS so that this kind of an underlying feature that we won't notice when testing other features on iOS won't remain unimplemented for too long.

**Comment by markoaamunkajo** [comment]
@andreevdenis 1.16.1 I asked Otso to remove my token for user, in app I see that I cannot add new sensors to cloud but I was not signed out and no message was shown.

**Comment by andreevdenis** [comment]
@markoaamunkajo Probably it's because this behaviour is not implemented in new dashboard yet. Will return to this when I have time.

**Comment by andreevdenis** [comment]
Fixed. You should be in dashboard or sensor card during sync atempt. No message will be shown, just redirect to sign in screen.

**Comment by markoaamunkajo** [comment]
QA passed
