### ISSUE TITLE
Charts: BT sync icon replacement to make it more clear for user

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#873]
Description:

Some users are reporting they are not finding the sync button on new charts view.
Let's try to redesign this button.

**Comment by markoaamunkajo** [comment]
Some ideas
![sync4](https://user-images.githubusercontent.com/50437378/203884852-5ba480a1-40e4-452a-8ea1-6a390fecb429.jpg)
![sync3](https://user-images.githubusercontent.com/50437378/203884862-0764ea88-c4ef-4be8-a4c0-fa260a76377b.jpg)
![sync2](https://user-images.githubusercontent.com/50437378/203884865-069672ed-2d62-4408-9c47-95b5d64fc567.jpg)
![sync1](https://user-images.githubusercontent.com/50437378/203884867-0f87e747-28e5-430e-8128-028aff4872b2.jpg)

**Comment by sini-maaria** [comment]
Change "update icon" to "synchronise icon" and add text "Sync" next to it. ("Synkronoi" in Finnish)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Reopened this case, we received user feedback about the sync and we added card to show Bluetooth download popup only first time when syncing.

So this icon should be redesigned too.

**Comment by sini-maaria** [comment]
Here is an idea you can discuss with Lauri:

![Screenshot 2023-03-22 at 11 58 21](https://user-images.githubusercontent.com/19531763/226868649-68eeb658-1129-4036-900c-f760f9efe34a.png)

**Comment by markoaamunkajo** [comment]
@sini-maaria we reconsidered the text a bit with Lauri.
We would still like to change the sync icon on this page next to "Sync" text. Could you have some ideas regarding this?

![sync_fi](https://user-images.githubusercontent.com/50437378/227092234-0811475c-4905-495d-95b7-7108bfc2a8d3.png)

**Comment by markoaamunkajo** [comment]
Synchronisation

Ruuvi Station downloads the internal history of the sensor for the last 10 days if the measurement history is available.
The history is downloaded using a Bluetooth connection. Make sure you are near the sensor.

Don't show this again
Close

**Comment by markoaamunkajo** [comment]
2.2.0

@andreevdenis Looks like "don't show again" still shows it on the next card next time I do it. But not on the third anymore.

https://user-images.githubusercontent.com/50437378/231636587-54c3dc4e-17c5-43e3-b76c-0ff78d37ac85.mp4

**Comment by markoaamunkajo** [comment]
@andreevdenis I think the new sync icon is slightly too much to the left. Compare it with X button when sync is on.



![Image](https://user-images.githubusercontent.com/50437378/232959817-4997ce93-b7bb-4026-b988-2fa4cbce3b43.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
