### ISSUE TITLE
New dashboard: compact view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#874]
Description:

New dashboard layout will also have a more compact view where sensor images are hidden

Show new menu item in 3 dots menu which will be named according to currently selected view:

Show images
Use compact view

![photo_2022-11-25 08 51 37](https://user-images.githubusercontent.com/50437378/203885105-c3ec7237-1a89-4d7f-bfea-d68538dfdefd.jpeg)

**Comment by laurijamsa** [comment]
It's specified here: https://github.com/ruuvi/com.ruuvi.station/issues/854#issuecomment-1328986552

**Comment by markoaamunkajo** [comment]
Discussing this card at https://github.com/ruuvi/com.ruuvi.station/issues/854

**Comment by markoaamunkajo** [comment]
QA passed
