### ISSUE TITLE
New dashboard: remember selected view setting and defaults

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#876]
Description:

Related to #854 and #874 

Dashboard will be enabled always for all users, the setting to enable or disable Dashboard in app settings will be removed.

1. Dashboard showing images enabled will be set as the new default view for all Ruuvi Station installations (both old and new users). When user adds a sensor he will be forwarded to full sensor settings view, then when he chooses back button he will land to full sensor card view. Dashboard will be accessed using the left arrow on full sensor card view.
2. Compact view or show images view should be remembered in Ruuvi Cloud.
3. User was on dashboard view, then killed app, reopening app will remember to open in dashboard view including compact view or images view that was selected previously. If user was on full card view the app will remember this view on reopening.

**Comment by andreevdenis** [comment]
During meeting we've decided to not implement: If user was on full card view the app will remember this view on reopening.

We may return to this in future.

**Comment by markoaamunkajo** [comment]
QA passed, discussing add new sensor feature in main card
