### ISSUE TITLE
Numbers on unique code cannot be entered using a special keyboard

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#878]
When tried to sign in, user received a code that contained a number: ABC1. He was able to enter ABC without problems but the number couldn't be entered. He told he's using a custom keyboard: https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard

So he requested a new code and got one without a number on it -> now all went well.

**Comment by markoaamunkajo** [comment]
Latest app update in in Play Store: 26.11.2018
This app is not supported anymore. Cannot be installed on Android 13 and tested.
