### ISSUE TITLE
Alert popup layout

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#879]
- Remove padding on the input field: left side and on the bottom of the text
- Add "auto focus" to the field

![aaaScreenshot_20221128-091026_Ruuvi Station](https://user-images.githubusercontent.com/19531763/204216151-052ccdfc-0d78-419b-9274-03d0b594264e.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
