### ISSUE TITLE
File name for export could be better (enhancement)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#88]
File name for export should be shorter and include the tag name like tagName-yymmdd-hhmm
Most significant units first, cc unnecessary , ss also unnecessary.
Current name MM:MM:MM:MM:MM:MM:_nnnnnnnnnnnnnnnn_MMMMMMMM is very awkward.

**Comment by laurijamsa** [comment]
@andreevdenis is this something that has been updated already? Need to also make sure that Android/iOS export formats are consistent now and in the future.

**Comment by andreevdenis** [comment]
@laurijamsa Filename in Android version is the same as described in issue. iOS filename is: Ruuvi {Last 4 letters from tag MAC}-{Timestamp in format:YYMMDD-hhmm}.csv We can implement the same as in iOS or think about something better. Maybe we should include full sensor mac in filename?

**Comment by DG12** [comment]
IOS version 06.6.1(18) is now  tagname-yymmdd-hhmm.csv

**Comment by andreevdenis** [comment]
@DG12 you're right about iOS filename. Why closed? Nothing changed in android version since this issue was openned

**Comment by DG12** [comment]
Oops. I didn't notice that this was for android. I thought it was IOS and I had forgotten to close it.

**Comment by markoaamunkajo** [comment]
QA passed build 1.4.1
