### ISSUE TITLE
Bluetooth history downloading doesn't work for longer history if user downloaded shorter history first

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#881]
Reproduce:

- Set visible history length to 1 day
- Download history from RuuviTag
- 1 day history gets downloaded
- Set visible history length to 2 days
- Try to download 2 days history from RuuviTag
- No history for the first day is downloaded

Seems that on iOS, full 10 days history is always downloaded no matter if user selected 1 or 10 days for history length. It's not optimal either because it's making downloading time longer.

Let's discuss about this and decide how to modify Android or the both.

**Comment by markoaamunkajo** [comment]
There are good and bad things related to downloading full 10 days data.
@andreevdenis if you can suggest a better way to do it with less downloading happening, please let us know.
Otherwise let's download full 10 days data like we do on iOS.

**Comment by andreevdenis** [comment]
Ignoring view period when syncing GATT for the first time from now on. Always download 10 days first. On second try starting from last sync date (it it's not > 10 days old)

**Comment by markoaamunkajo** [comment]
Works for me, QA passed
