### ISSUE TITLE
Add Ruuvi Cloud plan information on the My Ruuvi Account page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#884]
Details need to be specified better before implementing but we'd need to show at least:

My Ruuvi Account
Signed in user
xxx@yyy.com

Current Ruuvi plan
Ruuvi Cloud Pro

Ruuvi plan’s expiry date
31 March 2023

Information
This is a completely free app that does not support monthly subscription purchases or other in-app purchases. If you are a user of the Ruuvi Gateway router and you are looking for more detailed information about your Ruuvi account, go to our website and sign in.

Tietoja
Tämä on täysin ilmainen sovellus, joka ei tue kuukausitilausten ostoja tai muita sovelluksen sisäisiä ostoja. Mikäli olet Ruuvi Gateway -reitittimen käyttäjä ja etsit tarkempia Ruuvi-tilisi tietoja, siirry kotisivuillemme ja kirjaudu sisään.

**Comment by markoaamunkajo** [comment]
Denis : I can show subscription name and expiration date. Someone should write instructions and provide links

**Comment by markoaamunkajo** [comment]
@andreevdenis content for My Ruuvi Account has been updated to card description

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@andreevdenis let's simplify this for 2.0 release, use what is shown in iOS build currently.

 We need to improve this after 2.0.
 
 
![photo_2023-02-17 10 24 57](https://user-images.githubusercontent.com/50437378/219542261-90789496-f718-404e-b0b6-9f99527dba2f.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed, moving to 2.1 and we will review with @laurijamsa

**Comment by markoaamunkajo** [comment]
Closing this issue for now as topic is moved to internal discussion.
