### ISSUE TITLE
Show (an orange?) low battery icon on dashboard and sensor card

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#888]
We need a UI design for this please

**Comment by andreevdenis** [comment]
Default battery icons
![image](https://user-images.githubusercontent.com/24788772/207336059-69901fa0-676b-429e-9e21-92f135177fcb.png)

**Comment by sini-maaria** [comment]
This could work:

<img width="387" alt="Screenshot 2022-12-14 at 8 34 32" src="https://user-images.githubusercontent.com/19531763/207524148-7468d2e4-84bf-427d-81e0-e4abdec140e2.png">

**Comment by DG12** [comment]
Please review 
station.ios [Tag name incorrectly displayed In all caps](https://github.com/ruuvi/com.ruuvi.station.ios/issues/5) 

I notice the the (simulated?) screen shot shows names is the case they were enter with. This applies to android, IOS and web.

**Comment by markoaamunkajo** [comment]
Asking from @sini-maaria about showing battery icon also on sensor card

**Comment by andreevdenis** [comment]
Sensor card battery indicator is implemented like this fair now:

![Screenshot_20221222-015040.png](https://user-images.githubusercontent.com/24788772/209018281-2d2326f0-e380-47af-97c2-824afdc04950.png)

**Comment by andreevdenis** [comment]
@sini-maaria 
Need some changes to battery icon for light theme. Better use solid gray color fro top part instead of transparent.
![image](https://user-images.githubusercontent.com/24788772/209740260-18187b43-ad6a-4e06-b640-de3a46fd3539.png)

**Comment by sini-maaria** [comment]
Svg in Telegram

**Comment by andreevdenis** [comment]
New icon is already in 1.16.8. Looks good in both themes.

**Comment by markoaamunkajo** [comment]
QA passed
