### ISSUE TITLE
Additional new set of backgrounds

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#889]
Description:

@sini-maaria will be asked to provide few new backgrounds

**Comment by sini-maaria** [comment]
<img width="297" alt="Screenshot 2022-12-27 at 17 41 55" src="https://user-images.githubusercontent.com/19531763/209689917-29bd922f-09de-434f-8021-a38ccf0e9519.png">

![default-bgs-01](https://user-images.githubusercontent.com/19531763/209689943-0242d5b2-2c82-4213-b98f-69ded16b4142.jpg)
![default-bgs-02](https://user-images.githubusercontent.com/19531763/209689945-7ae4e57d-8fe7-4e5a-b6f3-969bec0128a8.jpg)
![default-bgs-03](https://user-images.githubusercontent.com/19531763/209689947-7b009dbe-1bb3-44b6-964b-9a17eb7bd930.jpg)
![default-bgs-04](https://user-images.githubusercontent.com/19531763/209689949-203ea35e-8ca5-4b94-9d6a-d2b148cf6d4c.jpg)

**Comment by sini-maaria** [comment]
Some changes:
- Only one default image (eye) should be visible if user hasn't chosen an image yet.
https://user-images.githubusercontent.com/19531763/209689945-7ae4e57d-8fe7-4e5a-b6f3-969bec0128a8.jpg

- There will be 6 other default images on the Ruuvi Gallery:

![bg1](https://user-images.githubusercontent.com/19531763/210343537-e77e885b-1578-403b-986c-d037a7c85e38.jpg)
![bg2](https://user-images.githubusercontent.com/19531763/210343554-837d20c3-59e7-4bfe-8004-dcc2e5d7a942.jpg)
![bg3](https://user-images.githubusercontent.com/19531763/210343559-c6e75742-1f5c-4b3b-afe0-20ee48224d9e.jpg)
![bg4](https://user-images.githubusercontent.com/19531763/210343562-3513dfa5-f547-4a86-b978-45652f599de3.jpg)
![bg5](https://user-images.githubusercontent.com/19531763/210343564-d7125127-3b00-4702-a17b-0c6f81f83e27.jpg)
![bg6](https://user-images.githubusercontent.com/19531763/210343565-e0086267-d051-430a-87a7-6f33a2787115.jpg)

**Comment by sini-maaria** [comment]
An example of new default images on web station:
<img width="1467" alt="Screenshot 2023-01-03 at 12 56 21" src="https://user-images.githubusercontent.com/19531763/210344017-3d80fd0b-ab66-4202-ae0d-243f2cc7d4dd.png">

**Comment by andreevdenis** [comment]
@sini-maaria 
1) can we instead of selecting 1 specific eye image get a random from 4 eye images?

2) will there be more default images or I can pass this issue to testing?

**Comment by markoaamunkajo** [comment]
Discussed in meeting this one is completed
