### ISSUE TITLE
(1.15.8) no sensors found on Android (7.0), iPhone app is fine, computer BT dongle sees data

### ISSUE THREAD

**Issue by usvi** [ruuvi/com.ruuvi.station#892]
Hello,

At some point it seems Ruuvi Station has stopped receiving stuff on my Android 7.0. My wife tried Ruuvi Station on her iPhone thingy and it lists stuff fine. I can also see the raw data on my computer:

[CHG] Device DD:DA:C4:7C:F3:5A ManufacturerData Key: 0x0499
[CHG] Device DD:DA:C4:7C:F3:5A ManufacturerData Value:
  05 15 0e 21 9a c4 8e 00 28 00 10 04 08 79 36 e8  ...!....(....y6.
  5c 01 dd da c4 7c f3 5a                          \....|.Z        

Just wondering here what has happened.. I reinstalled the station, no effect. Version is 1.15.8 . Bluetooth is on, all permissions requested were given.

(BTW why have ruuvitag_fw and ruuvi-sensor-protocols been archived?)

**Comment by ojousima** [comment]
> At some point it seems Ruuvi Station has stopped receiving stuff on my Android 7.0.

I need to reboot my Android phone every few days to see any Bluetooth devices at all. Does a phone reboot help?

> (BTW why have ruuvitag_fw and ruuvi-sensor-protocols been archived?)

ruuvitag_fw was rewritten and is now under ruuvi.firmware.c, ruuvi-sensor-protocols has moved under docs.ruuvi.com

**Comment by andreevdenis** [comment]
Prior to Android 12 version Location permission and Location enabled is needed to work with Bluetooth devices. Please check if Location is permitted for Ruuvi Station and if Location is enabled globally.

**Comment by markoaamunkajo** [comment]
@usvi Please install latest 2.x version and let us know if this issue still persists. Also, check latest firmware in app and update if available.

**Comment by usvi** [comment]
Yes, I will try. Sorry about my late replies, I have a horrible work backlog.

**Comment by markoaamunkajo** [comment]
Closing this issue for now. Please report back if this issue still persists.
