### ISSUE TITLE
Make the bottom menu bar transparent everywhere

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#893]
Make the bottom menu bar transparent everywhere

**Comment by andreevdenis** [comment]
There's a small issue with making sensor settings navigation bar transparent. Code that ensures that contents of collapsible group will be visible after unfolding works incorrectly with transparent navigation. Should I spend more time on this?

Lauri: It is fine that it's transparent on dashboard, card vire and history view only for now I think, no need to have transparent footer on settings pages

**Comment by markoaamunkajo** [comment]
@andreevdenis is this a big task to do?

**Comment by andreevdenis** [comment]
Not big in general but my comment from Jan 5 is still valid. Currently I don't know how to fix it. Maybe on other screens will be other issues.

**Comment by andreevdenis** [comment]
@markoaamunkajo

**Comment by markoaamunkajo** [comment]
@andreevdenis this looks unnecessary, discussed with Lauri and we will close this issue for now.
