### ISSUE TITLE
Add sensor setting: Unclaim ownership

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station#896]
On sensor settings page:

When a use has claimed the ownership of a sensor, menu shouldn't change. User should be able to see the subpage.

On subpage the button should change from "Claim ownership" to "Unclaim ownership".

**Comment by andreevdenis** [comment]
Already implemented

**Comment by markoaamunkajo** [comment]
Similar subpage as in Force Claim but when ownership is assigned to signed in account then 

Show arrow on Owner field after email address
Tap on arrow to forward to Unclaim page


![Image](https://user-images.githubusercontent.com/50437378/235576908-799763fb-5cda-4251-92d3-4af1d1a667b8.jpg)
![Image](https://user-images.githubusercontent.com/50437378/235576907-bc75e189-b53d-4430-9c4c-dbf4ae60e412.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
