### ISSUE TITLE
Small chart fixes

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#898]
1) When sensor was offline for at least 1 day and user has selected 1 day as view period - the page with charts is completely empty. There should be a message: "no data for selected interval"

![image](https://user-images.githubusercontent.com/24788772/211615666-1aec0404-2489-49ae-901c-d43afb9625ad.png)

2) Partly visible Y axis values don't look good

![image](https://user-images.githubusercontent.com/24788772/211615698-366d1dfc-071a-4402-9e49-15202ac28673.png)

3) Remove "Chart view period" from settings.

![image](https://user-images.githubusercontent.com/24788772/211615753-0c45df97-93bc-48ea-a57d-14347077fc1a.png)

**Comment by markoaamunkajo** [comment]
Build 1.16.11 1 day view completely zoomed out looks still truncated on X axis on S8. I have default font size.

![1day_view](https://user-images.githubusercontent.com/50437378/211781630-04b8f245-952b-4c61-81eb-2ceb5389660f.jpg)

**Comment by andreevdenis** [comment]
Now count of X axis labels depend on font size (and regional time format) so now it should fit even with extreme user font size.

**Comment by markoaamunkajo** [comment]
QA passed
