### ISSUE TITLE
New Dashboard: app doesn't remember screen after minimize

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#906]
Description:

User on 1.16.12 has signed to Cloud and is using Cloud Mode. He browses to sensor chart screen and minimises app, then returns back to app.

Actual: App opens on Dashboard screen
Expected: In this case should be possible to return to sensor chart screen where user left from

https://user-images.githubusercontent.com/50437378/212804262-b26cc0f0-787c-457d-9e75-089eeb918f27.mp4

Related card: https://github.com/ruuvi/com.ruuvi.station/issues/854

**Comment by andreevdenis** [comment]
I believe we agreed to not implement this part.

**Comment by andreevdenis** [comment]
This is possible if you've set it in Developer options:

**Comment by andreevdenis** [comment]
my Samsung S9 works as expected.

**Comment by markoaamunkajo** [comment]
@andreevdenis weird but in 1.16.13 it works for me on S8 but doesn't work on S5. I made clean install for both, also waited for cloud sync to see if it made any difference but it didn't.

**Comment by laurijamsa** [comment]
does this still exist?

**Comment by markoaamunkajo** [comment]
Not spotted anymore in 1.16.18. I cannot confirm for S5 since I don't have access to it anymore.
Closing this for now, opening again if it's ever spotted again.
