### ISSUE TITLE
New welcome screen

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#907]

**Comment by markoaamunkajo** [comment]
@andreevdenis 
New onboarding texts in Pull request https://github.com/ruuvi/station.localization/pull/126

Also check screen changes: https://github.com/ruuvi/com.ruuvi.station/issues/934

**Comment by markoaamunkajo** [comment]
Waiting for language strings build.

**Comment by markoaamunkajo** [comment]
QA passed
