### ISSUE TITLE
Charts selected day range show incorrect X axis

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#908]
Description:

1.16.13

User first selected 1 day X axis and it showed correctly in all charts.
He then changed X axis to show 7 days.

Actual: When viewing chart now it shows 3 days range.
Expected: Should be showing 7 days range.

https://user-images.githubusercontent.com/50437378/213605683-b89aa2fa-5a17-49a1-bfa0-2209c5a014d3.mp4

**Comment by andreevdenis** [comment]
In your video it's clearly showing 7 days range. We can see reduced labels count - to avoid labels overlapping.

**Comment by markoaamunkajo** [comment]
It's a bit confusing for user to be honest. Axis is split into 3 timestamps, but we show 7 days (?) and there is no risk for overlapping with 3 timestamps. My initial thought was that I see only 3 days and there must be something wrong in what I see.

**Comment by andreevdenis** [comment]
This is what I see with S8 and slightly increased font size. You're using significantly bigger font 
![Screenshot_20230120-094839_Ruuvi Station](https://user-images.githubusercontent.com/24788772/213634932-b0c669b7-7243-4115-ad73-957c762c8998.jpg)

**Comment by markoaamunkajo** [comment]
![Screenshot_20230120-135957_Settings](https://user-images.githubusercontent.com/50437378/213636559-eb68eb18-de78-4190-a281-34a536999a98.jpg)

Ok closing this issue since system font.
