### ISSUE TITLE
Translation fixes to check in app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#914]
Description:

Sync Disconnected message not using language file on charts page, not sure which string is correct.

 "ident_ios": "BluetoothError.disconnected",
      "ident_android": "",
      "ident_webui": "",
      "en": "Disconnected",
      "fi": "Yhteys katkaistu",
      "ru": "Соединение разорвано",
      "sv": "Frånkopplad",
      "fr": "Déconnecté",
      "de": "Getrennt"
      
      "ident_ios": "TagSettings.ConnectStatus.Disconnected",
      "ident_android": "disconnected",
      "ident_webui": "",
      "en": "Disconnected",
      "fi": "Ei yhteyttä",
      "ru": "Отсоединен",
      "sv": "Frånkopplad",
      "fr": "Déconnecté",
      "de": "Getrennt"
      
      
      
![de-2](https://user-images.githubusercontent.com/50437378/216914642-c447dca3-dc30-4ff0-8ab4-1a44b266ee17.jpg)

**Comment by andreevdenis** [comment]
I'm using one with ident_android filled.

![image](https://user-images.githubusercontent.com/24788772/216981413-a53656aa-2486-4451-a9bb-3a33467f7ffb.png)

**Comment by markoaamunkajo** [comment]
QA passed
