### ISSUE TITLE
New sign in screen

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#916]
![ruuvi-welcome-11](https://user-images.githubusercontent.com/24788772/217394421-fa8a72ad-4c57-465d-a84c-8ecccda7fb03.jpg)
![ruuvi-welcome-12](https://user-images.githubusercontent.com/24788772/217394427-0d3721f6-1994-43e0-8069-6ead43cda2c0.jpg)
![ruuvi-welcome-13](https://user-images.githubusercontent.com/24788772/217394428-c2e692df-a753-4e80-8e98-9e17bcd28d25.jpg)
![ruuvi-welcome-14](https://user-images.githubusercontent.com/24788772/217394430-936aabd5-513a-4ee4-8e7c-ef58aa528af9.jpg)

**Comment by markoaamunkajo** [comment]
@andreevdenis Improved strings for new sign in page

Also added one new ident to be used at bottom of page called "benefits_sign_in"

![sign_in_page](https://user-images.githubusercontent.com/50437378/219556268-f914c8fc-fdc8-4424-8a24-64f8d8ae5fbe.jpg)

**Comment by markoaamunkajo** [comment]
@andreevdenis  Benefits page has also changed according to the screen below:

![benefits_page](https://user-images.githubusercontent.com/50437378/219568739-878c984e-af22-4191-a213-411bc600fadb.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
