### ISSUE TITLE
DateTime timezone is missing a :

### ISSUE THREAD

**Issue by MatthK** [ruuvi/com.ruuvi.station#92]
The time string in the gateway is omitting a : in the time zone.

"time":"2020-04-20T11:15:57+0800"

SQL Server can't convert this format into a datetime unless there is a : in the timezone like this:

"time":"2020-04-20T11:15:57+08:00"

**Comment by laurijamsa** [comment]
@andreevdenis is this something that requires actions?

**Comment by andreevdenis** [comment]
@laurijamsa @ojousima we asked about it in slack, because fixing it can break someones logic

**Comment by ojousima** [comment]
No-one has protested in Slack, I think we could take this on ToDo list?

**Comment by MatthK** [comment]
I got around it with adding the missing ":" to the string before inserting it into the database. I guess once that is updated, I need to remove that.

**Comment by markoaamunkajo** [comment]
QA passed build 1.4.1
