### ISSUE TITLE
Editing a sign in token after typed it wrong first is not possible (easy)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#929]
If token didn't work (typed wrong for example), automatically clear the fields and allow user to enter a new one.

EDIT: Seems that backspace works but it was not obvious to me. First I thought it's not possible to type a new one. Better to automatically empty the fields and allow user to type a new one.

Main card: https://github.com/ruuvi/com.ruuvi.station/issues/916

**Comment by markoaamunkajo** [comment]
QA passed
