### ISSUE TITLE
Nothing is happening after signing in and wide letters don't fit in the boxes

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#930]
Froze here:

![telegram-cloud-photo-size-5-6300621984651916307-y](https://user-images.githubusercontent.com/1311912/219248294-df5d8acf-e20e-4a56-91f9-439412e9b3dc.jpg)

Before this happened, I one time typed a wrong token first. Maybe related.

Main card: https://github.com/ruuvi/com.ruuvi.station/issues/916

**Comment by andreevdenis** [comment]
@markoaamunkajo @laurijamsa 
Please try to reproduce. I tested this screen many times and it was working smoothly. Token should be cleared not after failed atempt.

**Comment by markoaamunkajo** [comment]
QA passed
