### ISSUE TITLE
New no added sensors page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#932]
Description:

In designs there is new no added sensors page to be added to 2.0

<img width="357" alt="design" src="https://user-images.githubusercontent.com/50437378/219262159-a43d6bca-e127-4968-90f3-954cf2deb7c5.png">

Related card: https://github.com/ruuvi/com.ruuvi.station/issues/916
Main card: https://github.com/ruuvi/com.ruuvi.station/issues/854

**Comment by markoaamunkajo** [comment]
@andreevdenis added 1 new local sensor and removed it, I see the old add new sensors page.

Please remove the old add sensors page from app, we will only use the new one.

![Android_add_new_sensors](https://user-images.githubusercontent.com/50437378/219541140-ea8a7548-b647-4fb7-9e3e-1a69cde70c46.jpg)

**Comment by andreevdenis** [comment]
It actually was a sensor card without sensor. Now I've changed behavior and after removing sensor user will go to dashboard.

**Comment by markoaamunkajo** [comment]
QA passed
