### ISSUE TITLE
New onboarding: screen changes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#934]
Description:

New screen changes for onboarding

Screen 2 will be removed 
![screen2](https://user-images.githubusercontent.com/50437378/219336947-6d5ab0ad-3493-44ce-bfa0-1e451ddd71ee.jpg)

Screen 4 has title and subtitle swapped

![screen4](https://user-images.githubusercontent.com/50437378/219337034-b387e497-62b5-4af7-94ab-09c38e04dded.jpg)

**Comment by andreevdenis** [comment]
It took a couple of hours to make screen 2 look same way as design.

**Comment by andreevdenis** [comment]
Deleting it through tears

**Comment by markoaamunkajo** [comment]
@andreevdenis looks like we forgot to change design to one screen. Please follow the attached design.

![screen7_redesign](https://user-images.githubusercontent.com/50437378/219546283-9c876473-7225-4d42-890d-62b6d35818cc.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
