### ISSUE TITLE
Dashboard: view doesn't sync from iOS to Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#935]
Description:

User selected Simple View from iOS dashboard view menu

Actual:
View selection was not synced over cloud to Android

Expected:
View selection sync works on iOS when switched on Android so it should work the other way around as well.

**Comment by andreevdenis** [comment]
It actually got synced but app is not instantly applying the setting. Only after app reopen. Will fix.

**Comment by markoaamunkajo** [comment]
QA passed
