### ISSUE TITLE
Sharing screen for sensor without Gateway looks ugly

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#938]
![image](https://user-images.githubusercontent.com/24788772/220303644-1971ef5c-ce10-4f7e-bca3-5b40e825ea98.png)

**Comment by andreevdenis** [comment]
Message on top of this screen: Only sensors within range of your Ruuvi Gateway can be shared. If you don't have one yet, get it on ruuvi.com/gateway


Should this be changed?

**Comment by andreevdenis** [comment]
Discussed with Lauri and decided to remove link to Gateway purchase.

**Comment by markoaamunkajo** [comment]
Checked in app during other tests and this looks ok for now. Closing this issue.
