### ISSUE TITLE
Swipe left on first sensor card to bring dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#941]
Description:

User is on first sensor card and swipes left to go back to overview.

Actual:
Nothing happens

Expected:
Show dashboard

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1299

**Comment by andreevdenis** [comment]
Please let's not implement this. You already can go from any sensor card back to dashboard by swiping. All you need for this is abandon outdated 3-buttons navigation and use geasture navigation. It's 2023 outside. I really don't get why you still use it with latest smartphones. @markoaamunkajo @laurijamsa 


https://user-images.githubusercontent.com/24788772/221842218-d937ac41-a256-4a0e-9fdc-14c4185600d5.mp4

**Comment by markoaamunkajo** [comment]
Compared few applications, and found this gesture is only default on something like Twitter. Let's close this for now, since we don't see the benefit from implementing it.
