### ISSUE TITLE
Optimize cloud calls for free subscription sensors

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#943]
List of changes to app for this task:

1) Do not request history for sensor if subscription does not support history. (This needs changes to cloud side - adding maxHistoryDays to sensor-dense endpoint)

2) Caching list of users to whom sensor was shared. Local table will be created to store these emails of users.

3) Alerts can be synced from sensor-dense response instead of separate call to alerts endpoint.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1333
Web card: https://github.com/ruuvi/com.ruuvi.station.webui/issues/274

**Comment by markoaamunkajo** [comment]
QA passed
