### ISSUE TITLE
Check app and fix places where app crashes without Internet

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#949]
2.0.5 crash after enabling airplane mode on:
sign out
setting/modifiyng alarm
calibrating
removing cloud sensor
changing background
changing dashboard type (simple/image)
changing almost any setting

**Comment by markoaamunkajo** [comment]
2.0.6 Signed in to Ruuvi Cloud, then switched on Airplane mode and signed out.
App crashed.

**Comment by markoaamunkajo** [comment]
@andreevdenis when no internet this also happens, it moves me away from sign in page automatically before I can add email. 2.0.6
https://user-images.githubusercontent.com/50437378/223039981-15957d0b-128c-4d94-9ece-fc21d1abdb6a.mp4

**Comment by markoaamunkajo** [comment]
QA passed
