### ISSUE TITLE
View was not remembered 

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#954]
Description:

S21 Ultra OS13, OneUI5.1

Used app normally, after 2 days reproduced this issue
App minimized with home button, next launch view was not remembered, instead app goes to dashboard view when opening.
Also same on history view, settings view, all views take to dashboard.

**Comment by markoaamunkajo** [comment]
This could be some kind of silent crash?

**Comment by andreevdenis** [comment]
it's possible

**Comment by andreevdenis** [comment]
Connected to #962

**Comment by markoaamunkajo** [comment]
Will be handled on https://github.com/orgs/ruuvi/projects/17/views/1?pane=issue&itemId=24608891
Closing as duplicate
