### ISSUE TITLE
Sign in: switch sign in screen order to improve ux

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#958]
Description:

Few users were reporting to us that we are forcing them to sign in and seems that they simply missed the skip button at the bottom.

We switched the sign in and benefits screens order

![suggestion](https://user-images.githubusercontent.com/50437378/222665995-5799fe7f-3740-43be-8d65-4c22b4e9f882.jpg)

New language strings to be added soon

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1342

**Comment by markoaamunkajo** [comment]
@sini-maaria 

What do you think about this solution?
Benefits screen has limited space, if we use Continue button and force user to go to Sign in page then all information is shown, even though he cannot skip on benefits page, only on Sign in.

![Benefits_improvement_suggestion](https://user-images.githubusercontent.com/50437378/228425189-4003c560-019d-4000-849c-1313ee057dff.jpg)

**Comment by sini-maaria** [comment]
It is better. We can go with that for now.

**Comment by markoaamunkajo** [comment]
QA passed, language string fix pull request added
