### ISSUE TITLE
Starting foreground service crash (from crashlytics)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#962]
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5bb0c29 u0 com.ruuvi.station/.bluetooth.BluetoothForegroundService}

and many similar crashes in logs. 

Probably can be reproduced with Android 13 phone. But I can't do it with my phone for some reason.

**Comment by markoaamunkajo** [comment]
@andreevdenis Asked feedback also from Lauri and we concluded that nobody's seen this crash occur. Moving the card to backlog, we will probably bump into it during later testing.

**Comment by andreevdenis** [comment]
I was able to reproduce this a couple of times recently. I'll try to investigate this issue

**Comment by markoaamunkajo** [comment]
Moving this to done and will follow up on Firebase logs. Apparently difficult issue to reproduce (seen only when restarting phone and launching app too fast?)
