### ISSUE TITLE
Add last data source icon to dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#963]
Description:

Let's add last data source icon also to dashboard view. We'll use the same icon as in Full Image View.

![dash_source_icon](https://user-images.githubusercontent.com/50437378/223300078-7b48cee5-d5b2-40f5-8b72-5a2d989ba528.jpg)

@sini-maaria here is mockup for source icon location. Maybe you have best idea where it should be and if colour/transparency needs work.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1356

**Comment by sini-maaria** [comment]
Use the same icons we have on card view, only smaller. 

![Screenshot 2023-03-29 at 9 08 08](https://user-images.githubusercontent.com/19531763/228444422-f8a5d6db-1922-4bd1-b58d-9c154c6f969d.png)

**Comment by markoaamunkajo** [comment]
QA passed
