### ISSUE TITLE
Show cards that have no datapoints

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#964]
Description:

We currently hide cards that have no datapoints
Let's show these cards

Steps:

1. shut down gateway
2. add new sensor that was never seen by cloud
3. claim sensor to cloud
4. power off sensor, delete all app data
5. sign in to app

Implement same way as on iOS.
If you don't have sensors to test this, ask Otso to delete a sensor.

![Image](https://user-images.githubusercontent.com/50437378/232972016-6a65ed35-60bd-402d-9d64-cf03408aa201.jpeg)

**Comment by markoaamunkajo** [comment]
Let's implement same way as on iOS.

**Comment by markoaamunkajo** [comment]
Looks like removing this sensor doesn't work.


https://github.com/ruuvi/com.ruuvi.station/assets/50437378/5cc99c5a-353b-4b6a-b7f5-2e101f0f23a1

**Comment by andreevdenis** [comment]
@markoaamunkajo yep

**Comment by markoaamunkajo** [comment]
QA passed
