### ISSUE TITLE
Shared emails list when large font

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#968]
Description:

2.1.0

Emails list on share sensors page becomes almost unscrollable if user is using large font. Maybe this could be improved somehow.

https://user-images.githubusercontent.com/50437378/225554832-9711ae4c-0310-4c4a-ba31-7a0ff33df0cc.mp4

**Comment by andreevdenis** [comment]
Added a little bit more space for bottom part of this screen

**Comment by markoaamunkajo** [comment]
This will do for now, moving to done. Let's consider the redesign at a later point.
