### ISSUE TITLE
Dashboard: Show selected icon after selected view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#978]
Description:

Please show selected view with checkmark on **right** side of the view name in list.

![IMG_A256B2725E11-1](https://user-images.githubusercontent.com/50437378/228447488-59377858-6058-4bb2-a25a-c3605440b6dd.jpeg)

**Comment by laurijamsa** [comment]
Closing this one, a new spec coming in a separate issue :)
