### ISSUE TITLE
Landscape: card issue on dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#981]
Description:

Screenshot from Lauri's S21, I wasn't able to replicate yet.

![photo_2023-03-30 13 11 10](https://user-images.githubusercontent.com/50437378/228745575-dac31fc3-8417-41ab-83b7-2b22937f8e51.jpeg)

**Comment by andreevdenis** [comment]
What is wrong here?

**Comment by markoaamunkajo** [comment]
Too much spacing between cards in right side row here 
<img width="386" alt="Screenshot 2023-03-30 at 15 56 18" src="https://user-images.githubusercontent.com/50437378/228784228-9494c86d-956a-403a-8bfd-c9605407583e.png">

**Comment by markoaamunkajo** [comment]
This is ok for now
