### ISSUE TITLE
Sync icon when downloading

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#990]
Description:

We don't currently show syncing status when data is being downloaded from cloud
Should we animate the icon?

![Image](https://user-images.githubusercontent.com/50437378/232962138-f2260f7c-4fc4-45b5-83f4-1077b959b232.jpg)

Rotate antenna would be cool

**Comment by DG12** [comment]
Can you please add detail of when downloading you mean.
Although animations are "pretty" counters or % are much more informative.
Animations as separate processes are deceiving as they continue "spinning" without any activity actually occurring .

**Comment by DG12** [comment]
Thanks for your consideration

**Comment by markoaamunkajo** [comment]
Closing as decided not to implement as animation
