### ISSUE TITLE
Check how calibration change is applied from cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#995]
Description:

Check how calibration change is applied from cloud

**Comment by andreevdenis** [comment]
I've checked code and it looks good to me. It should work properly according to current solution for calibration. @markoaamunkajo please check if we got some issues.

**Comment by markoaamunkajo** [comment]
Offset is not added until new datapoint is received, which is still incorrect.
Discussed with Lauri that we won't touch this until card https://github.com/ruuvi/com.ruuvi.station/issues/1005

Closing this issue as completed.
