### ISSUE TITLE
Scan with NFC and show RuuviTag info / add new sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#999]
Description:

When app in foreground (any page), and NFC is enabled by user in device

Touch sensor with NFC
Show info popup in app

1. If sensor not added yet, show Add button

Name (show default Ruuvi XXXX name)
Unique ID
MAC
Firmware version

- copy to clipboard feature in unique ID and MAC

2. If sensor already added, move user to full image view

Show info popup on full image view page

- copy to clipboard feature in unique ID and MAC

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/535ecfd0-6144-43b8-9213-e3c13e1af0d4)
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/6fdf2c93-e14a-48fd-9611-7de1db5eda42)

**Comment by markoaamunkajo** [comment]
@andreevdenis 

I see that we don't have any feedback for copy to clipboard status on this popup and also on the sensor settings info.
Let's fix it showing Copied! text when text was copied, would it be difficult to implement?

Also, let's center those buttons at bottom of the popup.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/b43c08c0-f536-4bd4-a421-926ade9be046)

**Comment by markoaamunkajo** [comment]
More info, looks like the copy text not appearing is related to S10+ with OS12

**Comment by markoaamunkajo** [comment]
@andreevdenis 

I remember we had limitation to implement sensor details popup to show on sensor page when user is moved to sensor card via NFC scan. Is there any way around this? Some users would benefit from seeing MAC and unique ID on the sensor card page.

**Comment by andreevdenis** [comment]
@markoaamunkajo @laurijamsa 
What if we show dialog in both cases: for new and existing sensors? If sensor already exist we will show button "Go to sensor card" instead of "Add sensor".  Going to sensor and then show dialog will be trickier. 

There will be no dialog from add sensor screen for now, we can add it after rewriting to Compose.

**Comment by laurijamsa** [comment]
Sounds good to me

**Comment by markoaamunkajo** [comment]
QA passed
